### ISSUE TITLE
Inside io.js podcast season 1

### ISSUE THREAD

**Issue by mikeal** [nodejs/evangelism#1]
Let's do a podcast about io.js :)

Rather than just a round table or raw interviews we should edit a bunch of things together around specific topics.

First, let's build a list of show topics and then use that to build out an initial interview list.

Show Ideas:
- Why io.js? (Why was the project created, why did we fork)
- The TC and open governance, consensus seeking, etc.
- The i18n community, creation and current workflows
- The roadmap
- What is libuv
- `trace_event`
- AsyncWrap
- Streams WG

**Comment by bnb** [comment]
Some I have: 
- How to get actively involved, in detail (one for each WG?)
- Interviews with Project Leaders (Isaac, Rod V., you, Fedor, Bert, and Trevor are names I know, may/may not be the ones we'd do) to get their individual takes on where the project is, and where it's going
- "Educational" episode, where developers of Node projects can learn why they should update their projects to support io.js (similar to your first idea, but more specific)

**Comment by mikeal** [comment]
> How to get actively involved, in detail (one for each WG?)

Maybe at the end of _every_ episode we close with how to best get involved in what we've been talking about?

> Interviews with Project Leaders

Definitely, but I want to ask them questions about several of these topics at once so that they we have content from many people on each topic.

> "Educational" episode, where developers of Node projects can learn why they should update their projects to support io.js

This is a great idea. What is the best way to tackle it? Should we talk to people who switching and talk about how and why they made the move?

**Comment by bnb** [comment]
> > "Educational" episode, where developers of Node projects can learn why they should update their projects to support io.js
> 
> This is a great idea. What is the best way to tackle it? Should we talk to people who switching and talk about how and why they made the move?

Honestly, I was thinking the opposite approach of how I interpret what you're suggesting here--taking people who know their stuff and having them detail why io.js is good for a specific task or feature, like "Why you should use io.js to run the back-end of your mobile application," (a la LinkedIn) or "Why io.js is good choice for an app you need to be able to scale." 

I'm just spit-balling, but that's the type of thing I was thinking of.

**Comment by mikeal** [comment]
- "This importance of now"

Basically, an episode talking about how important it is that the community doing _current_ work is collaborating on the same current line of development.

**Comment by mikeal** [comment]
- The logo thread

**Comment by dotproto** [comment]
I've got more than a passing interest in podcasting. I'd be happy to help with editing, site work, etc.

**Comment by dotproto** [comment]
I should also mention that I signed up for early access to PodClear (http://www.podclear.com/) on behalf of the io.js Audio podcast. It could be quite helpful in creating a more polished podcast.

**Comment by bnb** [comment]
@svincent Looks like an awesome service. I guess that's something we need to decide--will the podcast be audio-only or video + audio tracks? There's not a problem with audio only, and I'm pretty sure just about everyone is going to agree with that assessment, but it's worth putting the idea out there of a video podcast through something like Hangouts and then ripping the audio for an audio version.

**Comment by mikeal** [comment]
podclear looks awesome, it solves one of the bigger problems I was anticipating :)

**Comment by dotproto** [comment]
I'd like to give pod clear a test run this weekend. Anyone interested in syncing up on Saturday around 12 PM PST to do some tests?

**Comment by mikeal** [comment]
@svincent they opened up access? I can do tomorrow morning PST.

**Comment by dotproto** [comment]
@mikeal I signed up for it (and got access) when I created the io.js Audio SoundCloud account. I've got the app installed and I'm ready to start putting it through its paces to see if it will help with the recording process.

**Comment by mikeal** [comment]
@svincent great, is there a time tomorrow morning PST that works for you?

**Comment by dotproto** [comment]
@mikeal My schedule is completely open; I can do anything as early as 8 AM PST.

**Comment by mikeal** [comment]
ok, i'll ping you when i wake up here and we'll try it out :)

**Comment by bnb** [comment]
@mikeal @svincent I'd also be able to get in, if it's a multi-person thing. Morning PST is perfect for me.

**Comment by dotproto** [comment]
Absolutely @bnb! 3 people would be great if the plan is to do a multi-person podcast. The closer we can test to actual use case the better, IMO.

**Comment by Fishrock123** [comment]
:+1:

**Comment by mikeal** [comment]
So, if you want to do a multi-person panel style podcast we should just do it on NodeUp :)

**Comment by timoxley** [comment]
+1 just do it on NodeUp.

**Comment by bnb** [comment]
Has this been resolved?

**Comment by bnb** [comment]
Closing, this has been idle long enough.
