### ISSUE TITLE
Evangelism: Weekly Update for 2015-06-26

### ISSUE THREAD

**Issue by Gioyik** [nodejs/evangelism#101]
It&rsquo;s Friday, Friday... Gotta get down on Friday!

**Comment by bnb** [comment]
Slide deck: Bluemix Webinar: Deploying a Full Stack Node.js Application to IBM Bluemix - https://speakerdeck.com/bradleyholt/bluemix-webinar-deploying-a-full-stack-node-dot-js-application-to-ibm-bluemix

**Comment by bnb** [comment]
Watson Developer Cloud Node.js client. https://github.com/watson-developer-cloud/nodejs-wrapper

**Comment by bnb** [comment]
Device Atlas API now supports Node.js: https://deviceatlas.com/blog/deviceatlas-api-node-js?utm_source=twitter&utm_medium=update&utm_campaign=node%20js%20support

**Comment by yosuke-furukawa** [comment]
io.js v2.3.1 is released https://github.com/nodejs/io.js/blob/master/CHANGELOG.md#2015-06-23-version-231-rvagg

**Comment by yosuke-furukawa** [comment]
How to Use Rust with Node.js When Performance Matters http://blog.risingstack.com/how-to-use-rust-with-node-when-performance-matters/

**Comment by bnb** [comment]
https://cloudant.com/blog/using-cloudant-with-node-js/#.VYm-q7WJi02

**Comment by bnb** [comment]
A tutorial to help you better understand how to use Cloudant with Node.js: https://cloudant.com/blog/using-cloudant-with-node-js/

**Comment by yosuke-furukawa** [comment]
@bnb 

> A tutorial to help you better understand how to use Cloudant with Node.js: https://cloudant.com/blog/using-cloudant-with-node-js/

This article is not so fresh. the article is published at 2013.

**Comment by yosuke-furukawa** [comment]
@bnb 

> Watson Developer Cloud Node.js client. https://github.com/watson-developer-cloud/nodejs-wrapper

This project does not support io.js and node.js v0.12.

https://github.com/watson-developer-cloud/nodejs-wrapper/blob/master/.travis.yml#L3

I would like to introduce more fresh modules related to the both of node.js and io.js at least.

**Comment by bnb** [comment]
@yosuke-furukawa Thanks for pointing those out. I will actually put time checking the sources in the future, instead of just pulling the headline and link.

**Comment by mcollina** [comment]
What is the process to highlight node conferences on the newsletter? I would love to promote http://nodejsconf.it in the upcoming events? It's in October on the shores of lake Garda, in Italy.

**Comment by Gioyik** [comment]
@mcollina the process is simple. Just put a link here and we will include it on every WU until the event happens. :)

**Comment by mcollina** [comment]
Great! The link is above, and the event is on the 10th of October :)! Thanks!

**Comment by yosuke-furukawa** [comment]
@bnb Yay !! We keep publish good articles :) 

@mcollina yay, nodejsconf.it will be listed in next weekly updates :D

**Comment by yosuke-furukawa** [comment]
On Maintaining a Native Node Module by voodootikigod
http://www.voodootikigod.com/on-maintaining-a-native-node-module/

**Comment by yosuke-furukawa** [comment]
[nodei.co](https://nodei.co/) is running with io.js 

http://twitter.com/rvagg/status/613688739030679552

**Comment by bnb** [comment]
We can probably publish this on the nodejs/nodejs.org repo's blog, with Node branding. When writing it, can you follow the guidelines [here](https://github.com/nodejs/nodejs.org/tree/master/doc/blog)?

**Comment by bnb** [comment]
npm 3.0.0 pre-release: https://github.com/npm/npm/releases/tag/v3.0.0

**Comment by yosuke-furukawa** [comment]
@bnb 

> We can probably publish this on the nodejs/nodejs.org repo's blog, with Node branding. When writing it, can you follow the guidelines here?

good!

But we need to discuss how do we handle our current blog(medium) and nodejs/nodejs.org on the evangelism wg meeting.

IMO, We would be better to publish this on the both blog platforms. after evangelism wg meeting, we will publish this weekly updates on the nodejs/nodejs.org.

How do you think ??

**Comment by diagramatics** [comment]
I was wondering about the localization teams' fate as well. Are we still going to work somewhat separately and publishing it on our blog platform of our choice rather than assimilating to the foundation's site too.

**Comment by Gioyik** [comment]
:+1: to all you. Let's add this as P1 point for the meeting. We had discussed about the change publishing WU but not complaining about teams who localize them.

**Comment by Gioyik** [comment]
I created a PR (#107). Let's check it

**Comment by bnb** [comment]
@diagramatics The blogging platform we're talking about (the one other than Medium) is the official nodejs.org blog, which I would say falls under the Foundation's reign. Since the Node blog's posts live as .md files, I don't see a huge issue with the i18n groups. They already pull .md files from this repo, so either they would just change where they're pulling from or they would also live here.

**Comment by diagramatics** [comment]
No, I wasn't concerned about how the l10n teams would do their jobs in the future, rather if the teams are going to be assimilated into the foundation and share a spot in the official blog if the English version will be posted primarily on the nodejs.org blog in the future.

As for the question if the updates should be posted on Medium or nodejs.org or both, I'd say do both. Medium has a feature where you can import stories by passing a URL so it wouldn't be too much of a hassle.

**Comment by bnb** [comment]
@diagramatics With the first issue, I'd say that's an action item for the Website WG (//cc @nodejs/website) to work out. They're the ones who would decide where the localized blogs would be hosted. 

On the topic of whether they will be brought in or not, IIRC the decision on that was to have a similar structure as before, except official i18n groups would be on the main site - non-official groups can do whatever they want, though.

**Comment by yosuke-furukawa** [comment]
published. https://medium.com/@iojs/io-js-week-of-june-26th-51ab30238256
