### ISSUE TITLE
Update wikipedia page

### ISSUE THREAD

**Issue by mikeal** [nodejs/evangelism#102]
The wikipedia page is quite out of date from the foundation announcement.

https://en.wikipedia.org/wiki/Node.js

We should also probably get a page going for the Node.js foundation.

I can't do the edits myself because it would violate their policies.

**Comment by bnb** [comment]
Can we do the edits, as we're a part of the organization that is Node?

**Comment by mikeal** [comment]
I believe you are allowed to do it. The problem with me doing is that I am directly or indirectly attributed in many of the "source" materials.

**Comment by Gioyik** [comment]
Maybe we can use this issue to collect all the info that would be good to update/add. Then we edit the wiki page with the changes discussed here. What you think?

That will give everybody the idea of what to add, sources, and changes. So, we can make a big (only one, maybe a few) edit on the Wiki with the entire collected info and not multiple (not coordinated) changes with no sense.

**Comment by Trott** [comment]
If someone is interested in this problem, I would recommend at least fixing the first line of the article. As of this writing, it reads:

> In software development, Node.js is an open-source, cross-platform runtime environment for developing server-side Web applications.
- There is no need for `In software development`. The articles for Ruby, Perl, Python, etc. don't include that.
- The word `JavaScript` should appear in that sentence (probably before `runtime`)
- The sentence wrongly implies that Node.js is useful for Web applications only.

**Comment by bnb** [comment]
> Node.js is an open-source, cross-platform JavaScript runtime environment for developing a diverse variety of tools and applications.

@Trott Better?

**Comment by bnb** [comment]
> In September 2015, Node.js v0.12 and io.js v3.3 were merged back together into Node v4.0.[37] This brought V8 ES6 features into Node.js, and a long-term support release cycle.[38] As of 2016, the io.js website recommends that developers switch back to Node.js and that no further releases are planned due to the merger.[39]

The v6 and LTS release information should be added here: https://en.m.wikipedia.org/wiki/Node.js#History

**Comment by Trott** [comment]
@bnb Yes, much better. MAKE THAT EDIT!!!

**Comment by bnb** [comment]
@Trott Edit made! So much better!

**Comment by Trott** [comment]
🎉 That entire first paragraph is now officially a million times better than it was. Thanks!

**Comment by bnb** [comment]
@Trott Absolutely! [Tweeted](https://twitter.com/bitandbang/status/771471292348280832) about this and it got a ton of engagement - people are really interested. We can very much get this going as a community effort.
