### ISSUE TITLE
Nominate @gioyik as a Evangelism WG Contributor

### ISSUE THREAD

**Issue by bnb** [nodejs/evangelism#103]
@gioyik has been involved in the WG for a while now, and seems to be producing outstanding work for it. I am nominating him for Contributor status here in the Evangelism WG. +1 or considerations requested.

**Comment by mikeal** [comment]
+1, did realize he wasn't already :)

**Comment by Gioyik** [comment]
Thanks for the nomination. I really appreciate it :)

**Comment by bnb** [comment]
@Gioyik No problem - you've been regularly active in a period of downtime, and that's what we look for in our collaborators. We really appreciate you, and I want to give credit where credit is due.

**Comment by yosuke-furukawa** [comment]
I already think he is a contributor.
https://github.com/nodejs/evangelism/issues/58

**Comment by yosuke-furukawa** [comment]
what is the difference between member and contributor??? he is listed in here.

https://github.com/nodejs/evangelism#evangelism-wg-members

**Comment by Gioyik** [comment]
Well, I thought this was a nomination to be included on the Nodejs github organization (evangelism group), isn't it?

**Comment by yosuke-furukawa** [comment]
oh i see. I don't have a permission to add you to github organization, @mikeal please add him to Evangelism WG .

**Comment by mikeal** [comment]
Added. Also, there seems to be some confusion as we've noted twitter handles on the README rather than GitHub handles. @tonypujals was also not added to the team yet.

**Comment by subfuzion** [comment]
Thanks for catching!

**Comment by bnb** [comment]
Just went to invite @tonypujals and it seems he's already been invited. Tony, you should have gotten an email (either in the last 2 hours or months ago) from GitHub saying you've been invited to the nodejs Evangelsim WG (io.js if it's old). I believe you can go [here](https://github.com/nodejs), where there will be a bar at the top saying you've been invited to join.

**Comment by Gioyik** [comment]
Thanks a lot of nomination and addition to Github organization. I really appreciate :)

**Comment by bnb** [comment]
@Gioyik No problem - looking forward to working with you more.

**Comment by bnb** [comment]
Closing, @Gioyik is now a collaborator.

**Comment by subfuzion** [comment]
Thanks! I didn't find an old invitation, but I did find the one @mikeal
sent recently, which I accepted. :)
