### ISSUE TITLE
First Evangelism WG Meeting

### ISSUE THREAD

**Issue by bnb** [nodejs/evangelism#105]
As things are going, I think we need to start meeting to make sure almost everyone is on the same page. 

We're going to be taking over the nodejs.org blog, Twitter account (Node and #nodejs get mentioned _a lot_), and other social properties, so we need to find a way to ensure organization and order govern us, and not be a random smorgasbord of information flowing out of every orifice.

I have created a Doodle where we can try to get a time that works for all the WG members: http://doodle.com/ctrss6uf2dx9a28n

If there is a topic you want to be raised, comment here (I will note the comments with the WG during the meeting)  or create an issue. I will be creating issues for some things that I think need to be talked about, but if you have _anything_ you want the group to discuss, don't hesitate to post.

**Comment by rosskukulinski** [comment]
FYI, July 3rd is when Independence Day will be observed in the US (the 4th is on a Saturday).  Many businesses will be closed, including my own :)

**Comment by bnb** [comment]
@rosskukulinski Do you need to be at your business to attend the call? I don't mean that in a harsh way, despite how it may sound - I just want to know. If you're not available certain times that's fine, of course!

**Comment by rosskukulinski** [comment]
ha! yes, of course I don't need to be at my place of business to attend a call.  But I do believe that taking time off of work (which to me includes OSS 'work') to spend uninterrupted time with family is very important.  Hence, I will likely be disconnected that day, and will be encouraging my teammates to do the same.

By all means, if people want to have the first call that day, don't wait up for me.

**Comment by bnb** [comment]
@rosskukulinski I don't mean to impose on your time off - I just live a very different lifestyle than most people, and so I lose touch with how things work. My mind didn't connect having personal time with not working on OSS, as that's the only time I work with it.

**Comment by rosskukulinski** [comment]
No harm done, friend :-)

**Comment by Gioyik** [comment]
I think is ok a meeting with this group. It will be recorded? 

I really like the idea of have an agenda, but please, let's use this issue, I will get crazy with a ton of issues with proposals each one. Will be better coordinate everything for the meeting using this issue.

**Comment by Gioyik** [comment]
Checking the dates, July 1 and July 2 are the best options for everybody. So, what could be the final date?

**Comment by Gioyik** [comment]
I created a formal issue for the meeting. Check it (#108)
