### ISSUE TITLE
Evangelism: Weekly Update for July 3

### ISSUE THREAD

**Issue by Gioyik** [nodejs/evangelism#106]
It&rsquo;s Friday, Friday... Gotta get down on Friday!

**Comment by ruimarinho** [comment]
Node-inspector adds support for debugging network activity (https://github.com/node-inspector/node-inspector/pull/677).

**Comment by yosuke-furukawa** [comment]
@ruimarinho 

> Node-inspector adds support for debugging network activity (node-inspector/node-inspector#677).

I think the update is newsworthy for some node/io.js developer. 
But if we accept the news, we need to write other libraries updates... 

We need to write news related to node/io.js deeply.

**Comment by yosuke-furukawa** [comment]
io.js v2.3.2 is released.

https://github.com/nodejs/io.js/blob/master/CHANGELOG.md#2015-07-01-version-232-rvagg

**Comment by yosuke-furukawa** [comment]
I will talk about "Node.js past, present, future" in YAPC which is the largest conference in Japan Programming Community. http://yapcasia.org/2015/talk/show/82e93a96-f60e-11e4-907e-8ab37d574c3a

**Comment by yosuke-furukawa** [comment]
Security issue is found in v8 https://github.com/nodejs/evangelism/issues/110

**Comment by diagramatics** [comment]
I took the spare time I have and made a weekly update for this one. I can make a PR if it's okay.

**Comment by Gioyik** [comment]
Sure, go ahead

**Comment by diagramatics** [comment]
#112. Hopefully it's up to standards.

**Comment by yosuke-furukawa** [comment]
Published. Thanks !! https://medium.com/node-js-javascript/io-js-week-of-july-3rd-5cfa61a80cbb
