### ISSUE TITLE
Node.js Evangelism Meeting - July 1

### ISSUE THREAD

**Issue by Gioyik** [nodejs/evangelism#108]
*_Meeting time: 3:00 PM Wednesday, Coordinated Universal Time (UTC) *_
- San Francisco: 8:00 AM Wednesday, Pacific Time (PT) 
- Amsterdam: 5:00 PM Wednesday, in Amsterdam, Netherlands
- Moscow: 6:00 PM Wednesday, in Moscow, Russia
- Sydney: 1:00 AM Thursday, in Sydney NSW, Australia

Or in your local time:
- [3:00 PM UTC to local](https://www.google.com/search?q=PST+to+UTC&ie=utf-8&oe=utf-8#q=3pm+utc+to+local)

Conference link: [http://www.uberconference.com/mikeal](http://www.uberconference.com/mikeal)

**Document with notes from the meeting:** _doc to move to io.js/docs after meeting_
- **Google Doc:** https://docs.google.com/document/d/1TwVRcE58HWsD81XUkoyTTBpyqHTiSk591QdBhHD1SHs/edit?usp=sharing

**Invited:**
Everyone is welcome to join the meeting

_People who confirmed assistance:_ @Gioyik @mikeal @yosuke-furukawa @tonypujals @rosskukulinski @julianduque @bnb

**Agenda so far:**
- Update Wikipedia page (#102)
- Node.js Foundation and Evangelism Group (#100)
- Social Media Management (#29, #91)
- New process for WU (#93, #95)
- Localization for WU. State of Localization groups (website?)

**Comment by bnb** [comment]
I can come. I don't understand the TO-DEFINE system though - do you just want a list of translations from UTC, or for us to propose times?

**Comment by rosskukulinski** [comment]
Looks like this Wednesday, 8am PST according to the [Doodle poll](http://doodle.com/ctrss6uf2dx9a28n)

**Comment by bnb** [comment]
Updated OP with correct times. If doing that is stepping on anyone's toes, apologies - just want to make sure plans are set as soon as possible to allow everyone a chance to participate.

**Comment by mikeal** [comment]
If this is happening tomorrow we need to commit to the time right now so I can get this on my calendar.

**Comment by mikeal** [comment]
Also, do I need to setup an uberconference for this?

**Comment by bnb** [comment]
@mikeal I'd say yes on both counts. If people actually show up, we'll be golden - if not so many (< 3) show up, we can decide where to go from there.

**Comment by Gioyik** [comment]
Seems this will be tomorrow. So, we will use Uberconference or Hangouts?

**Comment by mikeal** [comment]
http://www.uberconference.com/mikeal

**Comment by rosskukulinski** [comment]
thanks @mikeal. Updating the issue with the link

**Comment by bnb** [comment]
@nodejs/evangelism Meeting in 15 minutes. See you there!

**Comment by mikeal** [comment]
Ross and I are on, is anyone else going to make it?

**Comment by Gioyik** [comment]
Are you still on the meeting?

**Comment by rosskukulinski** [comment]
@Gioyik we waited for 15 minutes, didn't have a quorum, so we called it.  We'll have to re-schedule.
