### ISSUE TITLE
Evangelism: Weekly Update for July 4—10, 2015

### ISSUE THREAD

**Issue by Gioyik** [nodejs/evangelism#109]
It&rsquo;s Friday, Friday... Gotta get down on Friday!

**Comment by yosuke-furukawa** [comment]
OpenSSL has a high severity security issue. https://mta.openssl.org/pipermail/openssl-announce/2015-July/000037.html 

When OpenSSL patch is released, we will release new patch version. http://twitter.com/rvagg/status/618755098030686209

**Comment by yosuke-furukawa** [comment]
The Node.js LTS WG has updated it's proposed LTS plan. And the WG needs feedback from users. https://github.com/nodejs/LTS/blob/master/README.md#example

**Comment by yosuke-furukawa** [comment]
io.js v2.3.4 and v1.8.4 are out.
https://github.com/nodejs/io.js/pull/2146 (1.8.4)
https://github.com/nodejs/io.js/pull/2115 (2.3.4)

**Comment by yosuke-furukawa** [comment]
ReactNative required io.js as their platform 
https://github.com/facebook/react-native/blob/master/.travis.yml#L24
