### ISSUE TITLE
Ratify Reconciliation Proposal - Evanelism WG

### ISSUE THREAD

**Issue by bnb** [nodejs/evangelism#11]
As called upon by @mikeal in iojs/io.js#978, the members of @iojs/evangelism need to ratify the Reconciliation Proposal proposed there. Right now, we only have 4 official Evangelism WG members. We should follow the consensus seeking model that the io.js community has adopted, so I'd like to ask that we all put our approve/decline vote in. Outcome:
- [x] @mikeal 
- [x] @rosskukulinski 
- [x] @yosuke-furukawa 
- [x] @bnb 
- [x] @julianduque 
- [x] @emilyrose 
- [x] @svincent

**Comment by julianduque** [comment]
I'm +1 to the proposal as is

**Comment by yosuke-furukawa** [comment]
In my opinion, +1 on this.
I am translating on this `Reconciliation Proposal` to Japanese, every Japanese noder needs to know the goal. we are now discussing.

**Comment by bnb** [comment]
Added @julianduque, @emilyrose, and @svincent.

**Comment by bnb** [comment]
@yosuke-furukawa I think it's super important that the message gets distributed to everybody using io.js. Is there a big community of Japanese speaking io.js-ers?

**Comment by rosskukulinski** [comment]
Finally getting caught up on github/iojs after a product launch.  +1 from me (gosh it took a while to read all the comments)

**Comment by yosuke-furukawa** [comment]
@bnb Yes I have a Japanese Node/io.js Community (Actually I am a leader of Japan Node/io.js User Group), it has 400-500 people. BUT, most developer still uses Node.js currently, some geeks use io.js actively. I think this is super important message to every noders and ionians. I should translate it and spread to Japanese Community.

**Comment by affinity-matrix** [comment]
After today's discussion and the subsequent clarification I received, I'm comfortable with the proposal. :+1:

**Comment by rosskukulinski** [comment]
based on consensus model, it looks like we have approved this measure.  I'll wait to see if @svincent has a chance to review the proposal and give feedback before updating iojs/io.js#978.

**Comment by dotproto** [comment]
I'll read through everything tonight and give my up/down. Apologies for the delay.

**Comment by bnb** [comment]
@svincent No worries.

**Comment by dotproto** [comment]
I've [added some feedback](https://github.com/iojs/io.js/issues/978#issuecomment-76897639) to the main reconciliation issue, but I don't have any serious reservations with the proposal as it stands.

+1

**Comment by dotproto** [comment]
Closing as all current WG members have given a +1.
