### ISSUE TITLE
First meeting for Post Mortem Diagnostics workgroup

### ISSUE THREAD

**Issue by hhellyer** [nodejs/evangelism#113]
[nodejs/post-mortem#1](https://github.com/nodejs/post-mortem/issues/1)

We've setup the repository for the project with the basics. Would it be possible to publicise the working group? We'll hold a poll for when to schedule the first meeting once we have some interested parties.

**Comment by bnb** [comment]
Made a tweet about it - https://twitter.com/official_iojs/status/618174601995120640. If you would like a blog post, someone would probably be willing to help (I will, if needed).

**Comment by bmeck** [comment]
@hhellyeribm I would be interested.

**Comment by danielkhan** [comment]
Count me in.
I could sponsor a GotoMeeting for up to 25 attendees if needed.

**Comment by seabaylea** [comment]
Great! I've added you as interested group members
