### ISSUE TITLE
Evangelism: Weekly Update for July 25—31

### ISSUE THREAD

**Issue by Gioyik** [nodejs/evangelism#122]
It&rsquo;s Friday, Friday... Gotta get down on Friday!

**Comment by danielkhan** [comment]
If you still publish things like that: I've written a blog post about NODE_ENV in express: http://apmblog.dynatrace.com/2015/07/22/the-drastic-effects-of-omitting-node_env-in-your-express-js-applications/

**Comment by diagramatics** [comment]
I wonder if we should put a section on the update asking people to suggest community updates too.

**Comment by diagramatics** [comment]
v2.5.0 was out. I can write the update for this one if necessary.

**Comment by yosuke-furukawa** [comment]
@diagramatics yes please!!!

**Comment by diagramatics** [comment]
Is there any other community updates for this week, giving that what Daniel posted is already included on the last update?

**Comment by diagramatics** [comment]
Meanwhile I had to steal two articles from Node Weekly.
- [If This Then Node.js — Extending IFTTT With Webtask.io](https://auth0.com/blog/2015/07/28/if-this-then-node-dot-js-extending-ifttt-with-webtask-dot-io/?utm_source=nodeweekly&utm_medium=email).
- [Authoring Node Modules](http://h3manth.com/new/blog/2015/authoring-node-modules/?utm_source=nodeweekly&utm_medium=email).

**Comment by yosuke-furukawa** [comment]
Yes. I just added Daniel blog post in 24th weekly updates.

**Comment by yosuke-furukawa** [comment]
We need V8 maintainer for LTS. https://github.com/nodejs/LTS/issues/28
