### ISSUE TITLE
Evangelism: Weekly Update for August 1—7

### ISSUE THREAD

**Issue by Gioyik** [nodejs/evangelism#128]
It&rsquo;s Friday, Friday... Gotta get down on Friday!

**Comment by diagramatics** [comment]
v3.0.0 was out. We might need a longer post describing about this.

**Comment by yosuke-furukawa** [comment]
Yes, I am working on this. 
https://github.com/yosuke-furukawa/iojs-new-features/pull/1

**Comment by diagramatics** [comment]
[Issue 96 of Node Weekly](http://nodeweekly.com/issues/96). We can either link to Node Weekly or pick articles from it, and I'm not experienced with Node enough to see which ones are more closely tied towards the development of Node.js itself.

**Comment by yosuke-furukawa** [comment]
@diagramatics I didn't know the site. I would like to use the following posts to the community updates.

http://h3manth.com/new/blog/2015/authoring-node-modules/?utm_source=nodeweekly&utm_medium=email

http://blog.webkid.io/how-to-create-a-rest-api-with-hapi/?utm_source=nodeweekly&utm_medium=email

https://blog.risingstack.com/start-using-graphql-with-graffiti/?utm_source=nodeweekly&utm_medium=email

http://www.infoworld.com/article/2953719/javascript/samsung-banks-on-javascript-node-js-for-iot.html?utm_source=nodeweekly&utm_medium=email

from http://nodeweekly.com/issues/97

**Comment by rvagg** [comment]
probably best to leave off the google analytics query strings for nodeweekly

**Comment by diagramatics** [comment]
@rvagg I discussed about using our own even.  #124. 

I'll see if I can write this one in the next 6 hours.

**Comment by diagramatics** [comment]
@yosuke-furukawa Do you want me to reference the README.md file of your iojs-new-features on the article, or to summarize instead?

Also, the first link (Authoring Node Modules) was in the previous update.
