### ISSUE TITLE
Node Foundation/iojs SoundCloud accounts are ambiguously named

### ISSUE THREAD

**Issue by techjeffharris** [nodejs/evangelism#129]
Both https://soundcloud.com/node-foundation and https://soundcloud.com/iojs use the "Node Foundation" username which is a bit ambiguous.  

I imagine that the SoundCloud/node-foundation is for converged meetings and SoundCloud/iojs will be no longer receive updates once the convergence is complete. Is this a reasonable assumption? 

For sake of clarity, the iojs account should be renamed back to "iojs" and the description for each respective account should indicate the above and provide links/direct consumers to the other.

**Comment by techjeffharris** [comment]
Also, see https://github.com/nodejs/node/issues/68

**Comment by mikeal** [comment]
> I imagine that the SoundCloud/node-foundation is for converged meetings and SoundCloud/iojs will be no longer receive updates once the convergence is complete. Is this a reasonable assumption? 

The governance has already converged, the weekly meeting of the TSC covers current node.js and io.js releases. The node-foundation account is where those TSC meetings are being published.

The iojs account pre-dates that account and is an audio-only version of the meetings that are posted to the iojs youtube channel.

We're in-between tooling. Groups less than 10 people are still using hangouts + youtube while groups over 10 are using Uberconference with recording and publishing to node-foundation.

**Comment by techjeffharris** [comment]
> The governance has already converged, the weekly meeting of the TSC covers current node.js and io.js releases. The node-foundation account is where those TSC meetings are being published.

Indeed :-D 

> The iojs account pre-dates that account and is an audio-only version of the meetings that are posted to the iojs youtube channel.

Nonetheless, it would be nice if each account's respective descriptions noted their status (archive/current) and provided links to the other, no?

P.S. sorry for being nit-picky O:-)

**Comment by techjeffharris** [comment]
Also, the converged repository is focused on the converged release; however, https://github.com/nodejs/node/issues/68 was closed despite the node-foundation soundcloud account not being up-to-date.  Is nodejs/node the correct place for such an issue?  It would be valuable to prevent this from falling through the cracks..

**Comment by techjeffharris** [comment]
Also I'm happy to volunteer, though it seems a higher level of trust than I have earned may be required.

**Comment by bnb** [comment]
@svincent Is the one in control of soundcloud/iojs, IIRC. He can probably change the name.

**Comment by dotproto** [comment]
Thanks for the ping, @bnb. Yep, I (poorly) maintain the iojs account. I'm literally on the road right now (friend is driving), so I'll take a few min to read through this thread...

**Comment by dotproto** [comment]
So! For a bit of background, I started be iojs account because I love podcasts and wanted to hear the meetings when I was on the road. I wasn't aware there was a node-foundation account. Back when the io.js TC voted to merge with Node.js I renamed the iojs account's display name from  "io.js Audio" to "Node Foundation". I considered changing the username as well, but I couldn't think of one I liked that wasn't take.

In any case, this is the first I've heard of the node-foundation account. If there's an official account that will be maintained going forward, I don't mind retiring the account I created.

**Comment by mikeal** [comment]
Is there a way to merge over the old io.js audio files? If we just pull them down and add them they'll have the wrong release date.

**Comment by dotproto** [comment]
Unfortunately it doesn't look like we can do that.
- http://help.soundcloud.com/customer/portal/articles/526334-can-i-merge-accounts-
- https://www.soundcloudcommunity.com/soundcloud/topics/hi-i-have-two-accounts-i-just-want-one-and-to-combine-them-somehow

**Comment by bnb** [comment]
@svincent Would downloading them manually (you should be able to control this as the account owner; you can also use a service to do it) and uploading them manually work? I'd be willing to spend the time on doing that, if needed.

**Comment by mikeal** [comment]
@bnb the problem with doing that is that the publish dates will be the date you upload them which will really mess up the podcast feed :(

**Comment by dotproto** [comment]
We could always upload them but exclude them from the podcast feed. Certainly not ideal, but at least they'd be centralized and it wouldn't mess with the order of new episodes coming out.

**Comment by techjeffharris** [comment]
Is there a way to set the default order sounds by name? If so, maybe renaming them such that the names have the dates pretended and are therefore effectively ordered by date? I'm not sure whether or not they can be renamed, however..

**Comment by MylesBorins** [comment]
Sound cloud will always default to the date. 

if you have a pro account you can make a highlighted section at the top of your feed, you can control the order of that feed

**Comment by dotproto** [comment]
Unfortunately that list at the top of your account doesn't have any impact on your podcast feed. Podcasts automatically add tracks in the order they're published on Soundcloud.

@mikeal, I think it would be best to either re-publish the tracks but leave them out of the podcast feed, or leave them as completely separate accounts that link between each other. Personally I favor the re-publish route as I believe tracks will become hidden if my subscription lapses, and there's not much incentive to keep my subscription alive if the official account is publishing meetings.

**Comment by mikeal** [comment]
Probably best to leave them provided you aren't stuck with a never-ending bill from soundcloud to keep them up :)

**Comment by dotproto** [comment]
I think that may be the case. Guess we'll see :wink:

**Comment by dotproto** [comment]
@mikeal Could we get the Node Foundation account to publish a Podcast feed on Soundcloud? It [looks like there's an RSS file](http://feeds.soundcloud.com/users/soundcloud:users:153451281/sounds.rss) for the account, but the feed doesn't have any files. I'd very much like to subscribe to a podcast feed rather than having to rely on the Soundcloud mobile app/site. 

Also, I'd be happy to help with the SoundCloud stuff if you/whoever needs a hand 😄
