### ISSUE TITLE
Add member to Evangelism WG

### ISSUE THREAD

**Issue by bnb** [nodejs/evangelism#13]
I'd like to propose that @svincent be added as a member to the Evangelism WG. He's contributed high-quality work and discussion, and is motivated to continue working under the WG. 

He asked me if I could review the contents of #6 in a bit more detail than we could over text on GitHub. I accepted, and we spent 3 hours going over, arranging and re-arranging. 

The document ended up more solid than I could have hoped for, and we came up with some excellent ideas for it and other issues to propose to the WG (which I'm going write up and post ASAP) while we were working. He contributed a ton of really good ideas and had a ton of well thought-out input. The WG would definitely benefit from having him as a member.

**Comment by mikeal** [comment]
+1

**Comment by rosskukulinski** [comment]
+1

**Comment by dotproto** [comment]
Aw, thanks all. Regardless of how the vote shakes out I hope to stay involved and help however I can.

**Comment by bnb** [comment]
@yosuke-furukawa Can we get your vote?

**Comment by julianduque** [comment]
+1 from me

**Comment by bnb** [comment]
An invite has been sent. Welcome, @svincent.

**Comment by yosuke-furukawa** [comment]
+1 form me!

**Comment by dotproto** [comment]
Thanks all! Happy to be part of the team :grin:

**Comment by rosskukulinski** [comment]
@svincent has been added to the Readme
