### ISSUE TITLE
Weekly Updates on new nodejs.org Blog

### ISSUE THREAD

**Issue by mikeal** [nodejs/evangelism#130]
Hey everybody :)

I just did this https://github.com/nodejs/new.nodejs.org/commit/e72e537785d6952574c9a30d77bcbda7fdfee87d

Basically, I ported all of the weekly updates we've been keeping as markdown files in this repository to the blog for new.nodejs.org.

From now on rather than sending a PR to this repo we should send one there :)

-Mikeal

**Comment by Gioyik** [comment]
@mikeal so, should we still manage the issues to collect links for every weekly update on new.nodejs.org repo?

**Comment by mikeal** [comment]
@Gioyik the issues have been working quite well to collect links from the community. You've done a great job putting these together and I don't think we should interrupt anything that is working. The only thing I think that we should do is change where we send the PR for the final markdown post so that it shows up in the new website.

**Comment by bnb** [comment]
Seems like this has worked itself out. Closing.
