### ISSUE TITLE
Evangelism: Weekly Update for August 8—14

### ISSUE THREAD

**Issue by Gioyik** [nodejs/evangelism#133]
It&rsquo;s Friday, Friday... Gotta get down on Friday!

**Comment by diagramatics** [comment]
Dropping in the link to issue 98 of [Node Weekly](http://nodeweekly.com/issues/98).

**Comment by yosuke-furukawa** [comment]
Rod Vagg proposed to move repo from nodejs/io.js to nodejs/node https://github.com/nodejs/io.js/issues/2327

**Comment by snostorm** [comment]
The https://github.com/nodejs/summit happened last Thursday/Friday although the notes haven't been published anywhere too helpful yet for consumption.

For your purposes, incase somebody wants to summarize the event at a high level, the notes are linked from https://github.com/nodejs/summit/issues/11 -- I'm sure we could also get a few attendees to either help write up a brief summary or could answer a few questions on a call to that same purpose.

**Comment by diagramatics** [comment]
@snostorm Is it too much to ask if the summary is going to be available by Thursday at the latest? I really want to publish the weekly updates on time so I might write this weekly update one or two days before Friday.

In addition, if anyone could cherry pick the articles from the recent Node Weekly newsletter that'll be great.

**Comment by snostorm** [comment]
Nobody is charged with it and I'm not sure if I will have time to write anything long, so I don't want to volunteer myself for the moment. I guess at minimum we can note that it happened, try to get some high level stats (# attended, from where in the world, etc.) and list the general topics discussed by the group.

**Comment by snostorm** [comment]
Tracking the request at nodejs/summit#13

**Comment by Trott** [comment]
I'm not sure what criteria exist for determining whether an event warrants listing or not, but it seems like maybe Nodevember would be something to add to the Upcoming Events section. http://nodevember.org/

**Comment by srl295** [comment]
Intl is about to have its first meeting - https://github.com/nodejs/Intl/issues/8

**Comment by yosuke-furukawa** [comment]
io.js repository is renamed nodejs/node https://github.com/nodejs/node

**Comment by diagramatics** [comment]
Selecting three stuffs from Node Weekly:
- [Get Node.js Command Line Arguments with yargs](http://davidwalsh.name/nodejs-arguments-yargs)
- [Building a GraphQL Server with Node.js and SQL](https://www.reindex.io/blog/building-a-graphql-server-with-node-js-and-sql/)
- [https://github.com/kabab/qr-cairo](https://github.com/kabab/qr-cairo)

**Comment by diagramatics** [comment]
#137 is up!
