### ISSUE TITLE
Information / brainstorm / input session w/ all of the content and “locale” groups

### ISSUE THREAD

**Issue by snostorm** [nodejs/evangelism#134]
Crosslinking this issue here: nodejs/Intl#9

cc @nodejs/evangelism

**Comment by yosuke-furukawa** [comment]
@snostorm Thank you for linking!!

**Comment by bnb** [comment]
@snostorm Is there still something beneficial that we can get from this issue still being open?

**Comment by bnb** [comment]
Closing as there has been no development. Don't hesitate to re-open if this can be useful again.
