### ISSUE TITLE
Working Together - Introducing nodejs/collaboration

### ISSUE THREAD

**Issue by snostorm** [nodejs/evangelism#135]
As a heads up for those of you who weren't able to make the summit, https://github.com/nodejs/collaboration has been spun up as a new team to help share resources and best practices among groups, as well as trying to help everyone better work together.

Later we'll be more aggressively working to get representation from all WGs but for now I was hoping to get a few evangelism members in early. Because this group by its very nature has to stay in tune with  what the other WG are doing (for weekly updates, tweets, etc.) collaboration is a key factor for your team's success.

Another aspect of this early invite is to try and develop better ways to have evangelism, website, documentation and the 30+ i18n groups work together. We're hoping on some occasional meetings (say, a few times a year) across many time zones and to generally maintain open channels in between. For that see #134 or nodejs/Intl#9.

So if you are interested, we'd love to get some early input and also longterm have some ongoing representation from your team as members inside the new group.

**Comment by yosuke-furukawa** [comment]
@snostorm Yes, I would like to collaborate together !! if anyone does not stand as a representation, I would like to try to get involved to the WG.

**Comment by snostorm** [comment]
@yosuke-furukawa there's room for multiple people to join the Collaboration Team from the same WG. If you're interested, join via https://github.com/orgs/nodejs/teams/collaboration :)

**Comment by bnb** [comment]
@Trott Do you know the status on this? Looks like there's been 0 activity in Collaboration.

**Comment by Trott** [comment]
I don't have any special knowledge about it, but as far as I know, any Collaboration WG or similar initiative is inactive. I'll go ahead and close this. If that's a mistake and this is really a going concern, some can comment and/or re-open.
