### ISSUE TITLE
Node.js 4.0 International Launch Party!

### ISSUE THREAD

**Issue by julianduque** [nodejs/evangelism#136]
We should organize a launch party, get together or organize a meetup to celebrate this important milestone in the life of the Node.js project

**Comment by Gioyik** [comment]
What is the date?

**Comment by yosuke-furukawa** [comment]
+1 !!  but the date is unclear....

**Comment by subfuzion** [comment]
:+1:

**Comment by yosuke-furukawa** [comment]
In September???
https://medium.com/node-js-javascript/4-0-is-the-new-1-0-386597a3436d
