### ISSUE TITLE
Evangelism member 

### ISSUE THREAD

**Issue by yosuke-furukawa** [nodejs/evangelism#147]
@nodejs/evangelism 

I got a message from @JungMinu . 

![image](https://cloud.githubusercontent.com/assets/555645/9837260/63075fda-5a74-11e5-80c0-a2f233623dd2.png)

She really want to be a member of our WG.
I agree that she will be an evangelist. 

But I would like to know any other member opinions. if anyone disagree with that, we should discuss it.

**Comment by JungMinu** [comment]
Hello :bowtie: 
I really want to be a member of evangelism.
I have worked as a `contributor` of `nodejs/node`,`nodejs/new.nodejs.org` and 
a `collaborator` of io-js korea .
I will do my best as  an evangelist :)
Thanks in advance!

**Comment by julianduque** [comment]
It's a :+1: x :100:  from me

**Comment by JungMinu** [comment]
@julianduque Thanks :smile:

**Comment by rosskukulinski** [comment]
Sounds to me that @JungMinu is already an active contributor to the node ecosystem. +1

**Comment by JungMinu** [comment]
@rosskukulinski Thanks :smile:

**Comment by yosuke-furukawa** [comment]
Thanks, everyone. @JungMinu you are the member of evangelism WG.

**Comment by yosuke-furukawa** [comment]
I need your twitter handle name. 
We are listed in README.md.
I will write your name/github account/twitter handle in README.md if you tell me your twitter handle.

**Comment by JungMinu** [comment]
@yosuke-furukawa Thank you :smile: 
My twitter handle is https://twitter.com/jmwsoft
I will do my best as an evangelist :)
Also, would you invite me to the organization(https://github.com/nodejs) as a member?
Thanks again!

**Comment by JungMinu** [comment]
Thanks, I will make every effort to be a good Node.js evangelist
