### ISSUE TITLE
Goals of this WG / services it provides

### ISSUE THREAD

**Issue by danielkhan** [nodejs/evangelism#148]
I'm watching this group for some while and I'm happy to be able to spread my blog posts through the weekly updates. Still I don't completely know what they goals of this WG are and which service I could expect from it and how I could contribute in a meaningful way.
I am somehow missing graphical assets, messages that should be shared, meetup and conference requests, etc.
I would also love to see some initiative on providing peer reviews for blog posts and conference decks.
I'm currently also struggling with some rather deep technical questions I came across preparing my current deck. Is this the right place to ask?

**Comment by yosuke-furukawa** [comment]
> I'm currently also struggling with some rather deep technical questions I came across preparing my current deck. Is this the right place to ask?

Sure. We can review your blog/decks and discuss the technical questions.

The following sentences are my humble idea of this evangelism WG's goal.
1. We should be state-of-the-art end users of Node.js
2. We should try to use new features and feedback to Node.js core.
3. We should write blog posts and evangelize Node.js new features/use-cases.
4. We should extract community opinions from conference and feedback to Node.js core.

**Comment by danielkhan** [comment]
Thank you - I've posted my question in another issue.
