### ISSUE TITLE
Technical Question: Threads and Node.js

### ISSUE THREAD

**Issue by danielkhan** [nodejs/evangelism#149]
Often discussed and still unclear I may want to explain thread usage in Node.js in my next talk that should provide a deep dive into Node.js for beginners (to Node but not to CS).

If I start Node.js 0.10 with `UV_THREADPOOL_SIZE=1` I get this:

```
node(5157)-+-{node}(5158)
            `-{node}(5162)
```

5162 is the thread of my single thread threadpool.
5158 is libuv itself.

Now the question: Where does my userland code run (e.g. the `require` statements on the beginning)?
Is it on 5157 or 5158 (within libuv's main thread)?

Next question:
When I tried the same with 0.12 and 4.0.0 I see that threadpool handling works differently between releases.

0.10: UV_THREADPOOL_SIZE + 1 + 1
0.12: UV_THREADPOOL_SIZE + 2 + 1
4.0.0: UV_THREADPOOL_SIZE + 4 + 1

The + 1 is always the main process (like 5157 before).
What's the reason? What changed between those releases?

**Comment by yosuke-furukawa** [comment]
Hmm, I don't know libuv details. I need more help from @bnoordhuis / @rvagg ...

According to [libuv docs](http://docs.libuv.org/en/v1.x/threadpool.html#threadpool), all filesystem operations are run on the threadpool. if your userland module uses `fs` or `require` (include `net`?), the threadpool (5162) is used.

The following sentences are my hypothesis.

I guess JavaScript code is run on V8 side, so node main thread (5157) is used. But The case of async code like `fs.readFile` / `child_process.exec` uses 5158 and 5162.

so your question: `Where does my userland code run?`
my answer: `JavaScript execution => 5162, async code without fs operation => 5158,  async code with fs operation => 5162`

> Next question: When I tried the same with 0.12 and 4.0.0 I see that threadpool handling works differently between releases.

I have no idea, but I take a glance libuv code, I don't find changes.
https://github.com/libuv/libuv/blob/da42780223bae35d38b6d4d920caa1563e884470/src/threadpool.c#L172-L174

**Comment by danielkhan** [comment]
Thank you, Yosuke. This is also my thesis.

Would be great if someone from core could confirm that.

Maybe it would be also possible to explain the whole process / thread handling with a simple example like

``` javascript
var fs = require('fs');

fs.readfile('/foo/bar', function(err, data) {
    console.log(data);
});
```

I understand the event loop mechanism but the details aren't easy to grasp for me. I always hit some roadblocks like 'where does console.log(..) from the example above run then?'.

**Comment by bnoordhuis** [comment]
> filesystem operations are run on the threadpool

All _asynchronous_ file operations run inside the threadpool, i.e., file operations that take a callback.  `require()` is synchronous and runs on the main thread.  That includes the `vm.runInThisContext()` call that evaluates the require'd code.

> When I tried the same with 0.12 and 4.0.0 I see that threadpool handling works differently between releases.

V8 started spawning threads of its own over time, for concurrent garbage collection and dynamic recompilation.

**Comment by danielkhan** [comment]
Thank you @bnoordhuis. Where does userland code inside a callback run then? Will this be passed back to the main thread then? e.g. the console.log().

**Comment by bnoordhuis** [comment]
JS code always runs on the main thread.  In your `fs.readFile()` example, a C++ work request is constructed and handed off to the thread pool.  When it finishes, the main thread gets a ping with the result and makes the callback.

**Comment by danielkhan** [comment]
o.k. and just to be sure the main thread from my example would be (5157), right?

**Comment by bnoordhuis** [comment]
Yes.

**Comment by danielkhan** [comment]
Thank you @bnoordhuis and @yosuke-furukawa - finally it all makes sense.
I'll incorporate this into my slides.
