### ISSUE TITLE
Evangelism: Weekly Update for next week :)

### ISSUE THREAD

**Issue by JungMinu** [nodejs/evangelism#156]
Let's write down for next week :gift:

**Comment by yosuke-furukawa** [comment]
@JungMinu Yes! Please!!

**Comment by JungMinu** [comment]
@yosuke-furukawa Thanks :) Let's work together :smiley:

**Comment by rvagg** [comment]
- NodeSource announced N|Solid, "a platform built on Node.js and designed specifically for the unique needs of the enterprise" with a focus on insight, control and protection: https://nodesource.com/blog/nsolid-enterprise-node-finally

**Comment by JungMinu** [comment]
`Node v4.1.1 (Stable)`
https://nodejs.org/en/blog/release/v4.1.1/

**Comment by yosuke-furukawa** [comment]
NodeUp nintyone An Onboarding Show
http://nodeup.com/ninetyone

**Comment by yosuke-furukawa** [comment]
@JungMinu If you have time, you would try to create this week update. We can review your PR. If you couldn't, I will create.

**Comment by JungMinu** [comment]
@yosuke-furukawa When is the deadline for writing?

**Comment by yosuke-furukawa** [comment]
@JungMinu tomorrow! I am sorry for the close deadline .
But if you don't have time, I will update this.

**Comment by JungMinu** [comment]
@yosuke-furukawa Sorry, I will try next week :smile:

**Comment by julianduque** [comment]
- C++ Addons for Node.js v4 - https://nodesource.com/blog/cpp-addons-for-nodejs-v4
