### ISSUE TITLE
Help repo

### ISSUE THREAD

**Issue by mikeal** [nodejs/evangelism#158]
So, the foundation has access to the nodejs twitter account now and there's quite a lot of people who are in need of basic technical support and mentioning @nodejs.

It seems like a good idea to create some kind of "help" or "support" repo that the evangelism team moderates which we can point these people at on twitter when they have technical issues.

Thoughts?

**Comment by JungMinu** [comment]
LGTM :smile: +1
I'm very glad to participate in :smiley:

**Comment by subfuzion** [comment]
+1

**Comment by danielkhan** [comment]
Good idea. I'd love to help.

**Comment by yosuke-furukawa** [comment]
+100

**Comment by julianduque** [comment]
Love to help too!

**Comment by mikeal** [comment]
Created, https://github.com/nodejs/help

Would love someone to contribute an awesome README :)

The evangelism team is set as the admin of the repo.

**Comment by SomeoneWeird** [comment]
This is great. We should talk about when/if we want to triage/redirect people/issues from `nodeschool/discussions` seeing as currently that is where 95% of people who need help are directed to (via nodeschool workshops, word of mouth etc).

I'm also very interested in joining the help WG, is there a process or is it contributions etc?
