### ISSUE TITLE
Evangelism: Weekly Update Mar 6th

### ISSUE THREAD

**Issue by bnb** [nodejs/evangelism#16]
# io.js 1.5.0 Release

On Friday, March 6th, [@rvagg](https://github.com/rvagg) released io.js [**v1.5.0**](https://iojs.org/dist/latest/).  The complete change log can be found [on GitHub](https://github.com/iojs/io.js/blob/v1.x/CHANGELOG.md).
### Notable changes
- **buffer**: New `Buffer#indexOf()` method, modelled off [`Array#indexOf()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf). Accepts a String, Buffer or a Number. Strings are interpreted as UTF8. (Trevor Norris) [#561](https://github.com/iojs/io.js/pull/561)
- **fs**: `options` object properties in `'fs'` methods no longer perform a `hasOwnProperty()` check, thereby allowing options objects to have prototype properties that apply. (Jonathan Ong) [#635](https://github.com/iojs/io.js/pull/635)
- **tls**: A likely TLS memory leak was reported by PayPal. Some of the recent changes in **stream_wrap** appear to be to blame. The initial fix is in [#1078](https://github.com/iojs/io.js/pull/1078), you can track the progress toward closing the leak at [#1075](https://github.com/iojs/io.js/issues/1075) (Fedor Indutny).
- **npm**: Upgrade npm to 2.7.0. See [npm CHANGELOG.md](https://github.com/npm/npm/blob/master/CHANGELOG.md#v270-2015-02-26) for details including why this is a semver-minor when it could have been semver-major. Summary:
  - [`145af65`](https://github.com/npm/npm/commit/145af6587f45de135cc876be2027ed818ed4ca6a)
    [#4887](https://github.com/npm/npm/issues/4887) Replace calls to the
    `node-gyp` script bundled with npm by passing the
    `--node-gyp=/path/to/node-gyp` option to npm. Swap in `pangyp` or a version
    of `node-gyp` modified to work better with io.js without having to touch
    npm's code!  ([@ackalker](https://github.com/ackalker))
  - [`2f6a1df`](https://github.com/npm/npm/commit/2f6a1df3e1e3e0a3bc4abb69e40f59a64204e7aa)
    [#1999](https://github.com/npm/npm/issues/1999) Only run `stop` and `start`
    scripts (plus their pre- and post- scripts) when there's no `restart` script
    defined. This makes it easier to support graceful restarts of services
    managed by npm.  ([@watilde](https://github.com/watilde) /
    [@scien](https://github.com/scien))
  - [`448efd0`](https://github.com/npm/npm/commit/448efd0eaa6f97af0889bf47efc543a1ea2f8d7e)
    [#2853](https://github.com/npm/npm/issues/2853) Add support for `--dev` and
    `--prod` to `npm ls`, so that you can list only the trees of production or
    development dependencies, as desired.
    ([@watilde](https://github.com/watilde))
  - [`a0a8777`](https://github.com/npm/npm/commit/a0a87777af8bee180e4e9321699f050c29ed5ac4)
    [#7463](https://github.com/npm/npm/issues/7463) Split the list printed by
    `npm run-script` into lifecycle scripts and scripts directly invoked via `npm
    run-script`. ([@watilde](https://github.com/watilde))
  - [`a5edc17`](https://github.com/npm/npm/commit/a5edc17d5ef1435b468a445156a4a109df80f92b)
    [#6749](https://github.com/npm/npm/issues/6749) `init-package-json@1.3.1`:
    Support for passing scopes to `npm init` so packages are initialized as part
    of that scope / organization / team. ([@watilde](https://github.com/watilde))
- **TC**: Colin Ihrig (@cjihrig) resigned from the TC due to his desire to do more code and fewer meetings.
### Known issues
- Possible TLS-related memory leak, details at [#1075](https://github.com/iojs/io.js/issues/1075).
- Windows still reports some minor test failures and we are continuing to address all of these as a priority. See [#1005](https://github.com/iojs/io.js/issues/1005).
- Surrogate pair in REPL can freeze terminal [#690](https://github.com/iojs/io.js/issues/690)
- Not possible to build io.js as a static library [#686](https://github.com/iojs/io.js/issues/686)
- `process.send()` is not synchronous as the docs suggest, a regression introduced in 1.0.2, see [#760](https://github.com/iojs/io.js/issues/760) and fix in [#774](https://github.com/iojs/io.js/issues/774)
# Community Updates
- You can relax knowing that io.js and latest node.js [**are not affected**]((https://strongloop.com/strongblog/are-node-and-io-js-affected-by-the-freak-attack-openssl-vulnerability/) by the [FREAK Attack](https://freakattack.com/).  You are running io.js or the latest version of node.js, right?
- Walmart is now sponsoring a build machine for the io.js Jenkins CI system.  The @iojs/build team is working on creating io.js SunOS binaries (like you can get from nodejs.org).  A V8 fix ([iojs/io.js#1079](https://github.com/iojs/io.js/pull/1079)) needs to be landed first before more progress can be made.
- We would also like to thank the following companies for contributing hardware and related technology/support/engineering for io.js builds:
  - **Digital Ocean** (mainly Linux)
  - **Rackspace** (mainly Windows)
  - **Voxer** (OS X and FreeBSD)
  - **NodeSource** (ARMv6 & ARMv7)
  - **Linaro** (ARMv8)
  - **Walmart** (SmartOS / Solaris)
- The io.js community has been hard at work on the internationalization of all of its content.  There are now over 20 active languages published on [iojs.org](http://iojs.org) and i18n community sites.  Additionally, i18n links ([iojs/website#258](https://github.com/iojs/website/pull/258)) have been added to the website footer for easy access.  Are we missing your language?  [Help us add it!](https://github.com/iojs/website/blob/master/TRANSLATION.md)
- Speaking of translations, the [io.js roadmap presentation](http://roadmap.iojs.org/) has been updated to link to other language versions.
- It seems that **PayPal** is running an experiment comparing [Kappa](https://www.npmjs.com/package/kappa)  on io.js vs node.js 0.12 vs node.js v0.10.  The PayPal team identified a likely TLS memory leak. Initial fix is in [#1078](https://github.com/iojs/io.js/pull/1078) and progress towards closing is in [#1075](https://github.com/iojs/io.js/issues/1075)
- [**NodeSource**](http://nodesource.com) is now providing io.js [Linux binary](https://nodesource.com/blog/nodejs-v012-iojs-and-the-nodesource-linux-repositories) packages for Ubuntu/Debian as well as RHEL/Fedora distributions.
- The io.js [Docker build]((https://registry.hub.docker.com/u/library/iojs/) is one of thirteen new [official Docker repositories](http://blog.docker.com/2015/03/thirteen-new-official-repositories-added-in-january-and-february/) added in January and February.
- NodeBots and IoT people should be happy to hear that the just-announced [**Tessel2**](http://blog.technical.io/post/112787427217/tessel-2-new-hardware-for-the-tessel-ecosystem) runs [io.js natively](http://blog.technical.io/post/112888410737/moving-faster-with-io-js).
- [**@maxbeatty**](https://twitter.com/maxbeatty) is working on a new version of the [jsperf.com](http://jsperf.com/) backend, running on io.js and it is entirely [open source](https://github.com/jsperf/jsperf.com).  Contributions are welcome!
- [@eranhammer](https://twitter.com/eranhammer) wrote a blog post called [The Node Version Dilemma](http://hueniverse.com/2015/03/02/the-node-version-dilemma/) which discusses the various node.js / io.js versions and proposes which ones to use and when to use them.
# io.js Support Added
- **[scrypt](https://npmjs.com/scrypt)** now supports io.js. Learn more from this [GitHub issue](https://github.com/barrysteyn/node-scrypt/issues/39)
- **[proxyquire](https://github.com/thlorenz/proxyquire)** v1.3.2 published with support for iojs.

**Comment by rvagg** [comment]
Walmart are sponsoring a build machine for our CI set, we're just in the process of trying it out how well it's going to work but this could lead to "sunos" binaries from io.js like you can get from nodejs.org.

So far we have the following companies contributing hardware (and related means to make this work)
- DigitalOcean (mainly Linux)
- Rackspace (mainly Windows)
- Voxer (OS X and FreeBSD)
- NodeSource (ARMv6 & ARMv7)
- Linaro (ARMv8)
- Walmart (SmartOS / Solaris)

Someone in here should get @geek to update the status of SmartOS before this Weekly Update goes out because it'll have evolved by then.

**Comment by bnb** [comment]
@rvagg Great news! And thanks - I'll make sure we message @geek before this is published.

**Comment by rosskukulinski** [comment]
[proxyquire](https://github.com/thlorenz/proxyquire) v1.3.2 published with support for iojs.  Announcement [here](https://twitter.com/thlorenz/status/572492178829799425)

**Comment by geek** [comment]
We have a jenkins worker running on SmartOS at the moment, but we are running into issues getting v8 to compile: https://code.google.com/p/v8/issues/detail?id=3935

**Comment by bnb** [comment]
The Node Version Delimma - http://hueniverse.com/2015/03/02/the-node-version-dilemma/

**Comment by rvagg** [comment]
jsperf.com backend going io.js https://twitter.com/jsperf/status/572716156357873665

**Comment by yosuke-furukawa** [comment]
io.js and latest node.js are NOT affected by the FREAK Attack openSSL vulnerability. https://strongloop.com/strongblog/are-node-and-io-js-affected-by-the-freak-attack-openssl-vulnerability/

**Comment by tellnes** [comment]
[scrypt](https://npmjs.com/scrypt) do now support io.js, details in https://github.com/barrysteyn/node-scrypt/issues/39

**Comment by bnb** [comment]
Major version bump issue - iojs/io.js - https://github.com/iojs/io.js/issues/1061

**Comment by bnb** [comment]
iojs.org adds localization links to footer for access to available localized versions. https://github.com/iojs/evangelism/issues/31

**Comment by julianduque** [comment]
NodeSource io.js linux distributions: https://nodesource.com/blog/nodejs-v012-iojs-and-the-nodesource-linux-repositories

**Comment by yosuke-furukawa** [comment]
Tessel2 is io.js compatible. https://twitter.com/rwaldron/status/573525951688085504 https://twitter.com/technicalhumans/status/573503873727356929

**Comment by mikeal** [comment]
More on the Tessel 2. It runs io.js on the hardware http://blog.technical.io/post/112787427217/tessel-2-new-hardware-for-the-tessel-ecosystem

**Comment by bnb** [comment]
Just wanted to ask if someone could take over writing this tomorrow, as I'm having a pretty painful dental issue, and will be trying to get into the dentist to get it fixed. Would anybody be able to take it over?

**Comment by rosskukulinski** [comment]
I can step in. I'll ping you in the am for details unless there's a readme
on the process. If not, I'll write one.

Ross

**Comment by snostorm** [comment]
FYI We're up to 20 active languages now published (and linked) on io.js org.

**Comment by mikeal** [comment]
more on tessel http://blog.technical.io/post/112888410737/moving-faster-with-io-js

**Comment by Fishrock123** [comment]
dangit @mikeal beat me to it XD

**Comment by Fishrock123** [comment]
> Someone in here should get @geek to update the status of SmartOS before this Weekly Update goes out because it'll have evolved by then.

ping @geek

**Comment by Fishrock123** [comment]
Also, io.js 1.5.0 should be landing today: https://github.com/iojs/io.js/issues/1060

**Comment by geek** [comment]
https://github.com/iojs/evangelism/issues/16#issuecomment-76827548

Additionally, we have a fix for the issue here: https://github.com/iojs/io.js/pull/1079

**Comment by mikeal** [comment]
@rosskukulinski we can start drafting the language for the weekly update now :)

**Comment by rosskukulinski** [comment]
@mikeal aye, I'll start writing it up

**Comment by rosskukulinski** [comment]
Still working, but here's what I've got so far.  Comments welcome.

---

# io.js 1.5.0 Release

This week version [**1.5.0**]() was released.

## Notable changes

For reference, the complete change log is [here](https://github.com/iojs/io.js/issues/1060)
- [v8] Fix for build on solaris platforms [iojs/io.js#1079](https://github.com/iojs/io.js/pull/1079)

# Community Updates
- io.js and latest node.js NOT affected by FREAK [openSSL vulnerability](https://strongloop.com/strongblog/are-node-and-io-js-affected-by-the-freak-attack-openssl-vulnerability/)
- Build machines for CI:
  - Walmart now sponosring a build machine
    - Could lead to sunos binaries
  - Existing companies contributing hardware:
  - Digitial Ocean (mainly Linux)
  - Rackspace (mainly Windows)
  - Voxer (OS X and FreeBSD)
  - NodeSource (ARMv6 & ARMv7)
  - Linaro (ARMv8)
  - Walmart (SmartOS / Solaris)
- iojs community has been hard at work on internationalization of all of our content.  There are now over 20 active languages published on [iojs.org](http://iojs.org), and i18n links ([iojs/website#258](https://github.com/iojs/website/pull/258)). have been added to the footer for easy access. 
- [**NodeSource**](http://nodesource.com) now providing io.js [Linux Distributions](https://nodesource.com/blog/nodejs-v012-iojs-and-the-nodesource-linux-repositories)
- iojs/io.js Major version bump discussion [iojs/io.js#1061](https://github.com/iojs/io.js/issues/1061)
- [**Tessel2**](http://blog.technical.io/post/112787427217/tessel-2-new-hardware-for-the-tessel-ecosystem)*\* runs [io.js natively](http://blog.technical.io/post/112888410737/moving-faster-with-io-js).
- [@maxbeatty]() is working on a new version of jsperf.com backend, running on io.js [link](https://twitter.com/jsperf/status/572716156357873665)
- Blog: [The Node Version Dilemma](http://hueniverse.com/2015/03/02/the-node-version-dilemma/)

# io.js Support Added
- **[scrypt](https://npmjs.com/scrypt)** now supports io.js. [Details here](https://github.com/barrysteyn/node-scrypt/issues/39)
- **[proxyquire](https://github.com/thlorenz/proxyquire)** v1.3.2 published with support for iojs. [Announcement](https://twitter.com/thlorenz/status/572492178829799425)

**Comment by rosskukulinski** [comment]
I would appreciate it if someone from @iojs/core could help flush out the 1.5.0 release description & notable changes.

**Comment by rvagg** [comment]
@rosskukulinski I'm in the process of doing the Notable changes right now, watch the 1.5.0 issue for that.

Breaking news that will impact this update is that Joyent are stepping up to provide some SmartOS machines but we're still in the early stages of that -- the Walmart SmartOS server will probably not end up being required and we'll switch out to Joyent resources. Obviously this is bigger news than just having new build servers so perhaps the best way to handle this for now is to run with what you have and the next update can provide new information about the situation when we actually have our hands on something.

**Comment by Fishrock123** [comment]
@rosskukulinski the changelog will be up when the release goes live.

**Comment by bnoordhuis** [comment]
iojs/io.js#1079 hasn't landed yet (and therefore won't be in 1.5.0.)

**Comment by rosskukulinski** [comment]
thanks @Fishrock123 and @bnoordhuis.  I moved the 1079 under the community update section.

**Comment by rosskukulinski** [comment]
ok @rvagg

**Comment by bnb** [comment]
Great job, @rosskukulinski! I've got a few minor points, but it looks great. Here are my points:

Should the bullets under "Existing companies contributing hardware" be a level deeper? It looks like a list within the list, although I could be wrong.

> published on iojs.org, and i18n links 

I'd change the end of this, so it reads

> published on iojs.org and i18n community sites

With the point

> iojs community has been 

io.js should have a period between the o and j.

And, finally, with

> Blog: The Node Version Dilemma

I would just add a brief description of it, as well as a link to the author.

Again, great job, thanks _so_ much for stepping up and working on this.

**Comment by mikeal** [comment]
`Buffer.indexOf()` was released in 1.5, that should be in the release notes :)

**Comment by mikeal** [comment]
docker blogged about our official repo going in http://blog.docker.com/2015/03/thirteen-new-official-repositories-added-in-january-and-february/

**Comment by rosskukulinski** [comment]
Updated with @bnb and @mikeal comments.  Still flushing out remaining community updates bullet points.

**Comment by rvagg** [comment]
you could mention that PayPal are at least experimenting with internal Node adoption now that that's public via the TLS leak issue

**Comment by rosskukulinski** [comment]
@rvagg node or iojs?

**Comment by rvagg** [comment]
heh, io.js, sorry.

the graphs they have been providing in the leak thread are their experimentations with running Kappa internally on io.js vs 0.12 vs 0.10.

**Comment by rosskukulinski** [comment]
:) Awesome, thanks

**Comment by rosskukulinski** [comment]
ok, updated again.  I think it's all flushed out.  Anything/everything fair game for comments/suggestions/rewrites.

**Comment by julianduque** [comment]
- s/lanuage/language in "are you missing your lanuage?" sentence under i18n comments.
- s/v8/V8
- s/NodeBot/NodeBots
- node.js, Node.js and Node.JS are used in the article, not sure if we want to use only one style.

**Comment by rosskukulinski** [comment]
thanks @julianduque - updated!

**Comment by mikeal** [comment]
Is it ready? I can throw it up on Medium.

**Comment by rosskukulinski** [comment]
@mikeal I've submitted a PR here: https://github.com/iojs/evangelism/pull/36

**Comment by mikeal** [comment]
Published https://medium.com/node-js-javascript/io-js-week-of-march-6th-2f9344688277

**Comment by rvagg** [comment]
the npm sub-points have come out cray cray

**Comment by rvagg** [comment]
```
[are not affected]((https://strongloop.com/strongblog/are-node-and-io-js-affected-by-the-freak-attack-openssl-vulnerability/)
```

too much bracket

**Comment by rvagg** [comment]
```
[Docker build]((https://registry.hub.docker.com/u/library/iojs/) 
```

same

**Comment by mikeal** [comment]
cut the sub points. let's not do subpoints, they don't wokr on medium.

**Comment by rosskukulinski** [comment]
ok, I'll ditch the npm subpoints, fixing the extra brackets

**Comment by mikeal** [comment]
fixed the bracketing issue son the medium post

**Comment by snostorm** [comment]
Trying a little (safe) experiment: https://iojs.org/en/index.html is featuring a link to the weekly update (english homepage.)

This might help keep occasional users more in the loop until we expand the site's content offerings more. Thoughts?

**Comment by rvagg** [comment]
If you read this from the perspective of a new user/visitor there could be confusion about what "update" means, particularly given there is a "v1.5.0" next to it. Sounds like maybe io.js has weekly updates to download.

**Comment by bnb** [comment]
@snostorm @rvagg How about: 

> ~~**Weekly Update - March 6th** featuring official and community updates (**Medium**)~~

**Comment by rvagg** [comment]
better I guess

**Comment by mikeal** [comment]
-1 on the word "official." Strike it from our vocabulary :)

**Comment by bnb** [comment]
@mikeal My bad, I keep forgetting. 

> **Weekly Update - March 6th** featuring core and community updates (**Medium**) 

That better?

**Comment by mikeal** [comment]
+1

**Comment by snostorm** [comment]
Updated, thanks for the feedback

**Comment by rvagg** [comment]
Perhaps someone here should start a new issue for this at the begining of each week, or just after the last update goes out, so you can start collecting tidbits from around the interwebs.

For the next one, while I have it top of mind, @jbergstroem is likely getting a [patch](https://codereview.chromium.org/990063002) into V8 on behalf of io.js to bring Solaris support back into the latest version. It's nice to highlight these points of collaboration because they go to the value of the ongoing relationship between io.js and V8.

**Comment by julianduque** [comment]
@rvagg done https://github.com/iojs/evangelism/issues/41

**Comment by julianduque** [comment]
This was published, thank you all for this great work, this week will be on #41
