### ISSUE TITLE
New frontiers for nodejs/evangelism - Request for Input

### ISSUE THREAD

**Issue by bnb** [nodejs/evangelism#166]
The Evangelism group has died down quite a bit in activity, with only four issues being posted in the last two months. I think this WG can make a huge difference in the development of Node's community, and we should try to maintain consistent activity, as well as develop new methods of engagement with the community. 

The goal of this issue is to help spur that development of new methods of engagement. So, do you have any ideas for how we can further engage the community? Any input is welcome, there are no wrong ideas. 

Here are a few to get things going:
- Weekly interviews with Node developers (from sponsor companies?)
- Weekly sponsored tutorials, possibly at different levels (Introductory, Intermediate, Advanced)
- Official Node.js podcast
- Team-based hackathons, a la Rails Rumble

What are your ideas?

**Comment by mikeal** [comment]
Don't forget that the evangelism WG also runs/moderates the new help repo which has had some activity.

**Comment by mikeal** [comment]
> Official Node.js podcast

:+1: on a podcast but we have to be careful with calling things "official" especially when they are in a format where contributors will make off the cuff remarks.

> Team-based hackathons, a la Rails Rumble

This already exists as "Node Knockout" and will run again in November.

**Comment by mikeal** [comment]
> Weekly sponsored tutorials, possibly at different levels

What do you mean by "sponsored tutorials" in terms of format and what "sponsored" means?

**Comment by bnb** [comment]
The general idea of sponsored posts, as I imagine them, would be a post written by a Node-based company, on the topic of using their service, tool, api, and so on. They would either pay a fee to have it posted, or would get (n) posts as a perk based on their Foundation membership level.

That's just how I imagine a sponsored post might work - if anyone else has an idea, we'd all love to hear it.

**Comment by mikeal** [comment]
I'm -1 on taking money for docs or tutorials. Injecting money can introduce some counter-incentives into our documentation community which we are currently trying to grow.

**Comment by bnb** [comment]
Okay, that's not a problem. I'll put the general idea of sponsored posts on the back-burner and try to think of a unique take on it. If anyone else wants to pitch a solution to allowing community posts into the nodejs.org blog, feel free. Here are some elements to consider:
- There should be room for both individuals and companies to write
- Product promotion is good - as long as the focus is on using Node, and not an editorial advertisement
- Promotion of Node Foundation WG duties, benefits, and contributions are good (non-tutorial articles)
- Best-practices and newer technologies (such as ES6, work other WGs are doing) are good topics for tutorials

**Comment by danielkhan** [comment]
I am currently not really sure about the benefits I would have in writing blog posts as company.
All companies have their own blogs and I'm fine with being included on the weekly news.
If I contribute something, this can internally be booked under thought leadership efforts and then I am not obliged to promote our products at all. So if a company takes evangelism the right way there should be no major difference between a post from an individual contributor or someone that gets actually payed for contributing - maybe a short bio under the post that links back to the company I'm working for.

So I don't completely understand why you think about going down that path at all. It somehow contradicts the way open source works. I didn't even know that you guys are in need of blog content. Why don't you simply ask on - say - Twitter - I'm sure you will get enough content.
Then all you need is the same process that you have in other WGs (like docs).
People can propose, need a to be defined number of LGTMs, they submit a PR when they are done, someone reviews it and at some point it gets published.

**Comment by mikeal** [comment]
I'm in agreement with @danielkhan that we don't really need companies to be able to write on the blog. When companies do good posts about Node.js they now get re-tweeted by the official twitter account, that seems like a better way to support their writing than the project blog.

> Promotion of Node Foundation WG duties, benefits, and contributions are good (non-tutorial articles)

Absolutely, we should let the WGs know that they can post whenever they like and that they can also attract people to various Issues on GitHub through twitter now that we have access to all of it.

> Best-practices and newer technologies (such as ES6, work other WGs are doing) are good topics for tutorials

We've been talking lately about a "ES2015 for Node Core" guide. There are several features in use in core. Basically, once a feature no longer has a performance cost it starts being used in core so this would end up being a good general guide.

**Comment by bnb** [comment]
Okay, no problem on the sponsored posts - that was just one idea that I thought might be successful in soliciting more activity and engagement with the Foundation. 

Regarding the standard format for PRs to create content in WGs (and, with regard to evangelism/nodejs.org), I'm a bit cautious. I think this could be very successful, but it needs to be promoted properly. If we just have the structure in place to allow anyone - that's powerful, _anyone_ - to create an article that is published to nodejs.org, it needs to be used as a tool to pull in engagement. It should be actively promoted. It's a powerful tool, and it is a **huge** waste to not get everything we can from it.

**Comment by rvagg** [comment]
I'd like to see @nodejs/evangelism take over the `@nodejs` twitter handle. I'm pretty sure they would do a better job of keeping it on topic and consistent. I believe Zibby from the Foundation is doing most of the work on it, and good on her for keeping it up, but a lot of the tweets don't really come off as consistent with the tone of the actual activity going on (including the language used which is sometimes _off_). It's also currently being used to cross-promote Linux Foundation material and I'm not a huge fan of taking it so off-topic and giving people a reason to un-follow.

Also, timeliness, everyone actively involved in @nodejs/evangelism is on the ball and would be able to be in sync with releases, notifications, interesting news, etc. it's also a global team so it wouldn't be US-timezone based.

I don't know what the weird machinations were to get the handle off Joyent and into the Foundation but now that it's _in_ the Foundation we should be using it better IMO.

/cc @mikeal

**Comment by julianduque** [comment]
Totally agree with @rvagg, we were doing a great job with the official_iojs twitter handle, this can be also a joint effort with Foundation marketing team and we can still use this @nodejs/evangelism to coordinate tweeting activities.

**Comment by mikeal** [comment]
One of the reasons this hasn't been as responsive as we would have liked is because the foundation is currently a bit under-staffed with an open req for a marketing coordinator. In the interim Zibby (PR) and myself (Community) have been trying to fill the gaps. It's only been a week or so since I told the Evangelism team that they should DM the twitter account if they want something posted. In that time, nobody has done so.

> we were doing a great job with the official_iojs twitter handle

We were doing great when I was looking at it 6 times a day and replying to every message. Since then, not so much. I don't have the bandwidth for this level of involvement and we never figured out a good system for sharing that load, we have a bunch of people with access to the account but we don't know who has looked at what and the tools we looked at for doing so didn't work.

> including the language used which is sometimes off

One thing I expect to see once we have a real resource working on this is a document that describes the "voice" of the account and consistent language to be used. 

> in sync with releases, notifications, interesting news, etc.

This should be automated. All releases and new blog posts should just get auto-posted. I'll look in to writing this.

**Comment by danielkhan** [comment]
I think answering things on twitter and retweeting is one thing but _authoring_ useful and interesting tweets using the right "tone" for 275K followers looks like something that needs some kind of leadership. If I was member of this WG and wanted to get something on twitter I would really want an authority that approves it.

**Comment by MylesBorins** [comment]
Have you considered introducing a tool such as hootsuite?

Makes it easy to distribute access to an account on a team, schedule tweets, make tweets that are open for review, etc.

**Comment by bnb** [comment]
@TheAlphaNerd We have, but that was in iojs times when we didn't really have a method to pay for it. Maybe the Foundation can change that, but I think we need more active Evangelism contributors to make it work. 

@mikeal Would putting out calls to action for joining WGs, including the Evangelism WG help to pull more contributors?

**Comment by mikeal** [comment]
> Would putting out calls to action for joining WGs, including the Evangelism WG help to pull more contributors?

We should do these one at a time and space them out. What WGs are currently asking for new member?

**Comment by bnb** [comment]
@mikeal +1 to spreading them out. Should we @ mention the WGs here, asking them who wants new members?

**Comment by bnb** [comment]
Going to close this due to inactivity in the issue. Please, feel free to create a new issue or request this one be re-opened if needed.
