### ISSUE TITLE
Automating Social Media Content

### ISSUE THREAD

**Issue by bnb** [nodejs/evangelism#170]
Mikeal wrote (https://github.com/nodejs/new.nodejs.org/issues/223#issuecomment-146657652) that we will ideally have automated postings of news from whatever sources to our social media tools. 

We have three options: do everything manually, build our own architecture, or use IFTTT. 

Doing everything manually is how we've done it. We can handle it, but it's a lot more work than is necessary. The time spent on doing it manually could be spent better elsewhere, if we can automate a good amount of the work.

Building our own architecture is a possibility - I'd be willing to try to build this if someone would be willing to spot me on the programming. The benefit of this is that we have full control over it, and can make it do whatever we want it to.

I just looked at IFTTT, and they have a Medium channel that seems to allow you to post entire blog posts from an RSS feed. That would essentially solve https://github.com/nodejs/new.nodejs.org/issues/223. If there is a place where we can either get a RSS feed of releases, or set up an email workflow where an email is sent/generated when a new release is made, we can automatically notify through the RSS or Email channels to the Twitter channel on IFTTT.

Comments? Ideas?

**Comment by claudiorodriguez** [comment]
IFTTT is a pretty handy tool for this kind of thing. What kind of sources are we talking about, and which actions are taken exactly? Is there anything that would need coding work? I'm willing to lend a hand.

**Comment by bnb** [comment]
I think this can be closed - seems like it's been decently long enough that this has probably already been figured out. Definitely shout out if this is still a problem, or something that could be improved on!
