### ISSUE TITLE
Node Community Convention

### ISSUE THREAD

**Issue by datmiznags** [nodejs/evangelism#174]
Node Community Convention is bringing node.js experts from around the world to San Francisco January 26-28th. Join us! www.nodecommunityconvention.com

**Comment by Trott** [comment]
There are some great folks on your schedule. That said, the all-male and mostly-white speaker list in a "community" event suggests (rightly or wrongly) that the community is not very welcoming to women and PoCs. I would encourage you to reach out to women and PoCs for your few remaining TBA speakers.

**Comment by MylesBorins** [comment]
I would also highly suggest making the code of conduct more visible before doing so. Right now it is hidden under the contact us menu item... which makes very little sense. Many people from under represented groups have voiced not seeing a code of conduct as an immediate deal breaker for them

**Comment by nebrius** [comment]
I would also strongly recommend providing diversity scholarships. The community run JS conferences have had a lot of success increasing the diversity of attendees this way, which leads to a better conference for everyone.

**Comment by beaugunderson** [comment]
:+1: on the three proposals above.

**Comment by mikeal** [comment]
What was the request here? To promote the conference or just letting us know about it in case we want to attend?

**Comment by datmiznags** [comment]
All of the above. I particularly appreciate the feedback on agenda. That was also a goal.

**Comment by bnb** [comment]
Event is over! 🤗 Closing.
