### ISSUE TITLE
Get LTS post on our official blog

### ISSUE THREAD

**Issue by mikeal** [nodejs/evangelism#178]
There's an excellent post by @rvagg on Medium about LTS. Right now it's our best doc about LTS. With v4 going LTS and v5 getting released it would be great to get this on the nodejs.org blog.

https://medium.com/@nodesource/essential-steps-long-term-support-for-node-js-8ecf7514dbd

Is there something we need to update in it as well?

**Comment by MylesBorins** [comment]
This is a great idea. I'd be more than happy to put together copy for this if you want to give me a word count

**Comment by mikeal** [comment]
I don't have a target word count, just need to get all the info from @rvagg's prior post but brought in to the current tense with references to v4 release points.

**Comment by MylesBorins** [comment]
Sounds good to me. I'm in the process of writing some copy on LTS for collaborators.md in the main repo. I can put something together afterwards. When would you like to have this out by?

**Comment by mikeal** [comment]
prior to the v5 release, a day or two before would be ideal.

**Comment by rvagg** [comment]
Without looking, I think the only major difference since that was posted was the contraction of the 0.12 schedule to end in December 2016, but we have a new graphic for that (it's on the nodejs/LTS repo README).

**Comment by bnb** [comment]
Assuming this can be closed? Cleaning up the Evangelism WG repo, and this is quite old.

**Comment by bnb** [comment]
Closing ❤️
