### ISSUE TITLE
Globalize date formatting

### ISSUE THREAD

**Issue by dotproto** [nodejs/evangelism#18]
I noticed that the date format we're using for weekly updated is `MM-DD-YYYY` (PR #12). Given the global reach of io.js and Node.js, I'm concerned that this date format is too US-centric.

According to the [Date format by country](http://en.wikipedia.org/wiki/Date_format_by_country) article on Wikiepdia, `MM-DD-YYYY` format is only used by 6 countires. The second most common format is `YYYY-MM-DD` (28 countries). Globally, the most commonly used date format is `DD-MM-YYYY` (124 countries).

I propose that in documents we adopt `DD-MM-YYYY` format as its the most commonly used date format across the globe. Further, I propose that we adopt `YYYY-MM-DD` in file names for sorting reasons. Given the mechanics of how filesystems and programming languages typically sort strings, this format ensures that files will be chronologically sortable.

**Comment by bnb** [comment]
+1. Sounds good to me. Are we using `MM-DD-YYYY` anywhere outside of the file names for the weekly updates?

**Comment by tellnes** [comment]
+1

**Comment by dotproto** [comment]
@bnb not to my knowledge, but I'm trying to think ahead.

**Comment by rvagg** [comment]
so much yes

but

I'm quite fond of a `YYYY-MM-DD` format as a compromise, it's nobody's official format but everyone understands it and it's sortable.

**Comment by tellnes** [comment]
I do also prefer the `YYYY-MM-DD` format for the same reasons as @rvagg.

**Comment by dotproto** [comment]
FWIW I also prefer `YYYY-MM-DD`. I've opted to use it as my standard dating scheme for io.js Audio files on SoundCloud.

**Comment by bnb** [comment]
I got it done locally, but realized I pulled a stupid with git. I'll send a PR soon, and it can be approved if we get another +1.

**Comment by Starefossen** [comment]
+1 for `YYYY-MM-DD`!

**Comment by julianduque** [comment]
Please, +1 for `YYYY-MM-DD`

**Comment by bnb** [comment]
Added in #19, just needs +1.

**Comment by a0viedo** [comment]
+1, even the localization teams could consider moving to `YYYY-MM-DD` format

**Comment by bnb** [comment]
Closing, as #19 was merged in 7fe19f1d68de2abc2fe8f7b94483cc0b7a839b0c.
