### ISSUE TITLE
Logo iteration: speculative design work—should we do this?

### ISSUE THREAD

**Issue by joshkehn** [nodejs/evangelism#181]
The request by @mikeal in #179 for design work is clearly [speculative design work](http://www.nospec.com/articles/just-say-no). The question is, do we want to perpetuate this trend in the industry? 

> The Marketing Committee will look over all of this at some point in the future and potentially select one or take some of the ideas/direction and handoff to a designer. 

Not only is this speculative, but the work itself won't be credited back to the designer. Everything is going into a pot, the Marketing Committee will sample that pot, and then a—paid?—designer will take it from there? 

> You could ask the same question about any contribution to open source, why is this different?

Because design work contributes to the _brand_ not the _community_. Open source is a labor that equally benefits everyone, if they participate or no. Code can naturally be improved, optimized, and refactored. Not so with a design. Additionally, the community around the project decides what goes in and what should be changed. Not the Marketing Committee.

Contributing the code that will go under a known license in a way where you are credited for that code is vastly different from this idea dump where people have no recognition for the effort they put into it.
### But people are enjoying this

I'd be happy to show you development contests where the person who built the best online storefront and had fun doing it launched world wide to much success. _But alas, those don't exist_. I don't mean to trivialize people trying to contribute. I'll point to documentation, localization, and learning as possible avenues to support the projects they use and admire. 
### So maybe this isn't good, what can we do?
1. Don't allow spec work, hire a design company to do branding. 
   
   This option costs money but asking for donations—[if done properly](https://www.google.com/search?client=safari&rls=en&q=scalenpm&ie=UTF-8&oe=UTF-8)—is better from an input/output perspective. Having branding work done by a professional means various asset sizes, treatments, color palates, and renderings are consistent. It also means there's an easy path for refinements or additional work.
2. Open-source the design process.
   
   Treat this just like a project. Open source image formats, scripts for rendering outputs, and contributions via pull requests and voting. If the argument is open source means free in all aspects then why not continue that with the branding?
3. Ignore it and continue.
   
   We can either take an amateur—unpaid—route or not. I'd like to hear the arguments for it and be convinced. I'll be the first person to disagree with spec work, but also the first to admit that some [time honored mascots](https://en.wikipedia.org/wiki/Tux) have come out of design contests. I think they are exceptions.

**Comment by mikeal** [comment]
> Not only is this speculative, but the work itself won't be credited back to the designer.

Credited how? The work is the accumulation of collaborative effort in that thread, which is public. It's unlikely that the work can be credited to any single individual but where it can be credited is public.

> Because design work contributes to the brand not the community.

The success of the brand to date has mostly been in the community. Just take a look at the number of projects and stickers that have adopted the hexagon as part of the community identity. This is not just the brand of a company or product but of the community, which is now protected by a non-profit foundation.

> Code can naturally be improved, optimized, and refactored. Not so with a design.

Not true. The iterations in the thread are collaborative, each contributor building from anothers ideas. Not to mention the fact that the entire thread is an iteration on prior art work produced by Joyent.

> I'd be happy to show you development contests where the person who built the best online storefront and had fun doing it launched world wide to much success. But alas, those don't exist.

People seemed to have a lot of fun [the last time](https://github.com/iojs/io.js/issues/37) we did this and aren't showing up to tell us they feel violated.

> Don't allow spec work, hire a design company to do branding. 

You seem to be assuming that the thought process behind doing this was to avoid hiring a design firm. That is not the case.

Paying for the work would have been the easiest thing to do but it wouldn't have given us any input from the community nor widened the contribution base. We did it this way so that more people have a way to participate and so that we, as a community, continue to build competencies outside of just code.

**Comment by bnb** [comment]
+1 @mikeal. I might have been a bit more on the fence about this if it was a new direction, but it's not - the io.js logo thread was a fantastic success, and it generated a lot of public interest and media coverage.

**Comment by robwierzbowski** [comment]
+1 @joshkehn. Think about what this would be like for a feature; it's not people submitting many small pull requests with a possibility of most of them being merged, but many people submitting different, near complete pull requests for the same feature, only one or two which will be merged and iterated on into a final release.

As a process note: established designers don't do unpaid spec work, and I don't know many designers that would be happy with the brief "Here's some free work we had done by volunteers/amateurs/non-established designers. Please take these ideas and make them better." If experts are going to be employed, might as well use their expertise from the start. There's some [really great work in that issue](https://github.com/nodejs/evangelism/issues/179#issuecomment-150353490), actually; there's no reason the experts can't be volunteers from the issue, but work with the final decision makers in a less open call, spec like fashion.

Whiteboarding design ideas with the community is great, but I understand the criticism that the referenced thread runs in a grey area between whiteboarding/brainstorming and spec work.

**Comment by joshkehn** [comment]
> Credited how? The work is the accumulation of collaborative effort in that thread, which is public. It's unlikely that the work can be credited to any single individual but where it can be credited is public.

This stirs the design “pot” so to speak and makes it impossible to figure out where an idea came from. We're in agreement on that. Where we disagree is if that is a positive or a negative. I also think you're under estimating how much people would like credit for their ideas. By making this a pot you're eliminating that possibility and some sort of disagreement about “who created that iteration” is likely.

> Paying for the work would have been the easiest thing to do but it wouldn't have given us any input from the community nor widened the contribution base. We did it this way so that more people have a way to participate and so that we, as a community, continue to build competencies outside of just code.

I would suggest that instead of running it backwards with community driven concepts into a designer—as it currently is—you employ an established designer to make some comps and suggest new ideas. Then you can drive those ideas into the community for feedback.

**Comment by bnb** [comment]
Closing - logo design has been finalized, and this has almost reached a vintage of one year. If there needs to be more discourse about this, feel free to re-open - just not sure what that would be at this point.
