### ISSUE TITLE
Add Contributor: @Trott

### ISSUE THREAD

**Issue by bnb** [nodejs/evangelism#184]
@Trott seems to be doing a lot of work for the WG, spending a good amount of time contributing information. I +1 adding him as a contributor.

**Comment by JungMinu** [comment]
:+1:

**Comment by bnb** [comment]
@nodejs/evangelism +1 or -1s would be appreciated.

**Comment by julianduque** [comment]
:+1:

**Comment by RichardLitt** [comment]
:+1:

**Comment by bnb** [comment]
Will add @Trott to Evangelism contributors if there are no -1s in the next 24 hours.

**Comment by mikeal** [comment]
+1

**Comment by bnb** [comment]
Added. Welcome aboard, @Trott.

**Comment by Trott** [comment]
Thanks. I'll review the CONTRIBUTING, GOVERNANCE, et al. docs.

**Comment by julianduque** [comment]
Welcome @Trott !
