### ISSUE TITLE
Create list for ongoing notices, pluggable in official social media.

### ISSUE THREAD

**Issue by bnb** [nodejs/evangelism#185]
See: https://github.com/nodejs/evangelism/issues/182#issuecomment-150462304

Essentially, there are topics in the community, such as global NodeSchool events, new meetups, Foundation events, Foundation membership awareness, member events/notices, and so on, that happen on an ongoing basis.

We should have a list of these in the Node.js Evangelism repo so we can refer to them for promotion, without forgetting some, while continuing to promoting others.

Additionally, the list should have a set of guidelines for adding things to it. Anyone who thinks their topic would be appropriate for the list should be able to send a PR that follows the guidelines to add their topic.

Iterations/comments/suggestions on this idea are welcome.

**Comment by Trott** [comment]
good-first-contribution tag should be called out from time to time too.

This might actually be a good use case for the much-maligned much-ignored GitHub wiki feature.

**Comment by bnb** [comment]
@Trott we're intentionally avoiding the GitHub wiki, as it fragments our structure of content-flow and organization. @mikeal probably has better words than I do to phrase it correctly.

**Comment by Trott** [comment]
It's a shame, because sometimes a wiki is exactly the right tool. But I agree that the GitHub wiki has definite problems and can understand avoiding it.

**Comment by mikeal** [comment]
> @mikeal probably has better words than I do to phrase it correctly.

Sure, the problem is that GitHub's wiki is lacking all the social features that make GitHub actually work. You can' have conversations or get the attention of contributors via @

**Comment by Trott** [comment]
Yeah, those are definite shortcomings with no easy solutions. I'll stop polluting the comment threads with suggestions to use the wiki and possibly maybe start polluting them with comments bemoaning that the wiki doesn't work for our purposes. :-P

**Comment by mikeal** [comment]
I wonder if there is an API we can use to overcome some of these shortcomings?

**Comment by bnb** [comment]
@mikeal How/what do you think we could possibly change? One thing I do know is that every repo's wiki is in itself a git repo.

**Comment by mikeal** [comment]
If we could automate an issue post for each change, or a PR, we could have a discussion.

**Comment by bnb** [comment]
Going to close this due to inactivity in the issue. Please, feel free to create a new issue or request this one be re-opened if needed.
