### ISSUE TITLE
Contest for node.js devs

### ISSUE THREAD

**Issue by galinabas** [nodejs/evangelism#186]
Hello guys! I would like to invite you to our javascript contest made special for node.js devs. It lefts only 2 days till the end of the contest, so don't hesitate to participate. The participation is free and the best contestants will be awarded with great prizes! Here is the link to the event http://ibm-bluemix.coderpower.com. 

Would be great to have your feedback!

**Comment by bnb** [comment]
Closing, looks like this is from a spam account. Feel free to correct me if I'm wrong.

**Comment by mikeal** [comment]
It's not spam :) A tweet went out about it already though, is there anything else you'd like to see done?

**Comment by bnb** [comment]
Closing - no further responses in the past year. ❤️
