### ISSUE TITLE
Event: JSConf.Asia

### ISSUE THREAD

**Issue by Trott** [nodejs/evangelism#189]
JSConf.Asia in Singapore on Nov 19 and 20 seems to have a lot of Node.js content. Might be a good addition to the Events section of the weekly updates.

http://2015.jsconf.asia/

Node presentations include:
- Tim Oxley on "The Structure of Node.JS Applications"
- "Scalable Micro Services with Node.js"
- "Node.JS Authentication and Data Security"
- Although it doesn't mention Node in the title, "Reactive JavaScript at Netflix, Microsoft and the World"  by Matthew Podwysocki seems likely to be Node-centric.

I thought I saw that Danese Cooper (Chair of the Node Foundation) was going to be there, but I'm not seeing that on the website.

Anyway, you get the idea.

**Comment by yosuke-furukawa** [comment]
Looks fine. add jsconf.asia to next update.

**Comment by serrynaimo** [comment]
I can confirm Danese as speaker. She's gonna be announced soon.
If people want to come, we still can fit 60 more pax. Use "NaN" as promotional code and get 20% off ;)
Looking forward to it!

**Comment by bnb** [comment]
Closing - event is over! I see the next one is coming up on the 25th/26th of November. Making a new issue to promote (if possible) would be rad!

**Comment by serrynaimo** [comment]
🎉🎉🎉 Here if you need anything! :)
