### ISSUE TITLE
Blog Series: We've got Node ideas

### ISSUE THREAD

**Issue by bnb** [nodejs/evangelism#190]
I was just checking in on /r/node, and saw an interesting post on 11 "cool" things you could build with Node. The post wasn't written as well as we could write it, and there are so many opportunities that we could make it a weekly post.

Here are my ideas for this:
- Weekly article
- Have an open issue/weekly issue for ideas to be shared
- Write 2-3 paragraphs on each idea and how it can be executed
- Somewhere down the line, highlight weeks where we only do ideas of a certain type, such as npm utilities, physical electronics programming, etc.

I would be happy to write these, and let the community take over when/how it wants to.

Feedback welcome.

**Comment by bnb** [comment]
Additionally, something that we might be able to do is write a post/have a guest post on finished ideas that community members took and built. Awesome way to promote community members and increase engagement with them.

**Comment by mikeal** [comment]
I'm not so sure about "things you could build" when there are so many things people _have_ built. I'd love to highlight, on a weekly basis, projects written in Node. We could put together a good list and start writing them and queue them up for weekly release :)

**Comment by bnb** [comment]
@mikeal Okay, that sounds good. Are there specific criteria you have in mind? I wouldn't mind writing several posts a week about individual projects and their awesomeness.. 

That said, I think there is a huge field of modules/systems/programs/whatever you want to call it that are still underdeveloped. There's a whole culture around idea repos on GitHub where people store ideas that they don't have the time/money/skill/other to build. The ones that I have read are pretty interesting. 

The main reason I'm pushing for this is that I think it would be a good way to engage with people who are using Node as their first programming platform, as well as those who aren't familiar with the code design patterns that Node uses.

**Comment by mikeal** [comment]
> There's a whole culture around idea repos on GitHub where people store ideas that they don't have the time/money/skill/other to build. The ones that I have read are pretty interesting. 

Would you mind sharing a few links to these so i can get a better idea of what you mean.

> Are there specific criteria you have in mind? I wouldn't mind writing several posts a week about individual projects and their awesomeness.. 

Totally up to you, but if you started a thread soliciting projects to explore you'd probably get a great list. And, this is just a suggestion, but maybe come up with a standard list of questions to ask then in a new github issue and work from there to get information you can boil down into a good article. But feel free to go about this however you see fit.

**Comment by bnb** [comment]
List of GitHub idea repos: 

https://github.com/captn3m0/ideas
https://github.com/mattdesl/ideas
https://github.com/Vheissu/Free-Ideas
https://github.com/devcroo/ideas
https://github.com/h5bp/lazyweb-requests/issues
https://github.com/samsquire/ideas

Mine: https://github.com/bnb/ideas

@sindresorhus's: https://github.com/sindresorhus/module-requests/issues

I will post a call to action for cool modules tomorrow. Would you be able to tweet it once it's up?

**Comment by bnb** [comment]
I will also create a standard question list for the post tomorrow - great idea.

**Comment by bnb** [comment]
Going to close for now - more of a content piece than I've typically seen on the official blog. Feel free to reopen to discuss.
