### ISSUE TITLE
Implementing security into NodeJS

### ISSUE THREAD

**Issue by marylinh** [nodejs/evangelism#194]
Hi there.

NodeJS is an awesome platform and I was wondering if there is a clear process in place to provide security features to platform. If this is not the case I would like to contribute with this part

regards

Marylin

**Comment by ghost** [comment]
sorry, could you elaborate on what you mean by 'security features'? also, this is probably not the right repo, you're probably looking for [nodejs/node](http://github.com/nodejs/node)!

**Comment by bnb** [comment]
@sup This is the group that handles all written information. However, I think we've reached a conclusion that content posts such as this are not being accepted at present - someone correct me if I'm wrong.

**Comment by ghost** [comment]
@bnb ah, apologies. however, i still believe that elaboration might be needed in this particular case

**Comment by bnb** [comment]
+1 to elaboration - in any case, we would want more information to be able to make a solid judgement.

**Comment by marylinh** [comment]
Building Security features such as how to build and implement secure Authentication, Authorisation, Sanitise user input, Avoid Injections, etc. In other words, best practices developing a secure application using NodeJS

**Comment by bnb** [comment]
I'm going to close this for now - @marylinh as far as I know, the blog isn't taking community articles at this point. If you'd like to discuss that, I'd shoot over to the [Website WG](https://github.com/nodejs/website) repo and ask what the policy is and if it could or would be considered
