### ISSUE TITLE
Evangelism: Weekly Update for November 28 ~ December 3

### ISSUE THREAD

**Issue by JungMinu** [nodejs/evangelism#195]
Let's write down for next week :gift:

**Comment by bnb** [comment]
[Node.js running in the new Airbus A350 inflight servers](http://reaktor.com/blog/aircraft-customer-experience-on-a-new-level/)

**Comment by bnb** [comment]
[Automatic cat feeder powered by Node.js](https://github.com/rachelnicole/robokitty)

**Comment by bnb** [comment]
[Netflix' Node powered interfaces](http://tnstack.io/Vri6B)
