### ISSUE TITLE
Release line messaging

### ISSUE THREAD

**Issue by mikeal** [nodejs/evangelism#199]
Hello everybody :)

Recently we've seen a ton of confusion about releases. Some of this is due to poor messaging but much of it is also because we've dramatically changed the meaning on semver minor releases and their impact on the ecosystem.

I propose that from now on whenever we mention a release of node across the blog, website, etc we do the following:
- **When referring to a release line always call it "vMAJOR" as in "v4" or "v5."**
- Whenever possible do not make note of the exact version "4.2.1" or "4.2" because it makes people think that what you're talking about is specific to a semver minor when in fact we guarantee compatibility within the major.

@nodejs/tsc @nodejs/website @nodejs/collaborators

**Comment by ghost** [comment]
+1, makes it significantly easier to understand

**Comment by mcollina** [comment]
:+1: that was confusing.

**Comment by bnb** [comment]
This is the messaging we've had for quite a while, so it seems like this is working 💥 

Going to close this due to inactivity in the issue. Please, feel free to create a new issue or request this one be re-opened if needed.
