### ISSUE TITLE
Initial Members

### ISSUE THREAD

**Issue by mikeal** [nodejs/evangelism#2]
I have a PR in to officially charter the Evangelism Working Group and we need an initial list of members :)

Off the top of my head I'd like a collection of people who have been contributing a while and we definitely need to pull in some of the i18n community:
- @bnb
- @emilyrose
- @mikeal
- @yosuke-furukawa
- @julianduque
- @rosskukulinski

Let me know if you'd like to a member :)

**Comment by bnb** [comment]
I'd be happy to be a member. Super excited to get started as a part of this WG.

**Comment by julianduque** [comment]
Love to be part of it :)

**Comment by rosskukulinski** [comment]
I'm in @mikeal

**Comment by affinity-matrix** [comment]
I believe this to be relevant to my interests.

**Comment by a0viedo** [comment]
I would like to help with this WG.

**Comment by dotproto** [comment]
@a0viedo It's an open community project. Feel free to jump in and lend a hand when and where you can. You don't have to be an official WG member to help :smile:

**Comment by bnb** [comment]
@svincent @a0viedo Absolutely. If you have ideas, just start adding issues or creating PRs!

**Comment by gko** [comment]
I'm from iojs-ru. Would like to help.

**Comment by yosuke-furukawa** [comment]
wow, I have not noticed this. I would like to help io.js users with this WG :dancer:

**Comment by bnb** [comment]
@yosuke-furukawa Awesome, glad you're going to be around!

**Comment by rosskukulinski** [comment]
Somehow we completely forgot about @tonypujals who was part of the initial hangout helping @mikeal develop the roadmap slides.  I'd like to propose adding him as well.

**Comment by subfuzion** [comment]
Thanks, definitely count me in!

**Comment by psvet** [comment]
:+1:  for @tonypujals!

**Comment by rosskukulinski** [comment]
I should also note that @tonypujals is one of the co-organizers of [BayNode](http://www.meetup.com/BayNode/); specifically he organizes all of the learning-node events which routinely have 100+ attendees every month.

**Comment by aswiniatibudhi** [comment]
+1 for  @tonypujals

**Comment by mikeal** [comment]
So, I don't want being a "member" of the WG to become a barrier to participation. Ideally the members deal with _problems_ and a much broader group of people are getting things done on a day-to-day basis. We've been lucky enough to see a few people step up in huge ways and get added rather quickly, I don't want to see that end because the perception becomes "you have to be a member to participate."

**Comment by mikeal** [comment]
That said, I have no objection to adding @tonypujals specifically :)

**Comment by bnb** [comment]
I have no opinion of @tonypujals, as I haven't been aware of him previously. If you guys think he will be beneficial, then I have absolutely no objection.

@mikeal I absolutely agree about being a member. I think we need to try to find a way to make contributing easier, i.e. create a few cannels that people can start contributing to without needing account access.

**Comment by mikeal** [comment]
> I think we need to try to find a way to make contributing easier

I've actually gotten almost a dozen message asking "how do I get involved with the Evangelism WG" so this is something that really isn't obvious to people right now. We should update the README with a big section at the top about how to get involved.

**Comment by bnb** [comment]
Has this been resolved? Seems like we're beyond initial members now, but is there anything else needed from this?

**Comment by mikeal** [comment]
Closing.
