### ISSUE TITLE
Update Readme with initial member list

### ISSUE THREAD

**Issue by rosskukulinski** [nodejs/evangelism#20]
Its awesome so many people want to get involved.  One comment: the [working_groups.md](https://github.com/iojs/io.js/blob/v1.x/WORKING_GROUPS.md) document references the evanglism readme which has a list of the members.  Once we've come to a consensus on our initial group we should update our README.md accordingly.

**Comment by bnb** [comment]
I wrote up the GOVERNANCE.md and CONTRIBUTING.md, which come from the template in the WORKING_GROUPS.md file. I kept getting sidetracked when I was trying to send it yesterday. It's now available in #22.

**Comment by dotproto** [comment]
@bnb, small bit of feedback: could you make the GitHub usernames of the WG members in the README into links? I don't think GitHub Flavored Markdown does that automatically.

I'm at work ATM, so apologies for not making a PR.

**Comment by rosskukulinski** [comment]
this has been fixed with #22 and #25
