### ISSUE TITLE
nodeschool workshopper/tutorial for how to get node installed

### ISSUE THREAD

**Issue by ghost** [nodejs/evangelism#200]
over at the inclusivity group, we discussed on pre-conference education for first-timers and newcomers to node. the idea of a nodeschool workshopper focusing on how to install node was brought up, but there are still points to clear (such as how to install the workshopper in the first place, assuming node isn't installed). nevertheless, i believe that this is an interesting topic and might help people get into node more easily (which is what the inclusivity project is all about!)

/cc @TheAlphaNerd @jasnell @mikeal

**Comment by MylesBorins** [comment]
The first though I had was that we could use electron to embed node / browser based terminal to get people through the first steps on their own machines. The application could do some basic vendor checking and then offer a getting started tutorial for various install methods / tool chains.

Essentially this stand alone app could itself become a template for writing onboarding documentation

**Comment by ghost** [comment]
@TheAlphaNerd you mean that it might become a format like workshopper eventually?

**Comment by MylesBorins** [comment]
that was what I am imagining. That being said @Mikeal raises a good point about how that would scale. I'm not convinced that we can truly scale with only hands on on boarding though.

**Comment by mikeal** [comment]
@TheAlphaNerd I'm imagining that as we do these by hand we can slowly improve the documentation around install issues and setting up environments until we have something comprehensive.

**Comment by ghost** [comment]
@mikeal wait - what does 'by hand' mean in this context?

**Comment by mikeal** [comment]
@sup literally sitting next to someone and helping them figure it out :)

**Comment by ghost** [comment]
@mikeal oooh, you mean the 'install fest' idea?

**Comment by ghost** [comment]
what i think might be a decent idea would be a site/format where you get asked multiple questions related to os, editor, ide etc.. and then get presented with an install guide that's easy to understand AND suited for your situation. if anything doesn't work, you can request personal assistance (even though that should probably be up for debate)

**Comment by mikeal** [comment]
So, I'm going to get a little pie in the sky here, but what would be best is a more humane installer.

If we could create an installer, maybe with Electron, that:
- Installs Node.js
- Tests that Node.js works properly.
- Tests that npm works properly and fixes common permission errors.
- Offers additional help (in-app documentation) on setting up your environment and using npm.

This could be huge for us as nearly every new user trips over one of these things. It would make Node.js the easiest platform to get up and going on.

Thoughts? @maxogden @ashleygwilliams

**Comment by jasnell** [comment]
Just some context here... In late February I will be running a NodeSchool
type lab at IBMs InterConnect conference. @thealphanerd and I are working
on the agenda and materials. I'm hoping that we can use it as a test for
evolving these kinds of tools.

**Comment by max-mapper** [comment]
@watson was working on a page for the nodeschool website with really detailed install instructions, but I can't find it right now (it was never finished, but had a good start)

**Comment by watson** [comment]
@maxogden yeah, it's on my always growing todo list of bad conscience: https://github.com/nodeschool/nodeschool.github.io/pull/390

**Comment by MylesBorins** [comment]
@watson would you appreciate an external iteration?

**Comment by watson** [comment]
@TheAlphaNerd I'd appreciate all the help I can get :smiley:

**Comment by Knighton910** [comment]
@mikeal That's a great idea. It streamlines the process :tada:  and your up & running :runner:  with no headaches & online searching for installation resources.

**Comment by rvagg** [comment]
fwiw there is some prior art here, sort of. goingnative's [first exercise](https://github.com/workshopper/goingnative/blob/master/exercises/am_i_ready/exercise.js) is an environment test to make sure you have what you need. Since add-ons are such an essential part of node development, this might be something to include as an extra step beyond the basic setup.

**Comment by seabaylea** [comment]
@jasnell I'm also due to be at IBMs InterConnect conference if some more on-site hands would be useful.

**Comment by bnb** [comment]
@pup / @jasnell is this able to be closed? Can't tell what kind of resolution it came to. 🙏

**Comment by ghost** [comment]
@bnb if there's any further discussion, i'd rather not have it sit in a 2-year old thread, so yeah, go ahead

**Comment by jasnell** [comment]
Yeah I'd say this can be closed
