### ISSUE TITLE
Call for Podcast Guest Suggestions

### ISSUE THREAD

**Issue by gtewallace** [nodejs/evangelism#204]
Happy New Year everyone!

We'd like to get a weekly or bi-weekly Node.js podcast series going.
The first step is to line up some amazing guests. 
The only criteria is that they be contributors to Node.js inside the Node.js org.
Please drop your suggestions here along with a very short reason why you suggest them - and be sure to include their github alias so we can track them down ;)

TIA

**Comment by mikeal** [comment]
Just to clarify, it can be anyone who contributes to any working group inside the org. The point of the podcast is to shed light on some parts of the project people don't have much visibility into and let people know about some of the people doing the work.

**Comment by rvagg** [comment]
Seems to overlap pretty heavily with NodeUp, perhaps you should be considering collaborating there, a bunch of us appear on it, and host it, regularly and it sounds like you're going to be covering similar topics. I'm sure NodeUp would appreciate more content and would be happy to explore alternative formats and alternative hosts. It has a big following already so it'd be easier than trying to form a new audience and confusing the podcast-listener market. Perhaps you should have a chat with Jordan, nodeup@gmail.com, he's super easy to work with.

Anyway, I was asked to come in here and highlight some individuals who I see doing background work around Node that don't get much exposure. Here's some of my favorites from the top of my head (I'm sure there are others that aren't coming to me that I should be highlighting):
- @jbergstroem and @joaocgreis basically do all of the meaty work on the Build end of the project, I get far too much credit still for this while they are doing the lion's share and their recent work has been adding amazing technical value
- @JungMinu here for pulling together the weekly updates, regularly, on schedule
- @fhemberger and @phillipj for their tireless and responsive work on the website, vital, but unrecognised work
- @Trott for his work on improving the quality of testing, the ratio of value provided to glamour is soooo out of whack on this
- @kkoopa for work on NAN, shouldering the bulk of the work there
- @calvinmetcalf has been working consistently to keep readable-stream alive and in sync, I think many people underestimate how important that project is (ranked 4th in downloads by one measure: https://nodei.co/npm/readable-stream.png?downloads=true&downloadRank=true&stars=true)

Over the next few months I'd be keeping an eye on the docs WG to see who are the stand-out contributors there. It's looking like they are gearing up for some pretty heavy work but I don't think we know yet who will be putting in the hard work yet, but whoever they are, they are unlikely to get the credit for the value they add, which will be huge.

**Comment by jbergstroem** [comment]
I think the new @nodejs/testing group should get some spotlight. What @Trott has been spearheading for the project is nothing short of amazing -- we are soon at a recurring full-green ci run as a result of the work that's been done to tests recently.
