### ISSUE TITLE
Reaching out to 3rd party package maintainers?

### ISSUE THREAD

**Issue by fhemberger** [nodejs/evangelism#215]
Hi, I'm not sure if this is the right place to address this, but are we in contact with and provide regular updates to 3rd party package maintainers? I know that we can't trace back every platform and every package manager, but is there an official way to keep in contact with package maintainers? This affects various *nix distributions as well …

Example: I just found out that NAS manufacturers Synology and QNAP provide Node.js packages for their platforms as well, but those are outdated/vulnerable:
- [Official package for Synology](https://www.synology.com/en-us/dsm/app_packages/Node_js): v0.12.6 (their platform only supports gcc4.7, so no v4 yet)
- [Unofficial package through synocommunity.com](https://synocommunity.com/package/node): 0.12.2
- [QNAP](https://www.qnap.com/i/en/app_center/con_show.php?op=showone&internalName=nodejs&version=0.8.22-2&down_1_name=TS-NASX86&jump_win=1): v0.8.22 :scream:

I couldn't find a contact at Synology, but two PRs are pending at SynoCommunity (https://github.com/SynoCommunity/spksrc/pull/2196 for v0.12.12 and https://github.com/SynoCommunity/spksrc/pull/2192 for v4.4.0). I also opened a ticket at QNAP (JDT-953-55144) but just got a vague answer that "it should be implemented in one of the new updates".

**Comment by mikeal** [comment]
I recall a similar thread either here or in the build repo about this. Maybe someone from @build can give us the state of this, although I don't think these package systems were ever mentioned.

**Comment by mikeal** [comment]
Whoops, should have been @nodejs/build :)

**Comment by fhemberger** [comment]
With the recent release of their DSMv6 software, Synology offers now three different (but still outdated/vulnerable) versions of Node.js:
- 0.10.41
- 0.12.9
- 4.2.6

**Comment by jbergstroem** [comment]
I've previously been talking about doing this and have a list of linux distributions and packagers. Although the information is public, I haven't posted it somewhere just yet. Here's a draft email I also had in mind:

```
Hi,
I'm part of the nodejs build group (https://github.com/nodejs/build,
#node-build@freenode). The reason I'm emailing you is because
you seem to be tied to maintaining and packaging Node.js as part of a
package manager. My ambition is to better understand what problems you
might be facing packaging Node.js (if any) and also be generally around for
questions and feedback on how we can make Node.js better for your package
manager. The end goal is to make sure the user experience is as good as
possible through all channels of distribution.

We have a document that outlines different ways of installing Node.js (
https://nodejs.org/en/download/package-manager/). Are these instructions
up to date or are you perhaps missing from the list?

I'm also happy to help out should you have floating patches you want us to
help landing (both nodejs and v8 or other projects we depend on).

Would you also be interested in being part of a mailing list where we'd
send out an email on $version_bump outlining possible actions from a build
point of view? Dependencies, toolchain, abi breakages, etc.

Lets keep this short but it'd be great to hear from you - even if its just
to say you got my email. You can reach me at <redacted> or
jbergstroem@freenode.
```

Most of my work is at least 6 months old, but it should still be pretty relevant. Also, I think its time for us to treat shared builds seriously - but this is also borderline what we should be talking about here :)

I'm happy being part of an effort to improve communication with package maintainers.

**Comment by mhdawson** [comment]
Your draft email looks good to me and I'm also interested in the effort to improve communication with the package maintainers.

**Comment by fhemberger** [comment]
Ok, unofficial Synology packes will be removed, as there are new official packages for v0.10, 0.12 and 4.0. QNAP didn't seem to be interested at all (or the support didn't understand what I was talking about.

Still don't know if I should pursue this issue further. But I'd love to see package maintainers at least pushing the latest security fixes.

**Comment by jbergstroem** [comment]
@fhemberger lets keep this open. Lets work at extending the list and try to formalise the outreach. I believe a collaborative effort between the build group and evangelism is probably a good way forward. Lets have a chat on IRC or similar to see if we can come up with something.

**Comment by bnb** [comment]
@fhemberger Is there any more work to be done in this issue? Not sure if this is resolved or has more work that can be done.

**Comment by fhemberger** [comment]
@bnb Basically, I gave up on this.

- The SynoCommunity removed the node package altogether, because there's the official package.
- I tried to contact Synology, but they didn't care to answer.
- QNAP opened a ticket (March 2016), but tech support didn't at first understand, what the problem was. Then they "updated" node to v4.5.0, which is still the latest release in their app center today.

**Comment by bnb** [comment]
Thanks for the context @fhemberger. I *think* we can close this issue, unless there's something else you feel we can work on doing with Synology/QNAP. Sounds like they're pretty unresponsive, unfortunately. 😞
