### ISSUE TITLE
convince bosses and clients

### ISSUE THREAD

**Issue by vdeturckheim** [nodejs/evangelism#217]
Hi, 

I don't know if here is the right place for this. I've built [a presentation](https://blog.steamulo.com/node-js-convince-boss-and-clients-832b5cba2a7d#.h1tw0vc3p) ready to be used for convincing decision makers to go for Node.js. 

I would be happy to see this becoming part of a bigger set of resources branding Node.js.  
Do you have any comments/ideas regarding this ? 

Thanks,
Vladimir

**Comment by gtewallace** [comment]
Hi Vladimir, great minds think alike. I reviewed your presentation and I think it is very much in line with what the Node.js Foundation has just published, which you'll find here https://nodejs.org/en/foundation/case-studies/#presentation-the-enterprise-case-for-node-js

I'd like to invite you and the rest of the community to be involved in V2 of this presentation. To that end, I was thinking about closing this issue and opening a new one, which I'll point to in the Medium post we will be putting out shortly announcing the availability of V1 of the presentation.

LMK thoughts. 

Thanks!

**Comment by vdeturckheim** [comment]
H Greg !

Excellent idea, I would be happy to take part in such a project. I have spent a lot of time evangelizing node in some companies or with some clients and I definitely feel the need for a wide strategy within the community on this topic.

I have no problem closing this issue at all :)  Just ping me in the new one please ;)
