### ISSUE TITLE
Posting markdown to Medium

### ISSUE THREAD

**Issue by mikeal** [nodejs/evangelism#218]
This might be useful for some of the stuff we're doing.

https://medium.com/@andymcfee/how-to-import-markdown-into-medium-c06dc981bd96#.yla2vo4cw

**Comment by bnb** [comment]
Shared this in https://github.com/nodejs/nodejs-collection/issues/8, going to close discussion with preference for that one as a central place for the Node.js Collection Medium Publication discussions.
