### ISSUE TITLE
What would you like to see at Node.js Interactive 2016?

### ISSUE THREAD

**Issue by mikeal** [nodejs/evangelism#219]
Kicking off a thread here to get people's feedback on what kinds of talks they'd like to see at Node.js Interactive 2016 in Amsterdam and Austin.

The CFP is open for both events so if you're interested, submit a talk ;)

/cc @nodejs/node @nodejs/website @nodejs/build @nodejs/benchmarking

**Comment by riclf** [comment]
Well, as a lone developer I will not be able to afford to go to either venue of Node.js Interactive 2016. That frustrates me. These events are priced for Enterprise payment, not lone developers on a shoestring.

However, I will contribute what I would like to see & hear:  There is a time in development when you have too move your node app off the local network and get it running in a public cloud environment. But testing is not done, debugging is not done. And you are basically reduced to hammer, stones, and blind changes for tools behind the cloth called the cloud. Yet StrongLoop of IBM took control of an invaluable npm module tool called node-inspector which gives you the eyes and ears you need to fully debug a complex Node App. But it has never been documented as to how to run it in the cloud. The details are the issues. The concept is easily understood but when to do install it globally in the cloud. To get it running is a bear. So far, a bear that I have not successfully conquered. It just fails to appear in the local Chrome browser.  In my case, my environment is OpenShift at Redhat. I have queried blogs, StackOverflow, OpenShift IRC, Red Hat Support, various dev sites, many places. No pleasure. How about roping in a smart Red Hat OpenShift gal or guy and have them give a talk on specifically how its done. Then please, in kindness, send me a link here to the video recording!  Thanks. Have a great conference.

**Comment by zeke** [comment]
@mikeal can you add URLs to the opening comment for context? I don't know about these events.

**Comment by fhemberger** [comment]
@zeke 
http://events.linuxfoundation.org/events/node-interactive
http://events.linuxfoundation.org/events/node-interactive-europe

**Comment by stevemao** [comment]
@zeke They are on the bottom of the nodejs website https://nodejs.org/en/

**Comment by mikeal** [comment]
> These events are priced for Enterprise payment, not lone developers on a shoestring.

Super Early bird pricing was $250 which is quite low, even by community conference standards. The foundation is also doing smaller local events, http://live.nodejs.org/, which are mostly free.

**Comment by Chris911** [comment]
Submitted a talk for the first time! Would like the opportunity to do a 5 minute fire talk like we had at the end of the conference last year. 

And to answer the original question; more talks on performance improvement. Not only micro optimizations but how to find improvements in already existing big scale Node applications.

**Comment by jfathman** [comment]
- Node internals (could be a conference day zero, or separate track)
- Node API (structure, intrinsic capabilities sans third party modules)
- presenters from Google V8 team, Microsoft ChakraCore team, libuv team
- impact of ES6 (ES7), including prospect of displacing popular legacy modules
- TypeScript as primary Node language (independent of Angular or other front-end)
- ESLint
- Redux
- IoT (as much as possible, full separate track)
- serverless computing
- nats.io as message bus for Node apps on IoT and in cloud
- Docker, including logging and monitoring options for Node
- container orchestration for small-scale enterprise apps (not cloud service provider)
- Alpine Linux (Node considerations)
- using Ansible to deploy Node apps in a Docker environment
- commonly used and overlooked npm commands
- Node compatibility in new Linux subsystem in Windows 10
- Node Certification curriculum
- day in the life of a Node core contributor

And be sure to provide attendees with Node Interactive conference stickers!

**Comment by sejoker** [comment]
- Node Next (future API, breaking changes)
- Docker (official images, best practices, use cases)
- Serverless architectures with Node.js
- NPM (v3, security, performance)
- Node foundation (working groups, OSS processes, policies)

**Comment by Trott** [comment]
This issue can probably be closed at this point. But I'll re-animate it long enough to point out that the event is being referred to on the Linux Foundation website as both "Node Interactive North America" and "Node Interactive US". I have a preference for "North America"/"NA"  over "US" myself, but even more than that, I have a preference for picking one and sticking with it. :-D /cc @mikeal 

Specifically: [This page](http://events.linuxfoundation.org/events/node-interactive) uses "US" in the text but "North America" in the title (so that shows up in Google search results and browser tab titles).

OK, now that that's said, I'm going to close this issue. Comment or re-open if you think it should be open for some reason.

**Comment by williamkapke** [comment]
@Trott That is a good point and I agree. I'll forward this on to the Foundation.

**Comment by williamkapke** [comment]
@Trott Check Can you review again? It has been updated. Let me know if you find anything that was missed.

**Comment by Trott** [comment]
@williamkapke Thanks. Quick look seems good to me.
