### ISSUE TITLE
Evangelism: Weekly Update for April ~

### ISSUE THREAD

**Issue by JungMinu** [nodejs/evangelism#220]
Let's write down for next week :gift:

**Comment by gergelyke** [comment]
maybe it would worth mentioning our NodeHero series, you can find the first chapter here: https://blog.risingstack.com/node-hero-tutorial-getting-started-with-node-js/

we have just released the 5th one, but they will keep coming on a weekly basis.

**Comment by JungMinu** [comment]
@gergelyke  a PR for this weekly update: https://github.com/nodejs/nodejs.org/pull/700

**Comment by gergelyke** [comment]
great, thanks @JungMinu !
