### ISSUE TITLE
Node.js event reports

### ISSUE THREAD

**Issue by thefourtheye** [nodejs/evangelism#222]
Can we use this issues section to publish short reports on Node.js events conducted?

For example, we had our first meetup in Chennai (Tamilnadu, India) today, where many people who were new to Node.js attended. I would like to have more people know about events like this and love to see more participation from people in and around Chennai. That is why I was thinking about publishing a report here.

Is this okay?

**Comment by thefourtheye** [comment]
cc @nodejs/evangelism

**Comment by Knighton910** [comment]
+1 `@thefourtheye`

> Can we use this issues section to publish short reports on Node.js events conducted?

## 

SGTM  🎱

**Comment by mikeal** [comment]
So, we should definitely do all that we can to bring visibility to these reports (social media, weekly update blog, etc). All I'm wondering is if it is better to have these _live_ here or on something that is owned/controlled by your local meetup? I don't have an opinion about either, and I think this group and the foundation should help enable which ever route is best.

**Comment by thefourtheye** [comment]
@mikeal The meetup has no page on its own to present the reports. I can post it in the comments section of the meetup, but I am afraid it will not reach more people :(

**Comment by mikeal** [comment]
in that case, feel free to post it here :)

**Comment by thefourtheye** [comment]
Thanks @mikeal :-) #224 I am thinking about asking the community members itself to help create a site for Chennai Node.js, with Node.js.

**Comment by bnb** [comment]
Going to close this due to inactivity in the issue. Please, feel free to create a new issue or request this one be re-opened if needed. ❤️
