### ISSUE TITLE
Event Report for Chennai Node.js Meetup's first meeting

### ISSUE THREAD

**Issue by thefourtheye** [nodejs/evangelism#224]
Today (4<sup>th</sup> of May, 2016) Chennai saw first of its Node.js meetup's ([Twitter](https://twitter.com/Nodejs_chennai/), [Facebook](https://www.facebook.com/groups/598340823665660/)) first meeting. The actual invitation can be found here. http://www.meetup.com/nodejs-Chennai/events/230456256/. 81 people RSVPed for the event and around 50 managed to attend. The event happened in PayPal IDC, Chennai.

Speaker: Arunkumar Elengovan
Title: Introduction to Node.js and npm

Summary of topics discussed:
- What Node.js actually is
- Brief History of Node.js
- About Node.js and Node.js Foundation
- Event Loop and Asynchronicity
- Introduction to NPM
- Semantic Versioning
- Demos
  - Reading a file - Synchronously and Asynchronously
  - Error handling in Sync and Async code
  - Creating a simple HTTP server with express.js
- Hands on
  - The attendees had a hands on session creating a simple HTTP server with express.js, which can accept inputs as query strings.
- Introduction to good-first-contribution tag in node repository.
  - many people were interested to know how they can contribute to Node.js. So I opened our issues page and showed them the good-first-contribution tag and explained about our contribution guidelines.

Attendees who were totally new (not anymore!) to the Node.js, were helped during the session to get it installed in their computers and the environment setup.

Thanks @Yoda-The-master and @abhas9 for helping me organize this event :-)

**Comment by Knighton910** [comment]
+1

**Comment by bnb** [comment]
Thanks for posting this update - ideally we'll use this information in the future! Closing for now. ❤️
