### ISSUE TITLE
NodeConfEU 2016

### ISSUE THREAD

**Issue by leannevau** [nodejs/evangelism#228]
This year's event will be hosted at the Lyrath Estate, Kilkenny from October 16th-20th. Now currently in the process of CFP until 24th June. http://www.nodeconf.eu/

**Comment by bnb** [comment]
@JungMinu Hey - is this something that we might put in our weekly update at this point? Perhaps for October?

**Comment by JungMinu** [comment]
@bnb yep :)

**Comment by bnb** [comment]
@JungMinu It finished on the 19th. 🙂
