### ISSUE TITLE
assistance with a slide

### ISSUE THREAD

**Issue by gtewallace** [nodejs/evangelism#229]
I'm working with Node,js Foundation members on a presentation called "Selling Node.js in Your Enterprise."

The intended audience is Node.js developers at enterprises that could be using more Node.js. The goal is to equip these Node.js champions with the basic arguments and data they need to "sell" Node.js to their peers and management.

V1 is coming  along well, and we've already got a view to some of the improvements we want to make in future versions (for instance, adding a Developer Experience section).

To wrap up V1, there's one slide I can use some help with, and wanted to see if anyone here would be willing to assist.

I'm looking for a short summary of the performance considerations/pros and cons for single-threaded microservices architectures (like Node.js) versus multi-threaded monoliths (like Java).

I've seen a few articles on the subject, but they're kind of dated.

Here's the link to the slides - the slide in question is number 11.

https://docs.google.com/presentation/d/1KdYniohBE_APp8ngD_TTE0-Hl5loxXCTnj1AnEorebc/edit?usp=sharing

Thanks in advance!

**Comment by bnb** [comment]
Hey - sorry @gtewallace for not getting back sooner. Has this been published (it looks pretty familiar - I thought I saw it about a week or two ago) or are you still looking for feedback? If you're still looking, I'd be happy to help.

**Comment by bnb** [comment]
Going to close - @gtewallace if you're still interested, feel free to re-open. ❤️
