### ISSUE TITLE
Help with content of website

### ISSUE THREAD

**Issue by rosskukulinski** [nodejs/evangelism#23]
During the @iojs/website [meeting today](https://github.com/iojs/website/issues/240), they mentioned they're looking for some help with content for the website, and are looking to us to help with that.

cc/ @therebelrobot, @snostorm, @Fishrock123

**Comment by snostorm** [comment]
Especially with WG/TC updates we'll want to coordinate closely on communicating open governance well on the website. Also how to's, case studies, etc. as the site grows.

**Comment by bnb** [comment]
Absolutely. Let me watch the video, and I'll leave a more precise comment.

**Comment by bnb** [comment]
@snostorm Could you define what your exactly talking about with WG/TC updates, and communicating open governance? 

With the WG/TC updates, are you talking about upcoming meetings, and linking to previous meetings + minutes? Or are you talking about something else? 

And with communicating open governance, were you thinking dedicated pages to talking about it, communicating it over external sites, communicating it in another internal way, or something else? 

Sorry for asking for such specific clarification, but I'd like to know exactly what you want so I can help the Evangelism WG build the proper information around it.

**Comment by snostorm** [comment]
Hi @bnb -- my statement here was intentionally a broader vision, trying not to be too specific.

The website team is here to help all WG (including evangelism) publish their projects/content/etc. and as part of that I'd like to include the ability for the TC and WGs to be able to link to their meeting summaries, videos, etc.

One of the big "wins" of the io.js experiment is how well the WG structure is working but we're not advertising that at all. What sort of content best communicates this is probably something that fits the scope of this team better. If you want us to allow for new content, we'll make it happen :)

That all said, I'm personally happy to jump in on this side and help develop the plan.

> With the WG/TC updates, are you talking about upcoming meetings, and linking to previous meetings + minutes? 

Yes. Ideally, actually, a version of the minute .md files exist in our repo which will help the i18n groups publish them as well. (Less links out.)

> And with communicating open governance, were you thinking dedicated pages to talking about it, communicating it over external sites, communicating it in another internal way, or something else?

Probably our own pages to talk about it long term. Again this helps the i18n community to then have a place to communicate the message as well.

**Comment by snostorm** [comment]
Specifically posting this separately: we are very close to having our next stage of the website build process ready which will make it easier to manage information like:
- List of past versions (to download, for Changelog, ... maybe old API docs.) I'd like the Changelog itself to be imported to the website as well, as the i18n groups are translating them anyway, this way they can be published somewhere.
- List of WGs (including TC) -- where to find them, what they do, landing page?, etc.

Some of this information is too hard to manage in the simple markdown format we have now, especially once replicated across 20+ i18n groups. The new structure for landing pages like these will be more fill-in-the-blank on top of the English i18n defaults, to make opting in to translating easier.

Although, a page like a version Changelog would still be in Markdown (as it is mostly headings/links/content.)

**Comment by bnb** [comment]
@snostorm Apologies on being completely absent and not moving forward with this for the past two (almost three) months. Has a conclusion been made in this area, or is there further work that needs to be done?

**Comment by mikeal** [comment]
We'll want to roll this in to the work on the new site.

**Comment by snostorm** [comment]
Confirming what @mikeal said. There's still an interest in expanding the content. The only thing that came to fruition on our end since was the automatic past versions page (sans in-site README links.)

See https://iojs.org/en/releases.html

Mostly these efforts now will go toward expanding the new Node.js site.

**Comment by mikeal** [comment]
the most important thing to me is a "Get Involved" section which lays out a taxonomy of the working groups and the various projects and libraries they maintain with clear directions about how to get involved with each and every one.

**Comment by bnb** [comment]
@mikeal I'm job hunting right now, but after I finish that, I can probably work on the Get Involved page/writing. At most it will be ~two weeks, but I'm very confident it will be sooner.

**Comment by bnb** [comment]
@snostorm Is this still needed?
