### ISSUE TITLE
weekly Node.js newsletter starting up again

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/evangelism#238]
Howdy lovelies! 

[Jenn Turner](https://github.com/renrutnnej)  will be picking up past efforts to do a weekly Node.js news for the Node.js Foundation, very similar to what we had prior to the Foundation coming to fruition. She writes for a number of open source projects and is an awesome friend in/of the Node.js community. 

We'd love to find a good way for folks to be able to submit news they'd like her to consider for the weekly, given that there is no guarantee it will make it in--we are trusting Jenn to curate and highlight and there's too much happening in the world to include the whole kitchen sink.

Would it be cool for me to add to the README for @nodejs/evangelism that instructs folks to submit news as a GitHub issue in this repo, and then create a label `weekly-news` for Jenn to look through?

**Comment by jennwrites** [comment]
+1 It probably goes without saying but that system works great for me. Thanks @hackygolucky 💃

**Comment by Trott** [comment]
We already have a weekly issue that opens soliciting items for the evangelism weekly thing. (See https://github.com/nodejs/evangelism/issues/237 for the current example.)  I know that there's an intention of having the community weekly thing be different from the Foundation weekly thing, but IMO that just ends up confusing people and diluting the audience for both. It would be great to see these two things not working at cross-purposes.

Using this repo for both weekly things is a good start. Eventually having just one weekly thing would be a further improvement, IMO.

**Comment by fforres** [comment]
👍  to Trott.
Diluting the efforts could be problematic... although, (And I'm guilty of this) we do not add much info to the evangelism weekly issues.

**Comment by mikeal** [comment]
These can be a complimentary effort.

Perhaps the best thing to do is just to have Jenn watch this repo so that she sees all the stuff that people are adding to the weekly blog post. That way we avoid any confusion in this repo and people also don't need to try and post twice.

**Comment by hackygolucky** [comment]
@Trott @fforres We're not trying to duplicate effort here or dilute audiences, but we've received a bunch of feedback that no one knows where to go to get a comprehensive reporting of what is happening in Node.js on a regular cadence(weekly). Are you saying there's a community newsletter that already goes out on a weekly basis that covers the ecosystem--individuals, companies, Foundation work?

Jenn is a resource being provided by the Foundation to highlight some great stuff happening around the world on a weekly basis, as the above feedback I've referenced also shared how much we're lacking in highly exposed communication mediums such as a newsletter.

**Comment by Trott** [comment]
> Are you saying there's a community newsletter that already goes out on a weekly basis that covers the ecosystem

Not exactly. Without casting any aspersions on the people who donate their time to work on it, the current community newsletter is (as far as I can tell) not very compelling. I never recommend it to people who ask about a good daily or weekly resource. Instead, I point them to [Node Weekly](http://nodeweekly.com/).

If the Foundation is putting resources towards making a great weekly newsletter, then that's awesome. I know @mikeal thinks the effort could (should?) be complimentary to that of the Evangelism WG. I'm not so sure. Regardless, there should be one way for people to submit content and they should be able to do it once. If that means having only one newsletter, then great. If that means having a shared pipeline for both newsletters, that's OK too.

I suppose a perfectly fair/acceptable approach would be to reinvigorate the Foundation effort and then evaluate the situation once that's done.

**Comment by hackygolucky** [comment]
@Trott Ah, sorry I think I misunderstood efforts to better channel how people could communicate work they'd like to share than how to share it. Did not question whether something existed. I thought there was a gap from the iojs weekly. 

I'm not trying to pass any judgement on current newsletters. I'm reflecting feedback on the discoverability which in itself is always a fun thing to address in the project regardless of what we're trying to share(definitely something I think most people can agree we need to work on). So much good stuff going on.

**Comment by Fishrock123** [comment]
cc @JungMinu

**Comment by fforres** [comment]
I'm all for improving discoverability/visibility, (it's actually one of the biggest pains we are having here in Chile) my concerns where more on the side of trying to make it a joint effort, better than splitting apart.

I'd love to help though 😄 

Maybe it's a dumb question, but Is NodeWeekly an effort from the foundation?

**Comment by bnb** [comment]
@hackygolucky: @JungMinu has been handling most of the Node.js Weekly articles. I was very involved with io.js Weekly, and would very much like to help with the new newsletter.

Definitely a _lot_ we can do to 💥 discoverability and visibility.

A few _major_ things to get discoverability going:
- Tweeting about the beginning of the effort, twice weekly reminders, and then notices when it goes out.
- Pushing info to _all_ other official Node.js social channels.
- Email signups, making it an email newsletter. I think this is your intent, but doing this will be perfect because the site isn't really a destination for content at this point.
- Also posting it to the Node.js blog.
- Having a signup form on the blog posts for it to get new additions.

Those will go far.

**Comment by bnb** [comment]
@fforres No, Node Weekly is a private newsletter by Cooper Press. https://cooperpress.com

**Comment by julianduque** [comment]
@hackygolucky an example of what is being published currently to the Node.js blog coming from this Evangelism WG: https://nodejs.org/en/blog/weekly-updates/weekly-update.2016-08-15/ 

I think keeping only one newsletter will be of value and it can be a joint effort between community and Node.js foundation

**Comment by Trott** [comment]
Not sure we want to go too far down the how-to-improve-the-existing-newsletter rabbit-hole in this issue, but one thing that often goes unmentioned but that I think is hard to overstate: The layout of the current newsletter is not (in my opinion) inviting or easy to scan. The headers are hard to distinguish from the paragraphs, etc. (I'm talking about the layout at places like https://nodejs.org/en/blog/weekly-updates/weekly-update.2016-08-15/. No idea about other places the current newsletter might be appearing.)

**Comment by bnb** [comment]
@Trott You're absolutely right. However, that's a pretty basic design and stylistic change. Here's a quick [response](https://gist.github.com/bnb/ea2b315c44ff83c14c30a39682f238a3) (definitely want to discuss), to keep this thread more clean and on topic.

**Comment by JungMinu** [comment]
I'd love to help improve `weekly Node.js newsletter`
Can we collaborate? 
I'm really interested :)

**Comment by hackygolucky** [comment]
@Trott So if I'm gathering this correctly, anyone can come in and create an issue(if it doesn't already exist for that week) to the tune of "Evangelism: Weekly Update for Month/Week(or date range)" and then people add comments? Regardless of the publication, I think it would be nice for communities to be able to highlight things happening that they'd like celebrated and/or promoted. I'd love to help encourage submissions here.

As for collaborating, we'll need to bring @renrutnnej into the conversation @JungMinu @bnb and see what also fits her working style for newsletter writing and curation(maybe we should start an email thread?). I especially think the plan for getting people back into the newsletter reading is a great idea. Zibby, who works on PR at the Node.js Foundation, is especially great at this and I'm sure she'd like these suggestions on helping spread the word(yay resources that help get this done!).

**Comment by Trott** [comment]
> @Trott So if I'm gathering this correctly, anyone can come in and create an issue(if it doesn't already exist for that week) to the tune of "Evangelism: Weekly Update for Month/Week(or date range)" and then people add comments? 

I _think_ that's correct. @JungMinu had it opening once a week automatically (probably via ifttt.com or a similar service) for a while. It is possible that a more personal touch (with a different message each week) might be more engaging and attract more people to comment/contribute. Or maybe not. Maybe that would just be more work. :-D

**Comment by jennwrites** [comment]
Hello Evangelism thread friends 👋

I’m a writing and editing consultant used to curating content on my own (for publications like [npm‘s Weekly](http://us9.campaign-archive2.com/home/?u=077dfd41302a71310cef619e5&id=e17fe5d778), the [Hoodie](http://us4.campaign-archive2.com/home/?u=12d36bbe9418ed6a43127cd62&id=664f4ce8cd) and the [Offline First](http://offlinefirst.org/news/) organization’s monthly newsletters, etc.) so I’m excited to collaborate with the Evangelism and Community teams to make this Node Foundation + Node.js community newsletter happen.

I think it would be best to same-page-ify at some point, either via email thread or video call. I’m pretty flexible in terms of workflow because I’m used to hopping in and out of teams, so moving forward I think participating in an issue, like the one demonstrated above ([#237](https://github.com/nodejs/evangelism/issues/237)) would work fine, or we could take it to weekly email thread, if need be. 

Whatever we determine, I agree that it’s important to make sure that the process is clear and encouraging to people to reach out with contributions about what’s happening in the Foundation or the wider community. ✌️
