### ISSUE TITLE
List of Plugs

### ISSUE THREAD

**Issue by dotproto** [nodejs/evangelism#24]
We should create a simple list of plugs that can be read out at the end of each TC/WG meeting.

Meeting hosts often wrap up the meeting with some basics on where we're active and how to get in contact. Unfortunately, it seems hosts aren't 100% clear what channels they should be directing people to.

**Comment by rosskukulinski** [comment]
agreed, good idea @svincent

**Comment by bnb** [comment]
+1. How many should we have, and where should we direct them? Should there be WG-specific ones, such as one for the Website WG, one for the Streams WG, one for the TC, etc.?

**Comment by yosuke-furukawa** [comment]
I guess the following TC/WG has meeting
- io.js core: they already have ical (https://github.com/iojs/io.js/issues/230#issuecomment-68507813)
- website
- streams
- build
- tracing

And i find a [similar issue](https://github.com/iojs/roadmap/issues/7).

**Comment by bnb** [comment]
@yosuke-furukawa I think that's something different than what @svincent was talking about. If I understand correctly, he want's to create a script that someone in the WG meeting can read at the end to promote a way to contribute to io.js.

**Comment by dotproto** [comment]
Right on @bnb. Perhaps @yosuke-furukawa meant to comment on iojs/website#236 ?

**Comment by yosuke-furukawa** [comment]
oops!!

I could not catch the meanings. thanks @bnb and @svincent .

**Comment by dotproto** [comment]
My main intent with this issue was to create a list of social media outlets and calls to action that meeting hosts can read out at the end of their session. It doesn't have to be complicated, just something that the host can consult and rattle off as they're wrapping up.

Here's a quick draft as an example

> - To keep up with io.js you can ...
>   - Follow us on Twitter at [official underscore iojs (official_iojs)](https://twitter.com/official_iojs)
>   - Read our weekly roundups on Medium at [medium dot com / at iojs ](https://medium.com/@iojs) (medium.com/_@_iojs)
> - If you'd like to get involved, you can check out the main issue repo at [github dot com / iojs / io dot js](https://github.com/iojs/io.js) (github.com/iojs/io.js)
> - If you'd like to help out with other parts of the project, check out our list of working groups at ???

Does this seem reasonable?

**Comment by bnb** [comment]
I think it's important to include WG-specific prompts, as people are listening mostly to WG meetings of WGs they're interested in:

> - To keep up with io.js you can ...
>   - Follow us on Twitter at official underscore iojs (official_iojs)
>   - Read our weekly roundups on Medium at medium dot com / at iojs (medium.com/@iojs)
> - If you'd like to get involved with core development, you can check out the main issue repo at github dot com / iojs / io dot js (github.com/iojs/io.js)
> - If you'd like to get involved with the `<insert WG name>` WG, you can check out our repo at github dot com / iojs / `<wg repo name>` (github.com/iojs/`<wg repo name>`)
> - If you'd like to help out with other parts of the project, check out our list of working groups in `<find a way to call out this file: https://github.com/iojs/io.js/blob/v1.x/WORKING_GROUPS.md >`

With the last point, I think it would be super helpful if someone could send iojs/io.js a PR adding more helpful links to the WORKING_GROUPS.md file for each WG. Links to include would be main repo, contributing, governance, and issues.

**Comment by blakmatrix** [comment]
@bnb

> With the last point, I think it would be super helpful if someone could send iojs/io.js a PR adding more helpful links to the WORKING_GROUPS.md file for each WG. Links to include would be main repo, contributing, governance, and issues.

I attempted to do this but it didn't seem to be the right place for it. **When you thought it'd be helpful to list out all those links, what were you specifically hoping to achieve?** I took it to be a consolidation effort for both the evangelism group and would be interested parties having ease of access to such links, but like I said it seems like that was not the right place for such consolidated list of info.

**Comment by mikeal** [comment]
I doubt the TC and WGs will be diligent about stuff like this (finishing with calls to action). I also worry about spreading the assumption that the community watches those meetings. A very small subset of the community watches those, we want to get calls to action out to the larger community we should do a better job of it in the Weekly Updates and on twitter.

**Comment by dotproto** [comment]
@mikeal Annoyingly good points :wink: In the past you've also mentioned that the TC/WGs are hesitant to add more overhead: I can't help but think trying to get them to sign off with a closing statement could be a hard sell.

I'm inclined to close out this issue unless someone raises strong objections in the next couple days.

**Comment by mikeal** [comment]
Let's close this one and start a new one for getting more calls to actions out on twitter and the updates :)
