### ISSUE TITLE
NodeConf New Zealand

### ISSUE THREAD

**Issue by faceleg** [nodejs/evangelism#245]
Who should I talk to about the possibility of New Zealand getting our own NodeConf?

**Comment by fforres** [comment]
Hi @faceleg,
That's really cool! Kudos on the initiative! 
I believe you might get more info from @mikeal (for permission and details)

**Comment by bnb** [comment]
Not quite sure about who to contact about organizing - @mikeal would _most likely_ know if there is a single person to talk to, if he's _not_ that person.

These links might be useful: 
- [NodeConf GitHub Org](https://github.com/nodeconf)
- [NodeConf Collective](https://github.com/nodeconf/collective)

Also, happy to help in any way I can.

**Comment by mikeal** [comment]
@bnb is correct, just log an issue on the NodeConf Collective GitHub and you'll get pointed at the right docs and get a subdomain :)

**Comment by bnb** [comment]
Going to close this due to inactivity in the issue. Please, feel free to create a new issue or request this one be re-opened if needed.
