### ISSUE TITLE
Add Contributor: @vdeturckheim

### ISSUE THREAD

**Issue by bnb** [nodejs/evangelism#246]
Would like to propose adding @vdeturckheim as an Evangelism WG contributor. He has been consistently engaged, even during the long lull the WG has had. He submitted an excellent roadmap for the Thread Summary Process (https://github.com/nodejs/evangelism/pull/243), and has definitely demonstrated value-added work to the WG.

**Comment by Trott** [comment]
+1

**Comment by JungMinu** [comment]
+1

**Comment by bnb** [comment]
@Trott Can we get him added to the Foundation? He's currently not a member.

**Comment by Trott** [comment]
@bnb I've invited them to join @nodejs/evangelism. If they accept the invitation, they will be added as a Foundation member (in GitHub--actual Foundation membership is ¯\_(ツ)_/¯) automatically.

**Comment by thefourtheye** [comment]
LGTM

**Comment by vdeturckheim** [comment]
Hey guys, Thanks a lot for that. I'm really excited to carry on working within this WG \o/

**Comment by bnb** [comment]
Welcome to the WG, @vdeturckheim! 🎉
