### ISSUE TITLE
Node Interactive North America 2016 Discussions

### ISSUE THREAD

**Issue by bnb** [nodejs/evangelism#250]
At Node Interactive, an issue that was brought up was the community have a bit more access to official and broad Node.js social media.

Topics discussed
* Somehow having the community being able to contribute to Node.js on Twitter/Facebook (https://github.com/nodejs/evangelism/issues/254)
* Having an official Node.js publication on Medium or process (https://github.com/nodejs/evangelism/issues/255)
* What are we doing for chat (https://github.com/nodejs/evangelism/issues/256)
* Updating the Meetup Starter Kit (https://github.com/nodejs/evangelism/issues/257)
* Consistently updating the events page and getting that published on Social Media. (https://github.com/nodejs/evangelism/issues/258)
  * Audit what's currently on the page
    * Automating event submissions
    * Event submissions
    * Working on helping meetups find speakers
* Starting an official Node.js online meetup
* Getting Foundation Board minutes published more frequently.

This was with:

@julianduque @shiya @vdeturckheim @homosaur @pchinjr @eudaimos

**Comment by eudaimos** [comment]
@bnb interested in helping the Evangelism WG

**Comment by shiya** [comment]
Tagging @Samurais who runs a large monthly Node.js meetups in Beijing, China to be aware of the discussion. Tagging @xinyu198736 who runs Node meetups in Hangzhou.

**Comment by hailiang-wang** [comment]
Thanks, @shiya. I am glad to learn more what is happening in Node.js Community here, and even glad to join the online meetups. 

I and several friends hold Node.js/JavaScript meetups monthly for one and half a year. The moments, speakers and keynotes have been upload to https://github.com/rockq-org/node-party.

It's hard to find people sharing with great node.js skills, it would be great if we have online sharing.
