### ISSUE TITLE
Connect with local/grassroots initiatives around the World

### ISSUE THREAD

**Issue by vdeturckheim** [nodejs/evangelism#251]
Let's connect with people who started Node.js related initiatives everywhere.

Please comment on this issue to volunteer to reach people in an area and I will update the main message:

Reporting method is to be decided. In the meanwhile, work can start with a draft format.
@bnb will compile the good tips on how to do this :smile:  

| Area | Assignee|
|--------|-------------|
|France| @vdeturckheim|
|Virginia (USA)| @pchinjr|
|Missouri/Illinois (USA)| @homosaur|
|Austria, Germany, Switzerland|@danielkhan|
|California (USA)|@eudaimos|
|Indonesia|@tianp|
|Colombia/SW Florida (Tampa Bay Area)|@julianduque|
|Turkey| @yasinaydin|
|Beijing|@Samurais|
|Maine (USA)|@devinivy and @carlodicelico |
|Chennai/Bangalore (India)|@thefourtheye|
|Chile|@fforres|

**Comment by pchinjr** [comment]
I'll sign up for creating connections with NodeJS folks in Virigina, USA.

**Comment by homosaur** [comment]
I can take Missouri/Illinois USA

**Comment by eudaimos** [comment]
I can attempt California :) - but I'll definitely start with SoCal

**Comment by eudaimos** [comment]
Should we use this same issue to track the audit activity or create a new Issue for that?

**Comment by danielkhan** [comment]
I can do at least Austria, Germany, Switzerland and the surroundings if needed.

**Comment by tianp** [comment]
Can't wait to help in Indonesia.

**Comment by shiya** [comment]
In China there are three bigger meetups:
Like the people I tagged in https://github.com/nodejs/evangelism/issues/250, @Samurais runs Beijing Node parties, @xinyu198736 runs node parties in Hangzhou. Both are monthly.
There is also http://nodejs.club/ which is quarterly, not sure who run it. 

I'm moving to SF from Shanghai next year. There's already a ton of activities in the bay area though.

**Comment by julianduque** [comment]
Colombia (Medellín) and SW Florida (Tampa Bay Area)

**Comment by yasinaydinnet** [comment]
I founded Node.js Istanbul Community and co-founded NodeSchool Istanbul.
Please count me in.

**Comment by hailiang-wang** [comment]
Great, I am running a small community who love Node.js and JavaScript in Beijing China. Please add me in. Thanks @shiya.

**Comment by vdeturckheim** [comment]
Everyone, thanks a lot for your enthusiasm!
@eudaimos : I belive this will only be part of the audit
@yasinaydin : I assigned you Turkey if that's ok with you ;)
@danielkhan : If you need help with the French speaking part of Switzerland, I should be able to give you a hand.

**Everyone**: I will draft a document on the repo as template for the collection.

@nodejs/evangelism what are the language elements to use when reaching people ? I was thinking of something like "We would like to create a register of local nodejs initiatives to create collaboration between the initiatives and with the Foundation".

**Comment by devinivy** [comment]
CC @carlodicelico anything we can do in Maine?

**Comment by cdcme** [comment]
@devinivy Yes, I'd love to be a part of this! Started Nodeschool in Portland, ME! 😄

**Comment by yasinaydinnet** [comment]
@vdeturckheim Thank you :) Yes, that's good.

**Comment by thefourtheye** [comment]
I run Node.js Chennai events. If needed I can help with India.

**Comment by brody2consult** [comment]
I hope to see a local group in Amsterdam. There is <https://www.meetup.com/amsnode/> but it does not seem so active. Anyone else? Is there anything I can do to help?

**Comment by homosaur** [comment]
I have a simple format I am suggesting to start out this collection effort. Please place any comments on the format in that PR: https://github.com/nodejs/evangelism/issues/261

**Comment by bnoordhuis** [comment]
@brodybits I wouldn't mind coming out to 020 every now and then to do a talk.

I'd also like to set up something in Groningen.  @3rd-Eden That's not too far from where you are, right?

**Comment by 3rd-Eden** [comment]
@bnoordhuis Correct. I'm in Groningen now as we speak. Looping @swaagie as well.

**Comment by vdeturckheim** [comment]
@homosaur thanks a lot for that. I will review it tomorrow (we had the dotjs conf in Paris today).

**Comment by vdeturckheim** [comment]
@thefourtheye maybe whole India is a bit big as a starter, what area should I assign you too in a first time ?

**Comment by vdeturckheim** [comment]
@brodybits just let me know if there is an area you are ready to cover and I'll add you to the list \o/
Thanks a lot for helping us here

**Comment by fforres** [comment]
Hello :) 

Reporting in from Chile.
We created Noders ([Noders.com](Noders.com)) and run monthly JS Meetups:
And whenever we can, bigger events. We recently had a non-profit hackaton called EventLoop [eventloop.noders.com](eventloop.noders.com)

**Comment by thefourtheye** [comment]
@vdeturckheim I tried to find Node.js communities in other parts of India. Unfortunately, I couldn't find anything. I know of Chennai's and Bangalore's communities.

**Comment by vdeturckheim** [comment]
**all**: Since #261 is merged, we can start the collection \o/

**Comment by bnb** [comment]
As a heads up, we've gone ahead and merged @homosaur's PR to start building this list!

Edit: @vdeturckheim Beat me to it 😉

You can submit PRs for your meetups following the guidelines here: https://github.com/nodejs/evangelism/tree/master/documents/local_initiatives

**Comment by iteles** [comment]
This is so great @vdeturckheim ! 🎉
