### ISSUE TITLE
Summarize and distribute efforts of other WGs

### ISSUE THREAD

**Issue by eudaimos** [nodejs/evangelism#253]
In a conversation with the Version Management ~~WG~~ Team, it was put forth that we should be involved in summarizing the work of all of the Working Groups (this week + moving forward on a regular basis) and distribute that so the community can be up to date on the latest discussions.

If there is interest from someone in the particulars, then link them to the resources where they can find those details.

**Comment by williamkapke** [comment]
<sub>** Version Management is just a Discussion Group (AKA Team) at this time</sub>

**Comment by eudaimos** [comment]
thanks @williamkapke
