### ISSUE TITLE
Working with Official Social Channels as the Evangelism WG

### ISSUE THREAD

**Issue by bnb** [nodejs/evangelism#254]
Working with the foundation on providing more community content to build longer-term engagement.

Some points:
- Use Buffer for Foundation approval, if needed.
- Channels beside twitter?
- Help define a consistent voice for the official channels 
- Others?

Ref: https://github.com/nodejs/evangelism/issues/250

**Comment by mikeal** [comment]
We've actually grown a pretty sizable audience on Medium as well.

**Comment by vdeturckheim** [comment]
@mikeal one of the ideas of the WG would be to have a "Node.js" publication (#255) mixed with the Node.js medium account.

**Comment by bnb** [comment]
Just wanted to give an update on this: We launched the Node.js Collection Medium Publication earlier this year, and have now [developed a team](https://github.com/nodejs/nodejs-collection) for it under the Community Committee. 

Huge win for Evangelism 💥
