### ISSUE TITLE
Working on a Public Forum for Chat

### ISSUE THREAD

**Issue by bnb** [nodejs/evangelism#256]
Having a centralized, official community forum for instant chat. This is something that would be helpful long-term for communication and for monitoring.

- Slack - historically limited, based on free tier. 
  - Solution: IRC bot for listening to history and logging.
- Discord: free, open registration (signup with link)
- Others?

Ref: https://github.com/nodejs/evangelism/issues/250

**Comment by julianduque** [comment]
I would be interested in helping in this area

**Comment by yasinaydinnet** [comment]
What about http://www.discourse.org/ ?

**Comment by bnb** [comment]
@yasinaydin I like Discourse a lot - only hard part is that it either needs to be hosted and maintained, or purchased. Would love to hear any ideas on how we can make this easily sustainable for the project.

**Comment by vdeturckheim** [comment]
Could we try Slack + http://slackarchive.io/ ? Or should we develop our own bot ?

**Comment by julianduque** [comment]
The only limitation of Slack is logging, but is the same for IRC, we can have our own bot storing logs to http://logs.nodejs.org/channels

**Comment by fforres** [comment]
Is gitter not al option? 
https://gitter.im/

**Comment by vdeturckheim** [comment]
We have a gitter room, however there is no (AFAIK) moderation possible there.

**Comment by bnoordhuis** [comment]
Not that I ever visit it but isn't that what #node.js is for?  Yet another channel when IRC, SO, nodejs/help and the mailing list already exist just leads to more fragmentation.

**Comment by MylesBorins** [comment]
two things to keep in mind here

first is moderation. how will this channel be moderated  and who will be moderating 

second is buy in. there is an established chat on irc for both support and development. I think you will find push back from a good chunk of the core team with moving to a closed platform like slack. 

the biggest question I have is what is the goal here? to me I think we should work on better supporting the currently managed channels and increasing visibility.

**Comment by bnb** [comment]
I believe this has been discussed at length in the Community Committee (ref: https://github.com/nodejs/community-committee/issues/11) and can be closed. If the issue _does_ need further discussion, please don't hesitate to create a new issue or re-open this one with the context of https://github.com/nodejs/community-committee/issues/11 in mind.
