### ISSUE TITLE
Update the Meetup Starter Kit

### ISSUE THREAD

**Issue by bnb** [nodejs/evangelism#257]
Reworking the Meetup Starter Kit would be ideal.

Actually having a group of people to discuss starting a meetup and working on helping get others up and running with a new or existing meetup.

Ref: https://github.com/nodejs/evangelism/issues/250

**Comment by eudaimos** [comment]
@bnb should we close #162 now that this has been opened?

**Comment by bnb** [comment]
@eudaimos Yes, I think we're good to close this. 👍

**Comment by bnb** [comment]
Misunderstood 😅 

I think this is a good launchpad to start a round two on the Meetup Starter Kit. Closing #162.

**Comment by Eomm** [comment]
Hi,
I have almost finished to read the #162 discussion and also the actual Starter Kit.

What do you think should be added to the starter kit?

I'm thinking about some practical resources like:
+ link to node.js logo or an standard meetup image generator (like a TED<sup><small><sup>X</small></sup>)
+ right hashtag to use during the claim before the event
+ how to contact node.js to put a tweet on the official account
+ a practical cheklist split by category (questions to sponsor, CFP, speaker etc..) I think [this comment](https://github.com/nodejs/evangelism/issues/162#issuecomment-146919597) is very complete

Do you agree or I'm missing the point? 

If we define what should be added and update I could work on it 😃
