### ISSUE TITLE
Discussing the Events Page on the Website

### ISSUE THREAD

**Issue by bnb** [nodejs/evangelism#258]
The events page is a huge topic. It hasn't been updated in quite a while, and definitely needs auditing. It may just be best to rework the entire page, or move it to a subdomain.

Some issues:

* Consistently updating the events page and getting that published on Social Media.
  * Audit what's currently on the page
  * Automating event submissions
    * Google Forms and pull from Spreadsheet
  * Event submissions

Ref: https://github.com/nodejs/evangelism/issues/250

**Comment by bint** [comment]
Hello, I would like to asisst with this. Im somewhat new around here and am looking to be more actively involved. Thank you!

**Comment by Trott** [comment]
I don't think this is an issue anymore. The events page was removed in August.

**Comment by Trott** [comment]
Closing, but thanks for wanting to help @bint! Hope you find something good to work on! If you have trouble finding a good first issue, check out nodetodo.org.
