### ISSUE TITLE
Little help offer

### ISSUE THREAD

**Issue by yasinaydinnet** [nodejs/evangelism#260]
Hi.
I'm Yasin. I'm currently living in Istanbul, Turkey. I guess the person who adversises, promotes and teaches most about Node.js in Istanbul is me.

* I have a project to promote and get everything about Node.js together in a one, giant but very-well organized and very easy-to-use website/portal.
* I'm also organizing NodeSchool events here, most of the time by myself only, which 100 to 200 people attend every workshop.

So, I'm new and just started following the issues & pr's a while ago but I definetely would like to help & join Evangelism WG.

What can I do for Node.js or help with?

**Comment by homosaur** [comment]
Hey @yasinaydin, sounds like you're already running an evangelism branch by yourself with 100-200 people, wow! That's awesome to hear that your NodeSchool event is so successful, part of what we're trying to do in organizing this data centrally is maybe getting someone to help you out with a project like that. That cannot be easy to try to tutor that many alone.

A few old and new folks interested in Evangelism WG met for awhile at Node Interactive North America and there's a thread #250 detailing some of the current efforts. Pop in there and see if there's anything you're interested in. If not, feel free to make suggestions in there. It's a discussion started at NINA but it's a good hub for "new business" as it were. Thanks for your interest!

**Comment by mikeal** [comment]
@yasinaydin do you have a link to your project? It sounds really cool :)

**Comment by yasinaydinnet** [comment]
It's still in very early stage but the links & the sources could be found at:
* https://github.com/nodeist
* https://github.com/ogreogre/links-computing/tree/master/Node.js
I was inspired by Australian's community website

**Comment by bnb** [comment]
@yasinaydin Hey there. Doing some basic clean up of this repository, and came across this issue again - wanted to reach out and see if you're still interested in contributing and helping out. We just moved under the Node.js Community Committee, and should be able to get a little more velocity now. I'm working on making this repository a bit more active and beginner-friendly - so, there are several issues marked as ["Good First Contribution"](https://github.com/nodejs/evangelism/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+contribution%22) that could use some help and are a good first contribution to the Evangelism WG. Additionally, if there's an idea you've got don't hesitate to create an issue for it and we can discuss from there 💥

**Comment by yasinaydinnet** [comment]
Hey @bnb 
Yes I am still interested in helping out! In the meantime I have moved from Istanbul to Tallinn, Estonia and will start doing some missionary work to create Node.js community in this city.
I can't find as much as I could in the past but still can do some basic tasks to start for now.

**Comment by bnb** [comment]
@yasinaydin Awesome. There are now several files marked with ["Good First Contribution"](https://github.com/nodejs/evangelism/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+contribution%22) that are a good place to start 😄
