### ISSUE TITLE
Evangelism: Weekly Update for December~

### ISSUE THREAD

**Issue by JungMinu** [nodejs/evangelism#262]
Let's write down for next week :gift:

**Comment by rosskukulinski** [comment]
We should be sure to include #263 in the next few weekly updates

**Comment by vsemozhetbyt** [comment]
[V8 ❤️ Node.js](http://v8project.blogspot.com/2016/12/v8-nodejs.html) by @fhinkel on v8 blog,

**Comment by mikeal** [comment]
@vsemozhetbyt awesome post!

**Comment by vsemozhetbyt** [comment]
Yeah, kudos to @fhinkel and others for all the efforts.
