### ISSUE TITLE
Help in Promoting our Node.js Foundation survey

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/evangelism#263]
Howdy! The Node.js Foundation launched a second user survey to learn more about how developers are using Node.js. We would love this groups help in promoting the survey. 

You can find details on the survey in this blog post: https://medium.com/@nodejs/have-some-time-mind-telling-us-how-you-are-using-node-js-dbd8bcd67b42#.nts8mmikj.

I have suggested social posts below to make this lift as easy as possible. Also, let @gtewallace or me know if you have any questions on this. The data will be made publicly available for free, early next year.

**Social Posts**
The @nodejs Foundation launched its second user survey. If you have time and work with Node.js, fill it out here: http://svy.mk/2gJira0

The @nodejs Foundation wants to get a better understanding of how people use Node.js. Do you use the platform? Have an opinion to share? Survey here: http://svy.mk/2gJira0

The Node.js Foundation is interested in better understanding how people use Node.js. If you are using the platform, please fill out the survey here http://svy.mk/2gJira0

**Comment by fforres** [comment]
Done (in a bunch of communities). Hopefully we can get more people to answer it.

Is it too late to make some suggestions I guess?

**Comment by ZibbyKeaton** [comment]
Awesome and thank you @fforres! It's too late to make suggestions to this survey, but we are trying to run this survey every year and we might do a few more this year TBD. My colleagues @hackygolucky and @gtewallace pull most of the content together on this based on feedback from the community, Node.js members, general trends that they are seeing. Maybe you can sync up with them with suggestions for next year's survey.

**Comment by bnb** [comment]
@ZibbyKeaton Going to close this, as it seems the survey is over. Thanks for sharing with us - absolutely ecstatic that the Marketing people from the Foundation reaching over to the Evangelism WG now.

🙏
