### ISSUE TITLE
Evangelism: Weekly Update for January

### ISSUE THREAD

**Issue by JungMinu** [nodejs/evangelism#269]
Let's write down for next week :gift:

**Comment by bnb** [comment]
We at NodeSource released the Node by Numbers for 2016 - you can find it here: https://nodesource.com/node-by-numbers

**Comment by JungMinu** [comment]
@bnb thanks, opened a PR: https://github.com/nodejs/nodejs.org/pull/1135

**Comment by bnb** [comment]
Was merged - closing ❤️
