### ISSUE TITLE
Becoming and NF Individual Membership Director - deadline to submit is soon!

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/evangelism#270]
Hey All - As most of you know, we opened up nominations for the next Node.js Foundation individual membership director during Node.js Interactive in Austin. The deadline to submit closes soon (this Sunday; January 15). We are trying to do a big last push to make sure people know about the election and submit themselves, if they think they are qualified. 

If anyone in this groups has the time, please help us promote or apply! I have a few suggested social posts below - feel free to use if that's easiest for you. Thanks for your help here!

Want to have a voice on the Node.js Foundation board of directors? Submit your application by January 15 http://bit.ly/2hihYxR

Deadline to submit yourself to sit on the Node.js Foundation board closes on January 15. Details on the position 👉 http://bit.ly/2iGF5QO

**Comment by bnb** [comment]
Closing, as the election is over. Thanks, @ZibbyKeaton!
