### ISSUE TITLE
Speaker Request (German)

### ISSUE THREAD

**Issue by danielkhan** [nodejs/evangelism#274]
My company is setting up a conference in Linz/Austria and we are looking for a speaker. Preferably some known figure in the space that - and that is the hard part - speaks German.

Any ideas?

**Comment by vdeturckheim** [comment]
Sadly I have not spoken German in 7 years ^^

**Comment by danielkhan** [comment]
I never spoke French, so .. ;)

**Comment by Trott** [comment]
I don't know if they'd be interested in speaking or not, but we definitely have some prominent contributors who are fluent in German. addaleax and fhinkel are the first two that come to mind for me, but there are no doubt others. Even if those two are not interested, they can *probably* direct you to someone who may be.

Perhaps reaching out to the Script'17 organizers might give you some ideas too. https://scriptconf.org/

**Comment by bnb** [comment]
Additionally, @thlorenz is likely a good candidate. 👍

**Comment by danielkhan** [comment]
Yes @fhinkel came to my mind soon after I posted this. Already contacted her. She was just in Linz at scriptconf though.
I'm in touch with the scriptconf folks. In fact one is a coworker. Austria is small, Linz even smaller.
