### ISSUE TITLE
Help with promoting Node.js Interactive Europe Videos

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/evangelism#275]
Hope you are all doing really well. We conducted a series of videos at Node.js Interactive Europe on how folks are using Node.js and how it helps businesses.

The videos are now live and can be found here:https://www.youtube.com/playlist?list=PLfMzBWSH11xYieEIRBxmG4NGJKsv8MLMb. We encourage you all to share these videos on your social channels. 

We will be releasing a blog every week around the videos - some are coupled with other videos others are standalone on a specific topic. 

This week's blog focuses on how developers are using Node.js and the benefits that it provides to an enterprise; the blog is titled, "Why Developers and Enterprises Heart Node.js." Blog can be found here: https://medium.com/@nodejs/why-developers-and-enterprises-heart-node-js-e26afd2f30c8#.oindl8y01

To make it an easy lift, I've included a few suggested social posts on the playlist and blog below - if you want to share :) Thanks!

**Suggested Social Posts**
**Playlist**
A great series of videos about how people are using Node.js (whether its for robotics, web dev or with containers) http://bit.ly/2k5WO4v

**Blog Post**
Why developers and enterprises love @nodejs http://bit.ly/2kiag6F

From changing developer culture to its open source community, here are a few reasons why people love Node.js: http://bit.ly/2kiag6F

**Comment by fforres** [comment]
Wow, this are really cool.
Great work mate, will add them to our newsletter and coms for sure 👍

**Comment by davidfekke** [comment]
Shared it yesterday on our twitter account, @jaxnode. Thanks
