### ISSUE TITLE
Updating the Node.js Wikipedia Page

### ISSUE THREAD

**Issue by bnb** [nodejs/evangelism#276]
As noted in https://github.com/nodejs/evangelism/issues/102, the Wikipedia page for Node.js is _sorely_ out of date.

There are a suite of updates that need to be addressed - I've collected some ideas and suggestions here. If you're interested in contributing to this, feel free to either just update the Wikipedia page yourself *and/or* comment in this issue to discuss updates and edits.

# The Updates

Running over the Node.js Wikipedia page, here are some of the things I've noticed need to be added or updated: 

* Updating the introduction to be less dense, have with more relevant information.
* Fleshing out the history section - it's outrageously brief, and could use a hefty dose of information. Additionally, the last real historical _update_ was io.js > v4 and the Foundation formation - we've developed an amazing history since that point!
* Update the "Overview" to be more of an overview of what Node.js _is_, compared to what it _was thought to be_. 

## Examples of what needs to be updated:
Second paragraph of the introduction:
>  These design choices aim to optimize throughput and scalability in Web applications with many input/output operations, as well as for real-time Web applications (e.g., real-time communication programs and browser games).[5]

The last entry from "History":
> In September 2015, Node.js v0.12 and io.js v3.3 were merged back together into Node v4.0.[40] This brought V8 ES6 features into Node.js, and a long-term support release cycle.[41] As of 2016, the io.js website recommends that developers switch back to Node.js and that no further releases of io.js are planned due to the merger.[42]

The beginning of the "Overview": 
> Node.js allows the creation of Web servers and networking tools using JavaScript and a collection of "modules" that handle various core functionality.

## Examples of things missing:
* Information (a section) about the Node.js Foundation
  * Foundation Members
* Information about the variety of uses for Node.js
* Information about the TSC
* Information about the CTC
* Information about the Foundation Board of Directors
* Information about the LTS release cycle
* Information about Security Releases
* Information about the surrounding community
* Information about Node Interactive
* Information about Code & Learn
* Information about Node Live
* Information about the history of releases
* Other?

**Comment by vdeturckheim** [comment]
Huge :+1: here.

**Comment by bnb** [comment]
@vdeturckheim Awesome - definitely want to get this rolling! 

I'm going to request that anyone in @nodejs/evangelism and other WGs note their interest in participating by the 15th of February, so we can move forward with planning the meeting. 🙌

**Comment by bnb** [comment]
Okay, @vdeturckheim, looks like we should plan a meeting time 👍 

Will also need to co-ordinate to see when there won't be a collision with another WG's usage of the Node.js YouTube channel for streaming it. Not quite sure who to contact about that. 🤔

**Comment by vdeturckheim** [comment]
@bnb the Wikipedia task force is up ;) When is a good date for you ? Does Tuesday 28th work for you ?

I have no idea how the nodejs youtube channel works however.

**Comment by homosaur** [comment]
I am available to help quite a bit next week

**Comment by bnb** [comment]
Totally missed the ball on catching up on this - I can't believe it's been 7 days already 😬

@vdeturckheim @homosaur Let me know a day this week that works for you, if one still does? I can be available at any time but 1pm-2pm ET tomorrow (Wednesday), 2-3pm ET + after 6pm ET on Thursday.

**Comment by vdeturckheim** [comment]
No worries, I'll probably won't be available until next week. is there a day working for you ?

**Comment by homosaur** [comment]
@bnb If I'm available it would be Friday after 5 or any time Sat., but I'll have to get back to you tomorrow afternoon as I might be leaving town

**Comment by homosaur** [comment]
I have already started on a bit of editing, adding a "releases" section

**Comment by homosaur** [comment]
Also added a very basic section on governance. Could use a mention of Node Interactive here

**Comment by bnb** [comment]
Updated this issue a bit and removed references to being a meeting. For logging, here's the content I removed from the OP: 

>Updating the entire page as an individual is a *lot* of work - too much, honestly, to be taken on. I've been thinking about this, and one way that we could solve the burden of it would be to collaboratively edit the Wikipedia page on a Hangout - we can use a Hangouts on Air, streamed to the Node.js YouTube channel.
>
>It would be great to see the availability of @nodejs/evangelism team members, and try to fit in a time when we can work together on this. Additionally, I don't think there would be any problem with having members of other WGs participate - it would actually increase the accuracy and speed of the update.

**Comment by davidfekke** [comment]
Do we have proposed meeting time?

**Comment by bnb** [comment]
@davidfekke We did originally, but it was ~6 months ago. This is still important work that we can and should meet for - happy to get one going, if you're interested.
