### ISSUE TITLE
Evangelism: Weekly Update for February

### ISSUE THREAD

**Issue by JungMinu** [nodejs/evangelism#277]
Let's write down for next week :gift:

**Comment by mhdawson** [comment]
https://developer.ibm.com/node/2017/02/03/improved-testing-for-node-js-problem-investigation-tool/

**Comment by mhdawson** [comment]
I see it already went out last week so removing.

**Comment by mhdawson** [comment]
Not sure if there should be a new issue for March but here are a few recent blogs that might be of interest:
https://developer.ibm.com/node/2017/03/07/node-js-vm-summit-moving-forward-with-n-api/
https://developer.ibm.com/node/2017/03/06/not-misuse-node_modules-project-workspace/
https://developer.ibm.com/node/2017/03/02/extend-nodes-built-ca-certificate-store-using-node_extra_ca_certs/

**Comment by mhdawson** [comment]
Not sure if this is still active but:

https://developer.ibm.com/node/2017/04/20/keeping-node-js-core-small/

**Comment by Trott** [comment]
> Not sure if this is still active but:

I don't think it is. @ZibbyKeaton seems to be curating stuff now such as seen in https://github.com/nodejs/evangelism/issues/289 and @renrutnnej curates stuff for the email that goes out every Tuesday.
