### ISSUE TITLE
Launching Soon: The Node.js Collection (Looking for support from EWG)

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/evangelism#278]
A few members of the evangelism working group recently reached out the the Node.js Foundation communications team to figure out how we could work together to incorporate more community-generated content across Node.js Foundation social channels. 

We came to the conclusion that a Node.js Medium publication could be a perfect fit for this. The content on this channel will be curated by the Node.js Foundation communications team and the evangelism working group. The publication will be called "The Node.js Collection." 

We plan to launch the publication tomorrow. I will share the link s soon as it is live.
 
Included below are suggested submission guidelines, a workflow overview and details on how we hope to work together on the Node.js Collective.  

Ping me if you have any thoughts. We are very open to feedback and iterating as we go to accommodate new ideas and improvements. We are looking to have this group be actively involved in editing the publication. 

**Purpose of Node.js Foundation Medium publication**
The Node.js Foundation’s new Medium publication serves as a channel for the community to broadcast to a wide audience its views related to Node.js and its ecosystem. This may include:

- Summaries of incubated projects or technical decisions made
- Working project initiatives
- Use cases and success stories
- Industry insights and best practices around Node.js and development trends (see topic areas below)
- Reports on Node.js and JavaScript events (these events must have a code of conduct to be considered)
- Other topics will certainly be considered, but it should be something of interest to the Node.js community

**Quality**
We are looking for posts that teach and provide value to our community. Contributions should include the meta-narrative that “Node.js is maturing and gaining widespread use in mainstream enterprises, while continuing  to inspire amazing potential and creativity among the massive community using the platform.” Sub-domains and topics for the Medium page include:

- Serverless/Cloud
- Containers
- Community
- Best Practices (How To)
- Embedded/IoT
- AI/Mobile
- More (Essentially news from the Foundation and potentially more editorial style content about the future of Node.js Core) - see Google Cloud Platform’s More section as an example [here](https://cloudplatform.googleblog.com).

**Guidelines/General Tips of Submissions**

- Posts from members and community members must be vendor neutral, though they may mention vendors involved in specific project deployments if this serves the purpose of educating readers. 

- Posts about hosting of an in-person event or speaking at an event, or other indications of meaningful participation in the community, are allowed, but again shouldn’t feel like an advertisement for your services or company. 

- Your post must be your original content, but can be published on the Node.js Foundation Medium publication, if you received permission from the editors of the website to do so.  

- All content should have a byline (preferably by a company engineer) and be published with Creative Commons with Attribution, so you’re welcome to republish on your blog.

- The most interesting posts are ones that teach or explain how to do something in a way maybe others haven’t thought of. Good blog posts show hurdles that were encountered and explain how they were overcome (not that everything is rainbows and unicorns). 

- A few posts that have performed well on the Node.js Foundation Medium page include Walmart Strives to be an Online Retailer with Node.js (use case); Node.js Transitions to LTS (news); The Progress of Node.js Post io.js and Node.js merger (progress update).

- When showing upstreaming of a patch fixing an issue for others, link back to the Github issue so readers can follow along. 

- We don’t avoid critical commentary or broad issues, but approach them with sensitivity, professionalism and tact in a way that is beneficial and positive for the community. 

- Node.js Foundation Medium posts should be no longer than 1,000 words and no shorter than 300 words. 
Diagrams or photos are strongly encouraged. 

**How to submit for consideration**

- Please submit a brief summary and the topic of the post to medium@nodejs.org for consideration. The email alias reaches the review team consisting of Zibby Keaton, Sarah Conway, Tracy Hinds, Mikeal Rogers, Tierney Coren, Ross Kukulinski (with the potential to expand in the future).

- Members of the Node.js Evangelism Working Group and Node.js Foundation PR team will review your submission in an a timely manner and provide the green light to draft the entire article or provide feedback or direction. 

- If you are submitting an article or presentation that already exists, please send it in its entirety with a note on the expressed permission to publish from the owner of content.

- Once your submission has been approved, it will be added to the Node.js Foundation Medium publication publishing calendar and a publish date will be provided, so you may plan to promote accordingly through your personal and company’s social media channels. 

**Review Process for Original Posts**

- The review team will provide comments and edits. 

- Once the review team has made suggested edits, the post will be shared with the full evangelism working group, which will be given three days to provide additional edits/comments.

- The review team will share all suggested edits with the author, who has final sign off on content.  
- Zibby Keaton will then post to the Node.js Foundation Medium publication.

- The review process may take between two to three weeks depending on the number of edits and revisions involved. 

**Review Process for Created Medium Posts**

- Members from the evangelism working group are invited to become editors on Medium. If interested, contact Zibby Keaton here: zkeaton@linuxfoundation.org.

- Editors are allowed to request to put already available public content on the Node.js Foundation Medium publication if they follow the above guidelines.

**Comment by ZibbyKeaton** [comment]
@nexxylove @julian_duque @yosuke-furukawa @subfuzion @Gioyik @jmwsoft @Trott @poledesfetes
@dkhan - hey all: would you like to be added as editors and writers to the new publication? I'm just getting stuff organized on it now and would love to add anyone from this group to the mix, if you are interested. Please see guidelines of what we are looking for above and happy to answer any questions on the process, etc.

**Comment by vdeturckheim** [comment]
@ZibbyKeaton (I'm @poledesfetes ;) ). Yes I do, but I need to take some time to properly read the whole issue here, planned on this week-end ;)

**Comment by ZibbyKeaton** [comment]
@vdeturckheim I will add you. Yes, read though it this weekend and let me know if you have any questions. It's still a work in progress, but I good start.

**Comment by vdeturckheim** [comment]
but I'm @vdeturckheim on medium :p (I know, I'm terrible)
Thanks a lot.

**Comment by ZibbyKeaton** [comment]
The publication is officially launched. Check it out here: https://medium.com/the-node-js-collection/introducing-the-node-js-collection-4d0d60e72a64#.n0mj043wz

**Comment by vdeturckheim** [comment]
So lgtm, it is a great project. :D

**Comment by fforres** [comment]
Looks awesome!
Would love to contribute.

Quick question though, will we mainly focus on english based publications?
There's a big amount of non-english-speakers users, and I know some people that would love to contribute but can see language as a barrier. I do know that handling that "multiple language" case can complicated. 
So I guess the question is: Is it in the roadmap?

**Comment by ZibbyKeaton** [comment]
@fforess good point. I think it's a great idea in theory, the only issue is on how we would manage this... I don't know how many folks in this group can speak multiple languages to determine if the articles we receive are inline with our guidelines. Maybe for now, we keep it as it, but in the next couple of months, we start developing a plan to add in more languages here. This might also help us determine which languages we want to tackle first per requests. We could also see if we might be able to add more folks into this group to help us support it. Let me know if you have any other ideas on this.

**Comment by bnb** [comment]
cc @nodejs/evangelism - want to make sure that *everyone* sees this, and has a chance to participate.

**Comment by thefourtheye** [comment]
I would love to be a part of this. @ZibbyKeaton Can you please include me? I can review and proofread things. I am @thefourtheye in Medium as well.

**Comment by ZibbyKeaton** [comment]
Yes, will add you in shortly @thefourtheye

**Comment by ZibbyKeaton** [comment]
FYI: We received a few suggested pieces of content for NC over the weekend. I created a separate issue for it here: https://github.com/nodejs/evangelism/issues/280 cc @nodejs/evangelism

**Comment by fforres** [comment]
Sounds great @ZibbyKeaton.
I'd love to help proofreading and afterwards, with the multiple languages effort.
:)
In medium I'm @fforres as well.
