### ISSUE TITLE
Feedback Node.js Collection Submissions 2.13.17

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/evangelism#280]
All -

We received two requests over the weekend on content that folks would like to submit to the Node.js Collection. One comes from James Snell and is focused on the status of implementing ES6 modules in core: https://medium.com/@jasnell/an-update-on-es6-modules-in-node-js-42c958b890c#.5j7ljahtx. This would go under our "community" tab.

The other is content that is already been published on Toptal (we would need to give them original credit and link back to the original article if we post). This one focuses on what types of use cases work best for Node.js, what types of use cases work for Node.js and what do not work for Node.js:  https://www.toptal.com/nodejs/why-the-hell-would-i-use-node-js. This would go under our "Best Practices (How to)" tab.

Please let me know if anyone disagrees with these blogs being posted to our **Medium page within three days (so EOD ET time February 15).** If you do disagree or have comments, please be as detailed as possible, so we can provide feedback to the author. 

If any other requests come in, I'll be sure to add it into this thread. I will create a new issue next week. Please let me know if folks are okay with this format.

**Comment by thefourtheye** [comment]
Looping in @jasnell

**Comment by ZibbyKeaton** [comment]
I have two other submissions for this. Please let me know if you would like me to put any or all of these into a Google Document for easy review.

Re: submissions: one is around promises: https://medium.com/xo-tech/xo-tech-node-js-promise-enterprise-grade-first-of-all-d4de14a43ba2#.us9kkm4vv the other is around building a data transit system: https://medium.com/xo-tech/bunnybus-building-a-data-transit-system-b9647f6283e5#.4hkz36uly. 

They look fine to me from a grammatical perspective and they also are not sales pitches (although in the second one he does mention his company, but it doesn't seem overly promotional). What doe others think? 

I'm cc'ing @fforress @thefourtheye @vdeturckheim @bnb and @rosskukulinski as they specifically asked about participating in editing.

**Comment by vdeturckheim** [comment]
For articles already present on medium, can we use the review tool in this platform (I have never used it, but it seems to exist)?

So:
* @jasnell 's article: lgtm. Ok for the community tab but wouldn't we need a "Node core" tab ?
* Toptal's article: lgtm

xo-tech's articles: I will review them ASAP, however, my understanding of medium is that an article can only be in one publication at the same time (at least last time I checked a few months ago), will *xo-tech* unpublish them from the original publication ?

**Comment by ZibbyKeaton** [comment]
You have to be a writer to submit your story to the publication on Medium. I already had one individual ask to be a writer and I added him in. @jasnell do you want me to add you to be a writer? I have a feeling that you might want to post more stories here, so happy to make you a writer.

RE: Node Core: We only have 7 tabs here to work with for themes. I added a Node Core and combined the serverless/container/cloud tab together. This is not perfect, but we can always change these up bit depending on how many submissions we get for each.

You are correct. You can't cross pollinate articles like this. Hold on reviewing this. I reached out to the author to confirm if XO is willing to unpublish and allow us to publish in our Medium publication. Thanks for catching!

**Comment by jasnell** [comment]
Yes! Sounds good

**Comment by vdeturckheim** [comment]
@ZibbyKeaton Thanks for this clarifications :smile: 
Yes those 7 tabs look good to me and we should be able to sort most articles with them!

**Comment by ZibbyKeaton** [comment]
Friendly reminder to let me know if you disagree/have comments on James' blog or the toptal blog by 5pm ET today. If not, then I'll post these to our site. I still haven't heard back from Lam on his blog post, so we will hold on this until we hear back form him. I am going to put a little bug in the ears of the NodeBots community around submitting for Node.js Collection. If there are any other communities that are creating really cool projects or might have interesting stories to share, please put a bug in their ear.

Also, if you see any interesting stories out there that you think would be a good fit for this blog, please share here and then we can ask the writer if we can get their blog into our publication. For example, Jessica from our Outreachy program posted a Medium blog recently about Node Streams. I thought this might be great for our Best Practices (How to) section. What do others think? https://medium.com/@jessica.quynh.tran/a-brief-history-of-node-streams-pt-1-3401db451f21#.w02ex4biu

**Comment by vdeturckheim** [comment]
Jessica's article looks pretty cool to me at first sight. However, should we wait for part 2 to be published or reach her to ensure that part 2 will be written. I just want to ensure we will not publish a "part 1" if there will never be any "part 2" (in this case, the title can be updated).

**Comment by ZibbyKeaton** [comment]
I think either way would work here, but if you have a strong preference on one over the other than happy to go with what your gut is telling you.

**Comment by vdeturckheim** [comment]
I don't have any preference, the article is good and it would anyway be good to have it.

**Comment by ZibbyKeaton** [comment]
Alright, I say we do it :) I'm going to wait for others feedback. If I don't hear any objection by Friday, I'll ask to post :)

**Comment by rosskukulinski** [comment]
I'm 👍 on Jessica & James' articles.

I'm hesitant on the article currently published on [Toptal](https://www.toptal.com/nodejs/why-the-hell-would-i-use-node-js).  That article was originally published 3 years ago and a few of the links & projects referenced are dead/broken, and I wonder if the content needs to be refreshed before we re-publish.

For example, he references Hummingbird at http://projects.nuttnet.net/hummingbird/ which has a dead domain name - and the project hasn't been updated in years.  

The overall article is on-point and well written - I just worry about the word-rot.

**Comment by ZibbyKeaton** [comment]
Good feedback Ross, we can definitely have the writer refresh this. Any other suggestions to this post before I reach out to the author to refresh? Please get them into me by 6pm ET today.

**Comment by ZibbyKeaton** [comment]
@jasnell I just requested that your article go into our publication. If you could also add the tag NodeCore to your piece it will go into this tab. Thanks!

**Comment by ZibbyKeaton** [comment]
The Toptal article has been edited. I have a few comments in here, please share your feedback with me by EOD Monday 6pm ET. After this, I'll share our comments with the writer, have them fix or answer any questions we have and then we can post this: https://docs.google.com/document/d/1JsdT0sfuS4Hcntu6UhPDKoG4aXllzqowCXSydiONBJI/edit

**Comment by ZibbyKeaton** [comment]
Realizing that Monday is a holiday for a few of us, so please send me your edits by EOD Tuesday next week - 6pm ET.

**Comment by ZibbyKeaton** [comment]
Reminder to add in all your edits into this by EOD. There's a few technical questions in here that folks might want to look to: https://docs.google.com/document/d/1JsdT0sfuS4Hcntu6UhPDKoG4aXllzqowCXSydiONBJI/edit

**Comment by bnb** [comment]
@ZibbyKeaton Added a comment, and gave feedback on the only technical comment that I saw. LGTM!

**Comment by bnb** [comment]
@ZibbyKeaton Commented on the article regarding the CC-0 license for the content, and also responded to the only technical comment I see. 

Clicked through some of the links, and found a few dead, and some are *_old_* - commenting through them now.

**Comment by ZibbyKeaton** [comment]
@bnb thanks for highlighting; I found a few dead links in the original, but not finding any currently. Yes, we received approval that we could repost this, we just need to mention that an older version of this was posted in Toptal and link back to the original post and state that it's been refreshed.

**Comment by davidfekke** [comment]
@ZibbyKeaton I am getting ready to publish a post on starting a Node.js User Group on Medium. I don't know if anyone would be interested in having it in the next community release?

**Comment by ZibbyKeaton** [comment]
@davidfekke are you talking about the community newsletter? Also, that could be a good topic for the community section in our publication. Would you be open to that - this group would need to decide first, but maybe you can share here and the group can weigh in.

**Comment by davidfekke** [comment]
@ZibbyKeaton However the group decides it would want to use it is fine by me. Here is a copy of the current draft. 

[https://docs.google.com/document/d/14S3mPjuO_afSmmAp4IoJQb_A7s4toS8-3EGPoqXyGuE/edit?usp=sharing](https://docs.google.com/document/d/14S3mPjuO_afSmmAp4IoJQb_A7s4toS8-3EGPoqXyGuE/edit?usp=sharing)

**Comment by ZibbyKeaton** [comment]
@bnb there's two comments for you in the Toptal document. If you could confirm you are happy with them today that would be much appreciated. From there, I just need to add the author's title and then I can publish.

**Comment by ZibbyKeaton** [comment]
@davidfekke I think this is a good start. When it's in a final draft form, please ping us, so this group can edit.

**Comment by bnb** [comment]
@ZibbyKeaton Resolved the two suggested changes. 👍 

LGTM! :shipit:

**Comment by davidfekke** [comment]
@ZibbyKeaton Please feel free to edit.
