### ISSUE TITLE
New Blog Post on Node.js + Containers = Magic

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/evangelism#281]
Hey All - I just posted a blog on why more enterprises and startups are using Node.js and containers and how to get started with these technologies. If you are interested in helping promote this, below are a few social posts for you to use if you like. Thanks!

- Why are enterprises and startups alike turning to Node.js and containers? Read on here: http://bit.ly/2lPTRGV
- Node.js + containers = magic. Read this blog on the why and how to get started: http://bit.ly/2lPTRGV

**Comment by vdeturckheim** [comment]
You posted the same link twice I think.

**Comment by rosskukulinski** [comment]
@vdeturckheim I think Zibby's providing us with two different example tweets you _could_ use that both point to the same content.

**Comment by vdeturckheim** [comment]
How my bad sorry. Read that too fast :/ I really need some sleep.

**Comment by vdeturckheim** [comment]
If some of you want to upvote on:
* reddit
https://www.reddit.com/r/node/comments/5uau8o/nodejs_containers_magic_read_this_blog_on_the_why/
https://www.reddit.com/r/webdev/comments/5uavwk/why_are_enterprises_and_startups_alike_turning_to/
* HN
https://news.ycombinator.com/item?id=13656093
