### ISSUE TITLE
Node.js Collection Publication Edits and Idea for Week of 2/20/17 and 2/27/17

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/evangelism#282]
Hey All - Hope you are having a good week. I wanted to send over a few blogs that I think would be nice on our publication. Also @davidfekke is writing a blog on how to start Node.js User Group, which sounds really good to me. What do others think of this topic and the below blogs for NC (I would need to ask the authors if we can repost before we do so):

- Learning Node.js through creating games: http://www.nobadmemories.com/blog/2016/11/fun-and-games-with-node-js/

- How to build bots without hardware: https://nowayshecodes.com/2016/12/27/bots-are-banging-getting-started-with-the-microsoft-bot-framework-node-js/ (this gives examples of Microsoft products, but I don't think it's overly promotional and more educational).

- How Groupon Uses Node.js: https://medium.com/@nodejs/groupons-global-deal-with-node-js-95c54f51ab5b#.46hk3dr1w (this is from the Node.js Foundation and has a nice mobile narrative in it).

**Comment by ZibbyKeaton** [comment]
Adding another to this list, the team at Rising Stack is interested in posting this blog: https://medium.com/@RisingStack/10-best-practices-for-writing-node-js-rest-apis-46ffa728a464#.pdijznmvy 

I think it looks good, but let me know if others disagree. 

As a reminder, please let me know if you reject the four suggested above by EOD Monday (February 27) and if your reject the RisingStack blog by EOD Tuesday (February 28). Once I get your feedback we'll go through editing those that are not yet published ;)

**Comment by ZibbyKeaton** [comment]
@davidfekke I made some initial edits and suggestions into your post. Let me know what you think. Also, do you have a code of conduct at your meetup group? I know folks have been talking about doing this more with user groups and it's something that the Foundation really supports. If this is something you have experience in then I would love to have you add that or we can always have someone else provide their thoughts too. https://docs.google.com/document/d/14S3mPjuO_afSmmAp4IoJQb_A7s4toS8-3EGPoqXyGuE/edit?ts=58aef4b3#

**Comment by davidfekke** [comment]
@ZibbyKeaton We do not have a code of conduct policy. We have been meeting for 3 1/2 years, and we have never had a problem. One time we had a heated debate about the tenets of GIT vs. TFS source control, but everyone has always been professional. I know some of the other user group managers have used Meetup's ban feature on some of their users, but we have never had to ban a member. Everyone has always been cool and professional.

I will review your changes.

Thanks,
David

**Comment by ZibbyKeaton** [comment]
Thanks for the background there. I thought overall it was a really helpful and informative article. Thanks for submitting @davidfekke

**Comment by davidfekke** [comment]
@ZibbyKeaton I have the draft on Medium. Do you want me to publish the edits and pass you the URL?

**Comment by ZibbyKeaton** [comment]
Mind sharing the draft on Medium here, so other members of the evangelism working group can weigh in? I would like to give them a little time to provide their feedback here as well before we add it to the publications. Can evangelism folks provide their edits to this by EOD Thursday?

**Comment by ZibbyKeaton** [comment]
Hey All - See this recent comment to our "Why the Hell Would You Use Node.js" https://medium.com/@leichtgewicht/i-see-this-arguing-often-appear-and-i-think-it-is-focussing-on-the-wrong-points-a2c181135886#.dgypufk81. I think it's worth reaching out to the author of this comment and suggesting that they turn it into a post that we can include on Node.js Collection. What do others think here?

**Comment by ZibbyKeaton** [comment]
Tagging a few members that said they were interested in helping edit @fforres @vdeturckheim @bnb @rosskukulinski- please see my suggestion around the comment to our most recent article and also please let me know if you want to provide edits to @davidfekke article via Medium or via Google Documents. I want to get in all our edits to the Node.js User Group document by EOD Thursday.

**Comment by vdeturckheim** [comment]
@ZibbyKeaton The reponse you mentionned is pretty impressive. I would love to have this guy work with us actually. 

Let's do the review on Google doc, it is probably the easiest tool for such things. 

Thanks a lot @ZibbyKeaton , the work you achieve is pretty impressive here !

**Comment by davidfekke** [comment]
@ZibbyKeaton I have added all of the edits to my medium publish. I can publish it now, and send you the URL. How would you like for me to publish?

Thanks,
David

**Comment by ZibbyKeaton** [comment]
@davidfekke that sounds great. Please send the URL to me via email and I will request it to be added to the Node.js Collections. Also, happy to include you as an editor to the collection page, so in the future if you write a Medium post and it's approved, you can just add it in.

**Comment by davidfekke** [comment]
Zibby,

I don't have your email. If you send me your email address, I will forward
you the Medium post.

Thanks,
David Fekke
davidfekke@gmail.com

**Comment by ZibbyKeaton** [comment]
Just share here or send it to medium@nodejs.org.

**Comment by davidfekke** [comment]
Wilco.

https://medium.com/@davidfekke/how-to-start-a-node-js-user-group-e17399d213b1#.chfcfkeq7

**Comment by ZibbyKeaton** [comment]
Great - just requested it to be added to the publication. You should receive a notification on this shortly @davidfekke.

**Comment by davidfekke** [comment]
Awesome. Thanks Zibby.
