### ISSUE TITLE
Belong to a Node.js, JavaScript, React, etc. Meetup Group. Mind sharing? 

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/evangelism#285]
Node.js Interactive Call for Presentations closes in a month, and we want to make sure we have a bevy of diverse voices and submissions...

One area that we could particularly use help with is encouraging members of your local Node.js, JavaScript, Angular, React, Women Who Code, etc. meetup group to submit a talk. We find that an ask coming from within a group is the best way to go about this. A major part of Node.js Interactive is providing an opportunity for the Node.js community to connect, learn and interact with one another.

We will be offering diversity scholarships, speaker travel funds and community travel funds. We do not want folks to feel worried about applying due to financial reasons.

Below is sample copy for you to share with your meetup group. Feel free to tweak as you see fit. Thank you for sharing with your meetup groups and feel free to share this copy with others!

**MEETUP CONTENT**
Do you have a lot of great ideas about Node.js and JavaScript? Did you overcome a particular challenge that you think would be helpful to other Node.js developers and end users?

The Call for Presentations for Node.js Interactive, which will be held Oct. 4-6 in Vancouver, BC, closes Monday, April 10. This is the marquee event for Node.js developers and companies that rely on Node.js and the vendors that support both of these constituents with tools, training and other services. 

Never participated in a talk before? Don't let that stop you. Our meetup is great place to get feedback on your proposal or even practice your talk before heading to Node.js Interactive.

Diversity scholarships as well as community and travel funds are available as well, so don't let that hold you back either. Please email events@linuxfoundation.org with any questions.

Get started here: http://bit.ly/2ljbPF7.

**Comment by davidfekke** [comment]
I will mention this at JaxNode on Thursday evening.

**Comment by a0viedo** [comment]
I'll mention this at Buenos Aires Node.js tomorrow.

**Comment by fforres** [comment]
I've got an Incoming Meetup for SantiagoJS, will make announcement there 😄

**Comment by ZibbyKeaton** [comment]
Thank you all!

**Comment by bnb** [comment]
I'll also share it at the GDG Capital Region as it comes up 👍

**Comment by hlfshell** [comment]
Brought it up at node.jSTL tonight.

**Comment by bnb** [comment]
@ZibbyKeaton Going to close this issue because the CFP is now closed. It may be interesting if we can do something like a discount code for the Evangelism WG, though 🤔
