### ISSUE TITLE
Node.js Collection Blog Week of April 17 - April 24

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/evangelism#289]
All - I haven't taken a look at this from a grammatical standpoint yet, but wanted to see if you think the topic of this article is interesting: https://medium.com/@jacopodaeli/4965b5f910f4 - debugging Node.js with Google Chrome? I would imagine so, but please let me know your feedback on this by EOD this coming Wednesday.

**Comment by davidfekke** [comment]
This is a handy post on how you can use Chrome's breakpoint debugger with Node.js. This is a good tip for developers who are not using a full fledged IDE for debugging.

**Comment by Trott** [comment]
Since debugging behavior is changing (has changed?) a lot, it might be good to get someone from @nodejs/diagnostics to take a look at it to make sure there isn't info in there that might age poorly or be incomplete or whatever.

For one thing, I know there's been a lot of discussion about whether or not telling people to copy/paste the URL (that shows up in the command line interface) is the ideal workflow or not.

**Comment by ZibbyKeaton** [comment]
Following up with @nodejs/diagnostics to see if they want to take a look at the Medium post above to make sure we are giving folks the best direction in this subject matter?

**Comment by hybrist** [comment]
> To start debugging, run your Node.js application with the --inspect flag, and open in Chrome the URL starting with “chrome-devtools://” that is generated and displayed to you in the terminal.

That URL is about to go away so I wouldn't highlight it. We list multiple options in the [debugging guide](https://nodejs.org/en/docs/guides/debugging_getting_started/#chrome-devtools-55) that might work better. Especially when using the default port for `--inspect`, it might also be worth to mention the dedicated Devtools for Node which is the most convenient option (e.g. it survives restarts of the node process):

<img width="551" alt="screen shot 2017-04-20 at 8 31 09 am" src="https://cloud.githubusercontent.com/assets/567540/25240141/f3e08ac8-25a6-11e7-9b4f-c7c85ad620bd.png">

**Comment by ZibbyKeaton** [comment]
@jkrems Thank you. I'm asking this person to change his Medium page into a Google Document in case we have any more edits. I think that will help streamline the process a bit given there's so much movement here.

**Comment by ZibbyKeaton** [comment]
Hey All - We have two entry requests this week. @vdeturckheim has a Medium post interview with James Snell, this is a part of his series "Meet the People of Node.js." I provided some suggested edits to it already; if you have any additional ones, please confirm by EOD Wednesday (April 26).

Additionally, a member of the Google team is interested in writing a blog on async/queue. Here's the general description:

_Possible blog post title could be "Processing large datasets with async/queue in less than 100 lines of code". I can also shorten the snippet to make it a bit more general. 

Here's what it does: takes an ID from a local JSON file, pushes the ID to a queue, the queue generates the GCS url from the ID and sends the image to the vision API, then writes it to a local JSON file in the response._

What does this group think and do you need more specifics or background here? Please provide me your thoughts and approval by EOD Wednesday (April 26) as we'll.

**Comment by vdeturckheim** [comment]
I thinks the dataset processing article looks very exciting. I'd like to read that!

**Comment by ZibbyKeaton** [comment]
All, we put the debugging into a google document that you can find here: https://docs.google.com/document/d/1MgXp7iBGDQF389XGsh9x7sQjWY4vlBpPhPKVoK37qjY/edit#. I've added the above edit in and mine too. Please send me any feedback on this (if you have any feedback) by EOD Friday. cc @nodejs/diagnostics

**Comment by ZibbyKeaton** [comment]
Thoughts on adding this to the collection @mhdawson recommended it to us. Please let me know your thoughts on this by EOD Friday. https://developer.ibm.com/node/2017/04/20/keeping-node-js-core-small/

**Comment by sam-github** [comment]
@ZibbyKeaton Not to be too tireless a promoter of myself... but https://developer.ibm.com/tv/devoxx-us-2017-versioning-node-js/?social_post=874449549&fst=Discover may be apropros. Get @MylesBorins to confirm whether its generally reflective of LTS efforts, or just what I desperately came up with under pressure to speak on a topic for 5 minutes.

**Comment by ZibbyKeaton** [comment]
@sam-github I like the idea. I really do feel like a lot of folks still need to be educated around this and we are always looking for content of the sort. It was also noted in our recent survey that people are still a bit confused about releases and want more information about this. 

Were you thinking that the blog and video would stay the same or were you going to convert some of the video content into a more extensive blog post? I find that most folks like this type of stuff in writing, so we might want to go that route and then we can link to the video and this blog post for those that prefer video vs text as well as maybe videos around this that Myles has done. I'll also defer to @MylesBorins and this group on their general thoughts on the topic. 

Can folks please confirm thoughts with a 👍if they like the idea by EOD Monday.

**Comment by sam-github** [comment]
@ZibbyKeaton I think it works OK as a video, do you have a "interesting links found around" section of the roundup? It would fit in there. If the format is not right, then I'd have to find time to rewrite.

**Comment by ZibbyKeaton** [comment]
@sam-github are you okay with me posting this to Node.js Collection - https://developer.ibm.com/node/2017/04/20/keeping-node-js-core-small/? We'll add it to Node.js Foundation Medium page and add you as the author - see example here: https://medium.com/the-node-js-collection/node-js-8-0-0-has-been-delayed-and-will-ship-on-or-around-may-30th-cd38ba96980d

**Comment by ZibbyKeaton** [comment]
Another submission came in. What do folks think about this one: https://goenning.net/2016/02/10/simple-server-side-cache-for-expressjs/. Please give a yes 👍 or no 👎 vote by EOD Wednesday.

**Comment by davidfekke** [comment]
I give simple server side caching a thumbs up.

**Comment by sam-github** [comment]
@ZibbyKeaton re: https://github.com/nodejs/evangelism/issues/289#issuecomment-299501370, I asked, no problem, and as part of the lead-in attribution, we’d like you to reference the original article. :+1:

**Comment by ZibbyKeaton** [comment]
@sam-github what is your twitter handle?

**Comment by ZibbyKeaton** [comment]
@sam-github added this to the collection: https://medium.com/@nodejs/keeping-the-node-js-core-small-137f83d18152 Happy to update it with your Twitter handle and/or anything else you may need here.

**Comment by sam-github** [comment]
@ZibbyKeaton Looks nice, thank you. I'm https://twitter.com/octetcloud, you can add that if you like.

**Comment by sam-github** [comment]
@ZibbyKeaton can you add a space so it is "Node.js @ IBM"? (@IBM makes it look like a twitter handle)

**Comment by ZibbyKeaton** [comment]
Doen @sam-github

**Comment by Trott** [comment]
Typo: I'm pretty sure it's "Dominic Tarr" rather than "Dominic Tar".

**Comment by Trott** [comment]
Nit:

> the more you wish that node had been more conservative 

=>

> the more you wish that Node.js had been more conservative

**Comment by ZibbyKeaton** [comment]
Thought I got them all, thanks for letting me know.

**Comment by Trott** [comment]
This paragraph styles `util.deprecate()` two different ways. (I get that one of them is a link to the docs and needs to be styled like a link. That's fine, but it should still have the `()` like the other instance.) Additionally, there's a comma splice.

> Take util.deprecate as an example. util.deprecate() has been an API since 0.8, note that this predates the existence of Node.js’ internal module system, which allows private APIs only usable by Node.js.

**Comment by Trott** [comment]
(Oh, an additional tiny nit on that paragraph: `Node.js's` rather than `Node.js'` although I'll defer if you think it is just better without the trailing `s`. The "no `s` after the apostrophe"  rule is generally for plural nouns only. Perhaps this is a good place to just get rid of the word `Node.js` and say `predates the existence of the internal module system`.)

**Comment by ZibbyKeaton** [comment]
@Trott are you on Medium? If so, I can add you as an editor and you can directly edit this. If you want to send all the editing issues you found via email to my address that would be great - probably easiest to streamline this way.

**Comment by Trott** [comment]
Comma splice/run-on sentence:

> Node.js uses this API, it’s tied into various CLI options (--no-deprecation, etc.) so is not about to go away, and exposing it to users doesn’t seem to cause any harm.

**Comment by Trott** [comment]
OK, I'll stop posting every little thing here. :-D
