### ISSUE TITLE
Finding the best solution - Social Team Management

### ISSUE THREAD

**Issue by bnb** [nodejs/evangelism#29]
Evangelism Team Management in Social Media has been something @mikeal has been talking about since the first day I found the io.js community and started commenting.

I've done a lot of research into the topic, and have pretty much come out with just a few options. It seems that the only tools that can really get us what we need are either Buffer (https://bufferapp.com/app) or HootSuite (https://hootsuite.com/). We would need one of their team-based plans, with enough seats for the members of the WG that want access, plus leaders of the community.

We've discussed the topic on the Gitter, and several people, including myself, thought it would be reasonable to search for a sponsorship to get an account at either site that we can use to solve our problem. I'm not wise as to how sponsorships are normally granted, or who in the io.js leadership to talk to about this. 

What are your thoughts on this? If you think it's a good idea, what is the best way to go about it? If you think it's not a good idea, would you share why? Of course it would probably be best to get @mikeal's sign off on whatever we do, as he's the one currently charged with handling the social accounts.

**Comment by dotproto** [comment]
Today I reached out to one of my contacts regarding HootSuite. Hopefully I'll have some developments worth sharing in the not too distant future. 

EDIT: I should also note that I'm exploring the possibility of building a tool that could help with multi-user management of a single Twitter account. It's a good excuse to have fun writing some code ;)

**Comment by subfuzion** [comment]
HootSuite actually looks pretty cool..

**Comment by Gioyik** [comment]
Tweetdeck has a Team feature that could fit the solution for this.

Tweetdeck teams blog post: https://blog.twitter.com/2015/introducing-tweetdeck-teams
Video about Tweetdeck teams: https://www.youtube.com/watch?v=SykSn95WBhk&t=22

Pros:
- You can schedule tweets (same as HootSuite)
- Multiple user managing an account
- Tweetdeck live stream is really great and faster than others

Cons:
- It works only for Twitter accounts
- For this issue I can find more cons in Tweetdeck :)

**Comment by rvagg** [comment]
tisk tisk, our evangelism team using the term [Final Solution](http://en.wikipedia.org/wiki/Final_Solution), I hope this doesn't get out to the twitterati.

**Comment by julianduque** [comment]
@rvagg changed ;)

**Comment by mikeal** [comment]
I've been using tweetdeck and can't really figure out this teams stuff.

Recently I've realized that we've been going about this all wrong. This is a terrible way to select software.

Let's figure out what we want to _do_ with the twitter presence, as a project, and then select a set of tool(s) to do that.

As it stands, this is what I'm already doing on it (mostly by myself).
- Re-tweeting important things (Rod announcing releases, Tessel adopting Node)
- Tweeting about accomplishments (number of contributors, number of translations of something)
- Reading every mention of "io.js,iojs".
  - Favoriting all positive tweets
  - Responding to all problems people are having
- Attempting to keep up with mentions of "node.js,nodejs" but I consider it secondary.

Right now I'm doing this all by myself with very little process so however we can best cut this up, distribute the work, and do a better job, let's do it.

**Comment by subfuzion** [comment]
Same here with the favorites and retweets. I suppose the idea behind some of the proposed tools is more about consolidating message streams and then analyzing the impact. So far I've felt that using GitHub and Gitter to coordinate and being active on Twitter is working. Agree that we need to have goals before tool selection.

**Comment by Gioyik** [comment]
Tools should be used to publish content, I mean something like add an integration with an RSS to tweet latest news automatically, that would be a good use for social media tools. If main goals in social media are interact with people and give user-friendly answers it's better find another process to manage the account instead of searching an all-in-one-ultra-hype tool that fits everything.

**Comment by blakmatrix** [comment]
What about a simple @iojs_evangelism twitter account we can all follow and retweet or retweet with a mention to, with the Idea that this account has and will receive the most important evangelism related tweets?

**Comment by mikeal** [comment]
This whole feed to tweet and separate account to tweet feels like over engineering.

Let's try for something simple:
- Split up the day/time that people are monitoring twitter.
  - Tweet deck for favoriting positive comments and replying.
  - When your time comes up look through the thing that have already been replied to.
- Create a GH issue each week where we load up a specific number of io.js issues we should be pointed people to and schedule them to be sent out with Buffer.

The posts we load in to buffer can easily go out on G+ and Facebook as well.

**Comment by Gioyik** [comment]
I forget to mention that IFTTT is really good solution for automated process. I am seeing some issues and conversations on iojs about how to automate a bit some process and IFTTT could be the right solution. Indeed, IFTTT works too very good with social accounts.

**Comment by bnb** [comment]
What is the current status of this? Has a system been laid out, or are we still grasping to figure out a method of management?

**Comment by mikeal** [comment]
Still figuring it out, it will get more complicated when we take on the nodejs twitter account as well.

**Comment by dotproto** [comment]
Though now there's potential for the foundation to cover some of the cost, no? In lieu of that, is there a way we could collect donations form the community? I for one would be happy to kick some into a fund.

**Comment by mikeal** [comment]
Yes, the foundation can cover the cost of reasonably priced tools without much worry. For now I've just been paying for stuff outright until we have a bank account :)

**Comment by bnb** [comment]
@mikeal Okay, sounds good. 

Here's a list of tools that might be good, given that we can do some sort of payment. Note that number of team members is probably going to be the biggest point for us, as a large number of contributors is essentially the io.js way.
- http://socialcast.localvox.com/ (Looks very good)
- www.mediaroost.com
- https://commun.it
- https://hootsuite.com/

**Comment by dotproto** [comment]
@mikeal Paying for social management stuff? If so, I'd be happy to PayPal or Cash some money your way to help cover some costs :smile:
