### ISSUE TITLE
Node Summit 2017: CFP

### ISSUE THREAD

**Issue by vdeturckheim** [nodejs/evangelism#290]
Hi all,

Just a quick reminder, the CFP for the Node Summit are open right now:

http://nodesummit.com/nodetalks/

Everyone is invited to summit a talk. There is a real effort to improve diversity within the speakers. If you have something to talk about or if know anyone who might have a good talk, you should not hesitate to submit a paper!

Also, can you guy please tweet and share it? It would be awesome to have some help sharing this with the Node.js world!

**Comment by Trott** [comment]
CFP is closed, event starts today, closing!

> /cc @nodejs/community-committee is the a communication channel for of those going to NodeSummit 2017?

I don't think it's supposed to be that, but I don't know that we have one either. Feel free to re-open if there's consensus that this is a good place for it.
