### ISSUE TITLE
Node.js Collection May 22 - May 29

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/evangelism#292]
All - We have a couple of backlog articles that are in need of review and approval. Below are all the articles and the action items there. 

Additionally, I discussed this a bit with @bnb and also opened it up in the Community Committee https://github.com/nodejs/community-committee/issues/45#issuecomment-303433160, but we think it would be wise to update our process guidelines and build in at least one technical reviewer as a requirement before any article is posted to the Node.js Collection. 

What does this group think? Currently we do this ad hoc, but I think having one or a few people own this task would make the process more seamless. Does this group agree and is anyone interested in taking on that role?

With that, here are the articles that we have in our pipeline:
- **Debugging Node.js with Google Chrome**: https://medium.com/@jacopodaeli/4965b5f910f4 (I shared this via Google Document a few weeks ago). Are there any last minute edits needed here? Please let me know by Thursday 3pm ET

-We agreed upon reposting this "**Simple server side cache for Express.js with Node.js**" https://goenning.net/2016/02/10/simple-server-side-cache-for-expressjs/ This generally looks good to me from a grammatical standpoint - there are a few spaces that we'll need to add in. The only area that I wanted to flag was the fourth paragraph it appears we are missing a "to,"but I wanted confirm with others that this addition is technically correct. Here's how it reads:
_The goal of server side cache is responding (add to) the same content for the same request independently of the client’s request._

If this group could also do a technical review on this that would be great. Given the upcoming holiday, please send any technical updates by EOD Tuesday, May 30.

**Comment by ZibbyKeaton** [comment]
The debugging post is live: https://medium.com/the-node-js-collection/debugging-node-js-with-google-chrome-4965b5f910f4

**Comment by ZibbyKeaton** [comment]
I have another blog post for this group to review: https://docs.google.com/document/d/1TWOCpyrXJfI__7QsXBVOJSsU7rLgDZfwSCB2U-jSeMc/edit.

**Comment by ZibbyKeaton** [comment]
And finally, I wanted to add the Node.js 8 and Node.js API blog to Node.js Collection. Please let me know if you have any issues with this by EOD Wednesday next week.

**Comment by MylesBorins** [comment]
hey all did you get a chance to review the post that @ZibbyKeaton mentioned two comments above? Would be great to include it (my coworker put quite a bit of time into it)

**Comment by ZibbyKeaton** [comment]
Adding to this chain @poledesfetes @davidfekke @bnb - are you okay with us posting the "Processing a large dataset in less than 100 lines of code with caolan’s async.queue" post? Any comments? If you look over it and think it looks good, could you give a 👍If you have edits, mind getting them in by EOD Thursday? Thanks!

**Comment by vdeturckheim** [comment]
Both article look good to me

sorry for the delay.

**Comment by ZibbyKeaton** [comment]
Thanks @vdeturckheim
