### ISSUE TITLE
Moving to the Community Committee?

### ISSUE THREAD

**Issue by nebrius** [nodejs/evangelism#294]
Hi @nodejs/evangelism!

As you may or may not know, we recently created the [Community Committee](https://github.com/nodejs/community-committee), or CommComm for short. CommComm is a top level committee in the Node.js Foundation, meaning that we're a sibling of the TSC. We formed CommComm to focus on all of the non-code related activities that the Node.js project is working on, and the TSC can now focus on only on all of the code related activities (of which there are many).

Would you be interested in moving from under the TSC to CommComm?

If you decide to move, you would still operate the same as you do now, the only thing that would change is who you ask when you need funding from the Node.js Foundation. Given CommComm's focus on community, getting funding for evangelism activities should become easier if you switch, and we can also more easily connect you with other parts of the Foundation. I do want to clarify though that this decision is completely up to you, and if you would prefer to stay under the TSC, then that is absolutely your right.

So what do you think?

**Comment by vdeturckheim** [comment]
As a first guess, I don't have any objection against moving to CommComm. 

In what way would it be easier to connect with other parts of the Foundation?

**Comment by bnb** [comment]
I am +1. I have been participating in the Community Committee to some extent, and honestly think it will be a conducive place for the Evangelism WG. 

>In what way would it be easier to connect with other parts of the Foundation?

I am also curious about this 🤔

**Comment by julianduque** [comment]
I'm agree, it is better to have community efforts under one umbrella

**Comment by bnb** [comment]
I've gone ahead and personally reached out to all Evangelism WG members via Twitter DM to see if we can get as much input as possible. 🙏

**Comment by JungMinu** [comment]
I think this is a good idea 👍  so I'm +1 too

**Comment by yosuke-furukawa** [comment]
+1 too! Thank you!

**Comment by affinity-matrix** [comment]
I am definitely +1 on this idea but have had very little actual involvement in this WG thus far so my input should be weighted accordingly. 👍

**Comment by fforres** [comment]
Looks like a great idea 😄

**Comment by Gioyik** [comment]
it's fine for me.

**Comment by danielkhan** [comment]
Looks fine to me. Thank you for the initiative.

**Comment by nebrius** [comment]
> In what way would it be easier to connect with other parts of the Foundation?

The primary way this will be easier is in requesting things from the board. Under the current setup, if you need to request funding for evangelism activities (this is something you can do!), then you need to ask the CTC (since technically you're chartered under them), who would then go and ask the TSC, who would then go and ask the board. Under CommComm, you would just need to ask CommComm, who would then go to the board.

Also, given that CommComm is focused on community involvement, Requests from the Evangelism WG would be a higher priority for CommComm than it is for the TSC (as it should be, the TSC/CTC should be focused on the technical operations of the project).

CommComm would also request (but not require) that the Evangelism WG have a representative on CommComm itself to ensure better representation of the WG.

**Comment by vdeturckheim** [comment]
@nebrius thanks for this clarification. This seems like a great idea to me then!

**Comment by bnb** [comment]
@nebrius Looks like there's near consensus in the CTC issue. What are our steps to move forward?

**Comment by nebrius** [comment]
@bnb it seems to me that the WG already has reached consensus here, as there are no objections. The consensus seeking model in Node.js doesn't require every member to actively give approval, so if a few people haven't spoken up that's ok.

That said, it's not my place to state what the WG's consensus is since I'm not a part of it.

Is there a chairperson of the evangelism WG? If so, I would recommend that they be the one to formally state whether or not the WG has reached consensus. If not, then anyone from the WG can state it.

**Comment by nebrius** [comment]
There's also discussion happening amongst the CTC in the linked issue, which is the next step. Once that's done, we get CommComm's approval. Then we PR the various documents and the move is considered complete.

**Comment by bnb** [comment]
@nebrius There is not an official chairperson for the Evangelism WG (I believe it was formed well before that would have been considered for a WG).

With input from 9 WG members in this issue, none of which have been -1, I feel confident in stating that we've reached consensus in the decision.

**Comment by ghost** [comment]
this is done now, so maybe it can be closed? or do y'all want to put a notice in the readme of this repo or something?

**Comment by nebrius** [comment]
> this is done now, so maybe it can be closed? or do y'all want to put a notice in the readme of this repo or something?

It's probably wise to put a blurb in the README, similar to https://github.com/nodejs/nodejs-collection#about-this-team

**Comment by bnb** [comment]
@pup / @nebrius Check - added it. Will merge in a few days if there are no -1, or there are a couple +1. https://github.com/nodejs/evangelism/pull/296

**Comment by bnb** [comment]
https://github.com/nodejs/evangelism/pull/296 has been merged 💥

Closing this. Please feel free to reopen if needed.
