### ISSUE TITLE
Contributing guidelines

### ISSUE THREAD

**Issue by jsynowiec** [nodejs/evangelism#298]
Hey!

After exchanging a few emails with @bnb I've started going through the issues and documents, looking for some pointers how to get involved and where to start - a guide or some rules regarding collaboration.

Unfortunately current [contributing](https://github.com/nodejs/evangelism/blob/master/CONTRIBUTING.md) guidelines are not that very informative. Document only contains DCO and CoC. I think that having a better contributing guidelines will be beneficial. CommComm's [collaborator guide](https://github.com/nodejs/community-committee/blob/master/COLLABORATOR_GUIDE.md) and [guidelines](https://github.com/nodejs/community-committee/blob/master/CONTRIBUTING.md) could serve as a base for such documents.

Also there is a link to the roadmap in README, but c.a. 6 months ago that repository and WG was retired. Not sure where it should point now? Maybe to the [nodejs/LTS](https://github.com/nodejs/LTS) repository?

**Comment by bnb** [comment]
Thanks for the issue @jsynowiec! 

I think updating the contributing guidelines would be an extremely helpful contribution and something that needs to be done. I'll add the Good First Contribution tag to this issue - if you want to submit a PR updating the contributing guidelines, based on the CommComm Collaborator Guide and guidelines, I'd be happy to help review - and I know a few others would, too. 

As for the link to the Roadmap WG - thanks for noticing that. I've submitted https://github.com/nodejs/evangelism/pull/299 to update it - would love to get your feedback on it. It's a small PR 😄

**Comment by jsynowiec** [comment]
Sure. I'll try writing down/copying something and submit a PR for review. Prolly you can't assign an issue to someone outside repository members?

> As for the link to the Roadmap WG - thanks for noticing that. I've submitted #299 to update it - would love to get your feedback on it. It's a small PR 😄

Heh. Ok. I wanted to fix this and get one more contribution but I thought that asking first before submitting a PR is preferred 😉

**Comment by bnb** [comment]
@jsynowiec I've assigned you as the owner 🎉

Also, always feel free to submit a PR, create an issue, or do both - any method works, a contribution is a contribution. ❤️

**Comment by jsynowiec** [comment]
Just wanted you to know that I'm still interested in working on this. It's just hard to find some spare time now ;)

**Comment by bnb** [comment]
@jsynowiec No worries! Thanks for you interest, and we're happy to have you as a contributor when you can make it work 😄

**Comment by bint** [comment]
Hello, I am interested in ptiching in. Is this something you still would like help for? Thank you

**Comment by Trott** [comment]
@nodejs/evangelism ^^^^^^^

Is this being actively worked on (in which case, maybe someone reply to @bint) or should this be closed?
