### ISSUE TITLE
Social Media Style Guide

### ISSUE THREAD

**Issue by bnb** [nodejs/evangelism#3]
Would there be any interest in a social media style guide for io.js? This type of thing is employed at major companies to keep brand consistency across the board. 

I know io.js isn't Google or Yahoo!, but I think it's important for us to come off as a unified front, and the only way to stay consistent enough to maintain that is to have a guide that anybody representing io.js can look to to know exactly how to write and respond appropriately.

I started working on a basic one when I first found iojs/website and saw the Evangelism issues, but haven't worked on it a ton since. I'd be happy to work on it some more and then post what I've got for everyone to take a look at.

If you do think this is a good idea, I'd really be interested in listening to your thoughts on how we should present io.js as a unified front.

**Comment by mikeal** [comment]
This has come up a few times, we've tried to advocate some basic stuff like "always be positive" but it would be good to get something bigger down. It would also be good to include something like "whenever possible let people know how they can contribute and be involved."

**Comment by bnb** [comment]
Okay, I'll have something in the next few days.

**Comment by mikeal** [comment]
I think we should keep it simple, just a set of basic guidelines. It'll be useful for translators too. I'll start with a few:
- Always be positive.
- If people are negative towards io.js "kill them with kindness."
- Don't be too formal.
- Whenever there is an opportunity, let people know how they can be involved and contribute.
- Interactions should be bi-directional, we should reply, like, favorite and re-tweet the community as often as we post outgoing content.
