### ISSUE TITLE
Twitter background not high enough resolution for rMBP

### ISSUE THREAD

**Issue by bnb** [nodejs/evangelism#30]
Apparently Twitter didn't tell us that we needed a high resolution version of the profile background. Kyle Mathews let us know that the resolution is low for retina Mac Book Pros. We should definitely have the maximum definition image (@3x now?) that will be displayed on any current device. 

Source: https://twitter.com/kylemathews/status/572979716937801728

**Comment by rosskukulinski** [comment]
shipped in #33
