### ISSUE TITLE
New Discount for Node.js Interactive for JavaScript User Groups

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/evangelism#300]
Hey All - We are partnering with the JS Foundation for a special JS track during Node.js Interactive. You can find the details here: https://js.foundation/announcements/2017/09/20/js-foundation-joins-the-node-js-interactive-2017-experience

If y'all are part of a JavaScript user group/meet up group, please feel free to share this post and the discount!

**Comment by davidfekke** [comment]
Thanks Zibby. Will do.

**Comment by ZibbyKeaton** [comment]
Thanks @davidfekke !

**Comment by bnb** [comment]
Thanks @ZibbyKeaton - I'll share this with a few local groups. ❤️
