### ISSUE TITLE
Reviving Evangelism Working Group

### ISSUE THREAD

**Issue by codeekage** [nodejs/evangelism#302]
Here seem to be dead and buried as most activity is actively done on the CommComm. Is anyone other than me is interested in bringing this WG back to life?

**Comment by davidfekke** [comment]
I am interested. I run a Node.js user group here in Jacksonville. Always looking for ways to Evangelize Node.

**Comment by fforres** [comment]
It is really interesting :) 
In this issue https://github.com/nodejs/evangelism/issues/294, it was decided that it'd become part of the Community Commitee, better to have community efforts under one umbrella :)

**Comment by codeekage** [comment]
It's really exciting to see an interest in bringing this WG back, and I see no difference between this WG and other WG under the umbrella of the TSC. This WG can be under the umbrella of the CC, matters like diversity and inclusivity can be well handled under this WG. 

> The Evangelism WG creates promotional materials, brings discussions to a wider audience, and attempts to grow the community through positive, supportive messaging.

And if we'll want to achieve a wider audience I personally think that this WG should be given some time to come work together and see how it can profit the Node.js Project and They should be a working system like other WG do have such as bi-weekly meetings and probably a coordinator to ensure that this WG do what is named after "Evangelism".
