### ISSUE TITLE
Hackathon Sponsorship

### ISSUE THREAD

**Issue by Ethan-Arrowood** [nodejs/evangelism#303]
I hope this is the right place to inquire about this; if not I'm happy to move the conversation elsewhere 😊

My name is Ethan Arrowood and I am a university student at Wentworth Institute of Technology. I am the lead organizer for our annual, university hackathon, HackWITus. As my team is looking to expand our outreach in the tech community we were interested to see if the Node JS foundation would be able to sponsor our event this November. 

While monetary contributions are most needed, we understand that not all organizations can support us in that way. We would be just as happy to have Node JS community members attending as representatives to help mentor the participating teams or even present workshops. 

Thank you for your time!

Ethan Arrowood

**Comment by Trott** [comment]
@nodejs/board (might not be the exact right people to ping but would probably know the exact right people to ping)
