### ISSUE TITLE
readme grammar

### ISSUE THREAD

**Issue by jdavhar90** [nodejs/evangelism#304]
How to get involved!
There are lots of ways to contribute to Node.js. If you are interested in contribution to Node.js evangelism specifically, feel free to join in the conversations, comment on and create issues where you see fit, submit pull requests if something can be improved, and help<del>ing</del> others get started. You don't have to be a member of the Working Group to pitch in!

**Comment by jdavhar90** [comment]
" helping others get started"  to  "help others get started"

**Comment by Trott** [comment]
@jdavhar90 Feel free to open a pull request to make this change!
