### ISSUE TITLE
i18n footer now live

### ISSUE THREAD

**Issue by snostorm** [nodejs/evangelism#31]
If you head over to https://iojs.org/en/index.html you'll see we have 18 additional localizations linked now on https://iojs.org. Previously you had to "know how to find these links" in order to consume the i18n content.

Feel free to tweet, use this for weekly updates, etc.

Via https://github.com/iojs/website/pull/258 which came as a followup to some build improvements on https://github.com/iojs/website/pull/257

**Comment by mikeal** [comment]
https://twitter.com/official_iojs/status/573175622165389312

**Comment by bnb** [comment]
Should we include this in the weekly update? Is it the type of thing we usually list there?

**Comment by mikeal** [comment]
yup, stick it in the weekly update and then close this issue.
