### ISSUE TITLE
Slides from evangelists

### ISSUE THREAD

**Issue by yosuke-furukawa** [nodejs/evangelism#32]
I would like to share our presentations like this. https://github.com/iojs/evangelism/wiki
Does anyone have an idea where is more suitable space to put our slides? 

IMO, I like wiki. everyone feels free to update the list on wiki. If no problem, I will maintain this! :dancers:

**Comment by bnb** [comment]
I'd be fine with the wiki, but I think a more accessible place would be the website. I don't know if you watched it, but in the last WG meeting, @iojs/website said they would like to have the Evangelism WG help produce content for the website. (See https://github.com/iojs/evangelism/issues/23 for a brief discussion.) This is an example of what I think would be ideal.

**Comment by mikeal** [comment]
The wiki is a good spot for this. We should also highlight new entries in the Weekly Update and on twitter.

**Comment by bnb** [comment]
Is this resolved? A list is in the Wiki ([wiki](https://github.com/nodejs/evangelism/wiki)), but have we been highlighting in the Weekly Update and on Twitter? If not, do we need to start that?

**Comment by mikeal** [comment]
We should document all the kinds of things we want to see in the weekly updates and include slides so that people submit them more often.

**Comment by mikeal** [comment]
My talk in Oslo was a little too "off the cuff" to be useful as a general slide deck.
