### ISSUE TITLE
iojs/io.js repo traffic insight

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/evangelism#40]
Previously we've seen traffic spikes on the io.js core repo every friday, presumably due to the weekly updates. This week, however, traffic was normal on friday.

@mikeal has speculated this may be due to the weekly update being posted much later than it had been before.

Note: I have been keeping eyes on this for longer than the 2 weeks or so the chart shows.

Traffic graph (visible to collaborators only :disappointed:) https://github.com/iojs/io.js/graphs/traffic

Full pics for anyone without access:

![screen shot 2015-03-09 at 4 53 31 pm](https://cloud.githubusercontent.com/assets/1093990/6564184/fe52a0ee-c67c-11e4-8d7a-f427516c3208.png)
![screen shot 2015-03-09 at 4 53 45 pm](https://cloud.githubusercontent.com/assets/1093990/6564186/02a0ae0c-c67d-11e4-918a-65e12251be6b.png)

See also: https://twitter.com/Fishrock123/status/575034708683137024

**Comment by Fishrock123** [comment]
Oddly, Thursdays prior also showed increased clone-age. I'm not sure this is related.

**Comment by Fishrock123** [comment]
Hmmm, at closer look it appears that most of that came from the reconciliation proposal being posted on hacker news. Maybe we had similar things in previous weeks I had overlooked?

**Comment by mikeal** [comment]
This Friday we got out the update much later than usual (around 5 or 6pm PST). Ideally, posts would go out at 9am-10:30am PDT, that gets us the most traction on social media.

The only way to get it out that early would be to draft most if not all of the copy on Thursday.

We should also include a section of issues and PRs that the community might be interested in getting involved in.

**Comment by Fishrock123** [comment]
Some recent stats. Looks like last week was quite active. :D

![screen shot 2015-03-23 at 10 38 51 am](https://cloud.githubusercontent.com/assets/1093990/6782191/ed173f34-d148-11e4-8153-be3ab9ea6a38.png)

![screen shot 2015-03-23 at 10 38 58 am](https://cloud.githubusercontent.com/assets/1093990/6782199/f7066632-d148-11e4-85e8-d95bf2a147b8.png)

**Comment by bnb** [comment]
Closing, as this is outdated. If anyone desires a new insights issue, feel free to open one.
