### ISSUE TITLE
Add @vjk2005 as a committer to the evangelism repo

### ISSUE THREAD

**Issue by mikeal** [nodejs/evangelism#42]
+1 from me.

**Comment by julianduque** [comment]
+1

**Comment by dotproto** [comment]
+1

**Comment by yosuke-furukawa** [comment]
+1

**Comment by blakmatrix** [comment]
@vjk2005 did an awesome job on https://github.com/iojs/evangelism/issues/39 I don't know if this is just for the governance team or not, but I'd like to throw my vote into the ring for his time and contribution to the project.

**Comment by mikeal** [comment]
Added, @vjk2005 you need to accept the invite.

**Comment by vjk2005** [comment]
@mikeal I’m in! Thanks : )
