### ISSUE TITLE
Revive Node Forward repos and maintain them.

### ISSUE THREAD

**Issue by bnb** [nodejs/evangelism#5]
I found the Node Forward [GitHub](https://github.com/node-forward) recently, and I really, really love the repos and the ideas they represent. I think they could be a good starting point for io.js to start building a community outside of the contributors. Whether they stay in Node forward, or move to iojs is up for discussion. Here are some of my thoughts: 

io.js has the most engaged and friendly community I've encountered in OSS behind it.  If we can get the experienced community to lend a hand in teaching those new to io.js, helping those that are stuck with a problem, and provide a common area for people to collaborate and succeed, it would be _so much easier_ to break into io.js. 

The barrier to entry is _extremely high_ for Node. The NodeForward repos are a great opportunity to lower that barrier dramatically for io.js, which would allow us to pick up even more momentum and adoption behind/of the project. 

The problem of starting with Node is something I am extremely familiar with. I'm not the typical programmer, as I haven't progressed from a moderately early position in a long time. I've really struggled with trying to communicate with others and understand what I need to do to really program. I have tried every option I could find on the Internet to try to solve this. There's been a little relief in the past couple weeks, but the types of things in the NodeForward repo are the exact things I needed when I was starting, and still need to an extent, to really be able to become serious about it all. 

The reason I'm pushing hard for this is that I'd like to make this option available for others in the future, so they don't have to struggle as much as I have. I have a solid appreciation for the difficulty of learning to program, and I think the NodeForward repos are a way to ultimately negate a lot of that difficulty for people who started from nothing, like me.

I begun writing this issue by listing the different repos, but kept moving my writing toward more general terms. I did that because they're all about the same thing--helping the community--but are slight variations that help different kinds of people. This is the bottom line, for me. We can help support the io.js community in a way that Node 100% lacked. I think this should be something that is kept active as a way to engage the community and help teach, maintain, and adopt the software we're evangelizing.

**Comment by yosuke-furukawa** [comment]
-1: we maintain the node-forward repository.
+1: we broadcast NG working group messages. https://github.com/iojs/NG

[NG issues](https://github.com/iojs/NG/issues) are so interesting. We should collect community messages and reflect their messages to issues.

**Comment by rosskukulinski** [comment]
Now that the knode and node-forward domains have expired (https://github.com/knode/knode.github.io/issues/26), I hope that iojs/evangelism can rekindle some of the original spirit.  See [this issue](https://github.com/knode/node-meatspace/issues/125) for an ongoing post-mortem.

**Comment by Trott** [comment]
Can this be closed given how much has changed since February/March?
