### ISSUE TITLE
Evangelism: Weekly Update April 3rd

### ISSUE THREAD

**Issue by julianduque** [nodejs/evangelism#51]
Let's begin!

**Comment by rosskukulinski** [comment]
Progress on reconciliation via Node.js Foundation Technical Governance proposals
- https://github.com/joyent/nodejs-advisory-board/pull/30 merged
- @mikeal working on reconciling Project Lifecyce and WIG https://github.com/joyent/nodejs-advisory-board/pull/33

**Comment by julianduque** [comment]
io.js 1.6.3 has been released, changelog can be found [here](https://github.com/iojs/io.js/blob/v1.x/CHANGELOG.md#2015-03-31-version-163-rvagg)

**Comment by Gioyik** [comment]
Progress on reconciliation with Node.js:
- @mikeal posted this on medium: [Help us reconcile node.js and io.js](https://medium.com/node-js-javascript/help-us-reconcile-node-js-and-io-js-c060a9ec1bd4)

Great news for iojs:
- Added support for iojs in [Reactive-Extensions/RxJS](https://travis-ci.org/Reactive-Extensions/RxJS/builds/56671837)

**Comment by Gioyik** [comment]
**Scaleway** provides some ARM resources for the @official_iojs test/build infrastructure: https://twitter.com/rvagg/status/583566261746937856

**Comment by yosuke-furukawa** [comment]
@rvagg opened the discussion forum about our reconciliation in https://github.com/iojs/io.js/issues/1336 .

**Comment by Gioyik** [comment]
This is landed. Should be closed.

**Comment by mikeal** [comment]
Is this posted on Medium yet?

**Comment by Gioyik** [comment]
@mikeal No, is not. I created the weekly update and @yosuke-furukawa merge it. We still are waiting for someone to post it on Medium.

**Comment by mikeal** [comment]
https://medium.com/node-js-javascript/io-js-week-of-april-3rd-a4e1fe0c38c1

**Comment by Gioyik** [comment]
Thanks
