### ISSUE TITLE
Nominate @Giyoik as a evangelism WG member

### ISSUE THREAD

**Issue by yosuke-furukawa** [nodejs/evangelism#58]
He has contributed some articles.
I would like to recommend him as a WG member.

@Gioyik If you have time to contribute, please join and help us!!

**Comment by yosuke-furukawa** [comment]
This commit is my fault. Sorry. https://github.com/iojs/evangelism/commit/9a38c1940883ae096e613275e6498d9a31934d58

**Comment by julianduque** [comment]
+9000

**Comment by Gioyik** [comment]
@yosuke-furukawa Thanks a lot for the nomination. I am interesting in get involved with iojs development and promotion. You can see some issues and things I proposed on iojs to work on and I can continue helping on evangelism too.

I will be glad to be part of WG team.

**Comment by yosuke-furukawa** [comment]
yay!!

**Comment by rosskukulinski** [comment]
If @julianduque is that excited, then I'm a +1 :)

**Comment by Gioyik** [comment]
PR has been merged. Thanks to all who said yes!
