### ISSUE TITLE
High res logo for io.js Podcast

### ISSUE THREAD

**Issue by dotproto** [nodejs/evangelism#59]
I'd like to start using the io.js logo on the podcast page (https://soundcloud.com/iojs). To do so, I'll need a very high res version of the dashavatar asset. Apple requires podcasts to provide a 1400x1400px to 3000x3000px JPG or PNG image for their cover art ([source](https://www.apple.com/itunes/podcasts/creatorfaq.html)).

Assuming the size isn't prohibitively large, I'd lean towards the 3k version as it gives us a bit more future proofing for higher resolution displays. That would also give us the flexibility to downsample the image to 1.5k if necessary.

**Comment by yosuke-furukawa** [comment]
wow!! cool. unfortunately, I don't have the large image. 
But hexb.in has some logos. I found this. https://github.com/maxogden/hexbin/blob/gh-pages/vector/iojs.svg

**Comment by vjk2005** [comment]
@svincent [here you go.](http://dffrnt.com/io/iojs-podcast-logo.png)

**Comment by dotproto** [comment]
@vjk2005 thanks, man, I'll have se them first thing tomorrow morning

**Comment by vjk2005** [comment]
@svincent :+1:

**Comment by Gioyik** [comment]
@vjk2005 there's a way you add and svg, eps, or psd files of the logo to the repo? So everybody could use on their own?

**Comment by dotproto** [comment]
@vjk2005 I'd like to have some specific art for each group (WG/TC) so its easy to determine what you're listening to. The idea here is that you can glance at the album art to tell whether or not you're intersted in the topic being discussed.

Here's something I threw together. If you have the bandwidth I'd welcome another take on it.

![sets](https://cloud.githubusercontent.com/assets/1047763/7214362/b46bf098-e55d-11e4-977c-1c0a0c004d88.png)

**Comment by dotproto** [comment]
@vjk2005 ping!

**Comment by vjk2005** [comment]
@svincent I totally forgot, thanks for the reminder : ) I’ll post the graphics this weekend : )

@Gioyik the logo is already available inside the [Twitter banner source file](https://github.com/iojs/evangelism/blob/master/social-media/twitter%20banner.psd) but I’ll put in a PR tomorrow with just the logo in a separate file.

**Comment by vjk2005** [comment]
@svincent does your podcast platform support GIFs? Cause we could do this interesting thing if it does...
![iojs tc podcast logo](https://cloud.githubusercontent.com/assets/2087804/7375777/90bb09c4-edf8-11e4-8ee4-b69775c7627b.gif)

**Comment by mikeal** [comment]
this is awesome!

**Comment by dotproto** [comment]
Unfortunately, no. Apples podcast XML format only accepts PNG and JPG.

**Comment by vjk2005** [comment]
@svincent after a bunch of false starts I finally have a system that works across the board...
![io js-podcast-logo](https://cloud.githubusercontent.com/assets/2087804/7536347/b5d6b8e6-f5ac-11e4-9222-09b6659e61e0.png)

If you like this set I’ll send you the high-res PNGs tomorrow.

**Comment by dotproto** [comment]
@vjk2005 those look great. I really appreciate the work you've put in! Looking forward to the high res assets :smile:

**Comment by vjk2005** [comment]
@svincent [here you go](http://dffrnt.com/io/io.js-podcast-logos.zip).

**Comment by diagramatics** [comment]
How about versions for localization teams too, for use in social media profile pictures and such?

**Comment by dotproto** [comment]
Just finished updating all the tracks and playlists to use the new assets. Thanks a ton, @vjk2005!

EDIT: Anyone interested can see the updates here: https://soundcloud.com/iojs

**Comment by vjk2005** [comment]
@svincent looks really slick seeing all of them lined up in the SoundCloud feed. It was worth putting the time in to get the design right. The main avatar however has some low-res artefacts. Do you have a higher res image?

@diagramatics I’ll check in a PSD template into the repo soon and the localization teams can customize it by editing the text label.

**Comment by bnb** [comment]
Is there anything else that needs to be done here?

**Comment by vjk2005** [comment]
I think everything’s taken care of here.

**Comment by dotproto** [comment]
Apologies, I should have closed this a while ago.
