### ISSUE TITLE
Evangelism: Weekly Update for May 1

### ISSUE THREAD

**Issue by Gioyik** [nodejs/evangelism#65]
It&rsquo;s Friday, Friday... Gotta get down on Friday!

**Comment by diagramatics** [comment]
I think you might wanna change that IFTTT trigger so the title shows the next publication date instead!

(brought to you by the acclaimed nitpicker)

**Comment by Gioyik** [comment]
@diagramatics I would want it but IFTTT doesn't custom the date to show the one for next week, only has the function to show the current date day. :( So, I need to change it manually after issue is created.

**Comment by yosuke-furukawa** [comment]
REPL magic mode is proposed. https://github.com/iojs/io.js/pull/1513

**Comment by Gioyik** [comment]
johnny-five site launched: http://johnny-five.io/

It's not related at all about io.js but good to promote.

**Comment by Gioyik** [comment]
I discovered that [I'm batman](https://twitter.com/Gioyik/status/592524096765874176) ;) (joke)

![screenshot from 2015-04-26 22-00-55](https://cloud.githubusercontent.com/assets/1834718/7341135/dfee4300-ec61-11e4-83f4-2b779010eecd.png)

**Comment by yosuke-furukawa** [comment]
iojs.org will transfer to iojs.io https://github.com/iojs/io.js/issues/1534

**Comment by julianduque** [comment]
@yosuke-furukawa what I understand is that iojs.io was donated to the project and it will redirect to iojs.org

**Comment by julianduque** [comment]
david-dm.org is now running on iojs: https://twitter.com/_alanshaw/status/592855646124531713

**Comment by yosuke-furukawa** [comment]
@julianduque thanks. I just misunderstood that.

**Comment by yosuke-furukawa** [comment]
v2.0 nightly is out. this is a release candidate version for v2.0. https://iojs.org/download/nightly/v2.0.0-nightly20150428509b59ea7c/

**Comment by yosuke-furukawa** [comment]
I just created a repository for io.js v2.0 introduction. 

https://github.com/yosuke-furukawa/iojs-new-features 

I have only written about v8 updates, If the features are fixed, I will update the repository :dancer:

**Comment by yosuke-furukawa** [comment]
MS releases new Visual Studio Code based on Electron (AtomShell) https://code.visualstudio.com/
(And AtomShell is based on io.js :D).

**Comment by mikeal** [comment]
io.js TC meeting 4/29 
https://www.youtube.com/watch?v=-e675TT4WEA
on soundcloud
https://twitter.com/dotproto/status/594145574204510208

io.js/node.js code convergence plan draft
https://github.com/jasnell/dev-policy/blob/master/convergence.md

initial repo for code convergence work for io.js/node.js
https://github.com/jasnell/node.js-convergence

Node.js Foundation Governance/Convergence Call
https://www.youtube.com/watch?v=u9h0s3YtNAU

**Comment by mikeal** [comment]
there's also an ars article on the Visual Studio Code thing yosuke mentioned http://arstechnica.com/information-technology/2015/04/29/microsofts-new-code-editor-is-built-on-googles-chromium/

**Comment by mikeal** [comment]
release candidate for io.js 2.0 https://iojs.org/download/nightly/v2.0.0-nightly20150428509b59ea7c/

**Comment by mikeal** [comment]
io.js ARM cluster is growing https://twitter.com/rvagg/status/593226114992087041

**Comment by mikeal** [comment]
onboarding another batch of committers https://github.com/iojs/io.js/issues/1552

**Comment by Gioyik** [comment]
Nice, Let's freeze this issue to create a PR with the weekly update. If something else needs to be added, let check for next week at #68 

Thanks a lot @mikeal for last comments for the WU. (If you need to add something else just comment it)

**Comment by Gioyik** [comment]
PR with weekly update is created! Let's check it.

**Comment by mikeal** [comment]
io.js support coming to Modulus http://blog.modulus.io/upcoming-updates-for-nodejs-applications

**Comment by mikeal** [comment]
oh, whoops, missed the cutoff :(

**Comment by Gioyik** [comment]
Don't worry, there's still time, PR has not been merged :)

**Comment by julianduque** [comment]
Published: https://medium.com/node-js-javascript/io-js-week-of-may-1st-362e01678d48
