### ISSUE TITLE
Start evangelizing 2.0.0 RC!

### ISSUE THREAD

**Issue by domenic** [nodejs/evangelism#67]
https://iojs.org/download/nightly/v2.0.0-nightly20150428509b59ea7c/

/cc @rvagg

**Comment by yosuke-furukawa** [comment]
![image](https://cloud.githubusercontent.com/assets/555645/7389173/61798fe2-eea6-11e4-8a10-a90e23485fbd.png)

installed!! excited.

**Comment by yosuke-furukawa** [comment]
I have created simple v2.0.0 introduction repository.
https://github.com/yosuke-furukawa/iojs-new-features 
I will update if io.js feature is renewed. :D

**Comment by Gioyik** [comment]
We should close this. v2.0.0 is already released.
