### ISSUE TITLE
Social Accounts and Social Ideas

### ISSUE THREAD

**Issue by bnb** [nodejs/evangelism#7]
I've grabbed a few accounts on relevant sites, and I thought it would be good for us to coordinate our accounts and to share ideas of what we could do with them. Please share if you've grabbed an account for iojs on any relevant sites, so we can discuss their future.

Sites I've grabbed: 
- [Hacker News](https://news.ycombinator.com/user?id=iojs): Automating this to post articles from the official io.js Medium account might be smart. Officially responding to questions about io.js in io.js-related articles would also be a good idea.
- [EchoJS](http://www.echojs.com/user/iojs): I think the ideas I had for HN are relevant for this account too. EchoJS has shown enormous support for io.js, and it's definitely worth being active and contributing back.
- [Twitch](http://www.twitch.tv/iojs/profile): Programming streams and talk show-style streams have become more popular and supported on Twitch lately. It's definitely a good community to get involved with, as it's established and successful. Ideas for things we could stream would be excellent. I was thinking core contributors could stream working on core. Maybe TC members could stream something? Not 100% sure about everything they do.

**Comment by dotproto** [comment]
Twitch could also be useful for extending the reach of the TC and WG meetings.

**Pros**
- Twitch chat could make it easier for lower experience community members to join into the live conversation.
- Taps into the existing Twitch dev community
- Passive discovery mechanism for people "channel surfing"
- Trail blazing new methods of community outreach

**Cons**
- Multiple chat channels: participants may need to watch both IRC and Twitch streams.
- May require active moderation to keep chat clean.
- Chat may be diluted with people asking "what is this", off topic discussions
- More overhead to set up and keep 2 streams in sync

Some of these issues may be mitigated by having a volunteer or two in both channels. These individuals would relay key questions between Twitch and IRC as required.

**Comment by bnb** [comment]
@svincent One thing that might help alleviate the chat situation is the Twitch chat is actually IRC. It wouldn't be hard to have two tabs or windows open to see both in your IRC client of choice.

**Comment by dotproto** [comment]
@bnb I didn't realize that. That's both kinda insane and really cool.

http://help.twitch.tv/customer/portal/articles/1302780-twitch-irc

**Comment by bnb** [comment]
@svincent Also, with the "what is this" issue, I don't think many people who aren't interested in programming or code would be coming into the channel. In my experience, gamers stick to the game streams. I don't think many people just browse and click random streams--this might be a bit different if the io.js stream makes it into the top (x) streams, but I think the gamers, for the most part, understand what the difference is. 

I am pretty certain "what is this" comments would stay at a minimum most of the time. However, I definitely think having mods in both chats (unique to each chat or simultaneous, doesn't really matter) to answer questions and facilitate chat is pretty much required. From what I've seen of the community so far, that shouldn't really be an issue, though.

**Comment by mikeal** [comment]
I can see how Twitch could be used for screencasts but I don't quite understand how we could use it for TC/WG meetings. I don't know much about Twitch except that it's usually for gaming and I'm slightly terrified of the gamer community :(

**Comment by bnb** [comment]
@mikeal TC/WG meetings can be broadcast in one of two ways, which we'd have to investigate. The first is just a screen/window capture of the meeting, directly streaming from that. That isn't too hard to set up--same as a screencast. 

The other possiblity is using a piece of software that directly links with whatever video service you're using. I just spent over an hour looking for options, and it seems [XSplit Broadcaster](https://www.xsplit.com/products/broadcaster) is the best, and pretty much _only_, option. Take a look at it, and see if you think it would work for TC/WG meetings.

Do note that someone that's actually experienced with streaming would be a lot more knowledgeable and helpful than what I can find by doing searches online without knowing the best keywords to use.

As for the gaming community, they're typically pretty friendly. They'll use crude language and make stupid Internet jokes, but there's no reason to be scared of them. Could you tell me what exactly terrifies you about them? If I know in more detail, I'll probably be able to help you understand better. :smile:

**Comment by mikeal** [comment]
More specifically, this terrifies me http://en.wikipedia.org/wiki/Gamergate_controversy as we've spent a lot of time creating a welcoming environment.

I doubt the TC meetings will move to anything that requires _more_ setup and coordination that what we already do. For all its faults and annoyances Google hangouts-on-air is quite convenient in that it does the conferencing, broadcasts it and automatically dumps it to a youtube channel for us. But even getting that consistent required a bunch of documentation to be written by Rod.

**Comment by dotproto** [comment]
@mikeal, your concern regarding setup/coordination is why I wanted to take a stab at some pros and cons. IMO it's not a clear cut win, but it sounded like an idea worth discussing.

I don't have a ton of experience with Twitch, but I assume all it would take to do a live rebroadcast would be one person in the hangout streaming. That said, I recall a recent TC/WG meeting hitting capacity on hangouts and someone had to bow out; having someone just rebroadcasting may be too much overhead.

**Comment by rosskukulinski** [comment]
How are we planning on managing / sharing account credentials for these accounts?  e.g. the website WG wanted a tweet this morning for their meeting (albeit last minute) and @mikeal was AFK.  I tweeted from my personal account and he eventually got around to RT.

I understand the security issues of sharing the login details -- just wondering if we should all tweet/RT amongst ourselves and @mikeal will RT when he can.

**Comment by mikeal** [comment]
Sharing account credentials is easy, I'm fine with giving them out to other WG members. A much harder thing to figure out is how we split up the work of replying to people and watching search terms without stepping on each others toes :)

**Comment by bnb** [comment]
@mikeal The only work around I know of is to use something like Buffer. Put your posts a minute or two in the future, and everyone checks if there's buffered posts on the same topic/thread/whatever when they save their post. 

That's the only way I know of to do it. It would be really great if others had suggestions.

**Comment by mikeal** [comment]
Buffer doesn't help you with replies, which is the part where I'm worried about people stepping on each others toes. I can share the password with people no problem :)

**Comment by dotproto** [comment]
@mikeal, is this something we might want to create a tool to help us solve, or would that be out of scope? Like the kind of thing that would be better suited for a startup?

**Comment by mikeal** [comment]
I can't imagine such a tool is simple being that nobody seems to have a decent one yet. I've tried all of them. Maybe we should do a call some time soon where we all just compare notes about tools to manage twitter and try to figure out a system. The existing one where I watch everything every day is clearly not sustainable :)

**Comment by bnb** [comment]
@mikeal I generally meant buffering replies to other tweets, in the method I described. Everybody puts tweets in the buffer, and checks before they send to make sure nobody else has responded. :) Or maybe I don't understand how Buffer works.

+1 to a meeting with that as one of the topics.

**Comment by mikeal** [comment]
I don't know how to even do that with buffer :(

**Comment by bnb** [comment]
Discussion has stopped in this issue. Closing - feel free to re-open if you feel necessary.
