### ISSUE TITLE
Worksgroups under Node foundation

### ISSUE THREAD

**Issue by mhdawson** [nodejs/evangelism#70]
In advance of the formation of the Node foundation, we'd like to start working groups using the policies outlined in dev-policy https://github.com/jasnell/dev-policy.  

The current list is:

   https://github.com/mhdawson/workgroup-proposals

We already have a number of  interested parties and plan to get started in the next week or so.  

We wanted to publicize within the io.js community to find additional people that would be interested and it was suggested in a recent call that the best way to do this would be to open an issue on this project.   

If there are people who are interested they can either submit a pull request/open an issue on https://github.com/mhdawson/workgroup-proposals or let me know their contact details by emailing me at michael_dawson@ca.ibm.com

**Comment by mikeal** [comment]
Awesome!

What we usually do in io.js is get the repository for each WG started and put information in the README about how to participate and kick off an Issue about what people would like to see in the agenda for the first meeting.

You probably don't want to promote all 3 of these at once, we'll get more people checking them out if we stagger them a bit. Post in here when each repo is ready for us to point at and we'll tweet about each one with at least a day in between.

I did sort of a "teaser" tweet about these all starting up https://twitter.com/official_iojs/status/595703187593666560

**Comment by yosuke-furukawa** [comment]
Awesome. We will publish this news on next weekly updates.
