### ISSUE TITLE
Square nodejs art for the org avatar

### ISSUE THREAD

**Issue by mikeal** [nodejs/evangelism#76]
Does anyone have a squared off avatar using the nodejs logo we can use for the GitHub org?

**Comment by yosuke-furukawa** [comment]
I don't have it.
But we need new nodejs logo :D

**Comment by gko** [comment]
![logo](https://cloud.githubusercontent.com/assets/1726487/7659969/b4163c50-fb4e-11e4-9c64-ae14ad8de39c.png)

**Comment by gko** [comment]
![logo-white](https://cloud.githubusercontent.com/assets/1726487/7660042/750bc75e-fb4f-11e4-9d3b-9b3d56290791.png)
white one

**Comment by mikeal** [comment]
That isn't very nicely squared though :(

Maybe just the JS hexagon?

**Comment by MoOx** [comment]
Here is the SVG version that should help to get anything you want https://nodejs.org/images/logo.svg

**Comment by MoOx** [comment]
Transparent PNG with the hexagon 

![node-logo-square](https://cloud.githubusercontent.com/assets/157534/7660168/e2f43952-fb47-11e4-868e-47c15335fe80.png)

SVG http://cl.ly/3L2J2h2x0B3P/node-logo-square.svg

**Comment by gko** [comment]
![logo](https://cloud.githubusercontent.com/assets/1726487/7660259/e41b7c10-fb50-11e4-8d61-301d1845ca48.png)
green one

**Comment by mikeal** [comment]
Updated :)

**Comment by MoOx** [comment]
Green version is nice too !

**Comment by gko** [comment]
![js-black](https://cloud.githubusercontent.com/assets/1726487/7660837/5d100a96-fb56-11e4-9fc1-0eea454057a5.png)
gradient one with border radius just in case

**Comment by mikeal** [comment]
:/ I'm not sure about the gradient.

**Comment by gko** [comment]
![js-black](https://cloud.githubusercontent.com/assets/1726487/7660954/514350e6-fb57-11e4-9f44-603a904706aa.png)
without gradient))

**Comment by gko** [comment]
![js-black](https://cloud.githubusercontent.com/assets/1726487/7661084/626c66cc-fb58-11e4-8623-f225e4b4c3e4.png)
beveled one

**Comment by MoOx** [comment]
We should KISS :) The first one seems nice (the current one) maybe just reversed with enough space.

**Comment by bnb** [comment]
Personally, I like the beveled one the most, as it gives a good sense of depth while being extremely simple. Gives the brain something to think about when seeing it, instead of a flat, monotone stamp that doesn't distinguish itself from the rest of the page.

**Comment by bnb** [comment]
@mikeal Do we still need this?
