### ISSUE TITLE
Evangelism WG Join Node Foundation?

### ISSUE THREAD

**Issue by rosskukulinski** [nodejs/evangelism#78]
Hey Everyone.

So as you all probably know, the io.js TC voted to join the Node.JS Foundation.  

Meeting notes: iojs/io.js#1700
Video: http://www.youtube.com/watch?v=UbYiFLf7MpU

As noted in iojs/io.js#1705, all working groups will be moved to the new "nodejs" GitHub organization

> The impact on Working Groups is that they will also be moved in to the "nodejs" org and become part of the Foundation. However, since the Working Groups are autonomous they have the ability to relocate and detach from the Foundation and that is their right. If there are concerns within your Working Group(s) about this move, please discuss it and come to a decision according to the governance procedures you have set up.

So: should the Evangelism Working Group join the Node.JS Foundation?  Do we have any concerns, questions, etc?

**Comment by yosuke-furukawa** [comment]
No objection !!!

**Comment by Gioyik** [comment]
:+1:

io.js evangelism on Gitter disappear now with the change, we should take a look to get it back.

P.S I will really appreciate if I would be added to nodejs organization. Since a time I am part of the WG evangelism :)

**Comment by mikeal** [comment]
we need to talk with gitter staff to move rooms, it's a limitation of gitter right now.

**Comment by julianduque** [comment]
No objection at all :)

**Comment by bnb** [comment]
Sounds good to me.

**Comment by rosskukulinski** [comment]
We don't need 100%, but I figured we should ping @nexxylove and @tonypujals,

**Comment by subfuzion** [comment]
:+1:

**Comment by snostorm** [comment]
Is this WG holding open meetings? The _website_ group has started to try and get ours going again with the merger. The merger is a good opportunity for us to all refocus so I'd like (myself and willing others) to try to work with both groups -- and i18n -- to ensure we have some collaboration :)

**Comment by mikeal** [comment]
This WG hasn't really done meetings, we've mostly just been knocking stuff out pretty regularly through issues and whatnot.

Agreed that this is a good opportunity to refocus -- although the evangelism WG doesn't exactly have another WG it is merging with like the website WG :)

The foundation is also setting up a marketing committee which will obviously have some overlap. Why don't we wait until after the first board meeting where I have a little more information about that and then we can find a good collaboration model between the evangelism WG and the traditional marketing committee at the foundation.

**Comment by subfuzion** [comment]
A good collaboration model would be great, but I'm also curious about what the distinction would look like between the Node Foundation's concept of marketing and io.js' approach to evangelism (which I'd love to see grow to include more of a developer advocacy role as well).

**Comment by bnb** [comment]
@tonypujals Would you care to tell me more about what a developer advocacy role would entail? Also, does the Node Foundation's concept of marketing have documentation or basic information somewhere? I'd like to know so we can try to work both programs into each other.

**Comment by mikeal** [comment]
It'll be a little while before we have a handle on what the marketing groups is and does because the first board meeting hasn't even happened yet and the first marketing committee meeting will be some time after that. We shouldn't hold off on doing anything evangelism related waiting on the foundation's marketing group.
