### ISSUE TITLE
GitHub Pages does not redirect automatically.

### ISSUE THREAD

**Issue by marocchino** [nodejs/evangelism#79]
iojs-ko teams use github pages as bloging tool.
Because of changing name. our blog;s link is changed.
We announced this incidence at twitter but, I will be better to redirect automatically.
Can you guy contact the github people, please?
- http://iojs.github.io/iojs-ko
- http://nodejs.github.io/iojs-ko

**Comment by yosuke-furukawa** [comment]
We should discuss it on website WG.

**Comment by Fishrock123** [comment]
@mikeal uh oh, looks like this was overlooked.

**Comment by fhemberger** [comment]
We have to create a new repo under the iojs org with a 'gh-pages' branch and add an http meta redirect to the new location.

**Comment by mikeal** [comment]
@fhemberger that will forward the website but break the repo forwarding :(

**Comment by fhemberger** [comment]
@mikeal Hmm, you're right. The simplest way would be to place a little note in the master branch with the new URL and disable wiki/issues/PRs on the repo. It's not a perfect solution, but I don't think there will be much traffic coming to a translation group repo's main branch.

**Comment by bnb** [comment]
Is there a final word on this?

**Comment by bnb** [comment]
@Fishrock123 Has anything happened with this on the Website WG side?

**Comment by Fishrock123** [comment]
No this is out of our control and is GitHub's issue.
