### ISSUE TITLE
New Slide Deck about The Node Foundation

### ISSUE THREAD

**Issue by mikeal** [nodejs/evangelism#80]
We've been getting a lot of questions about The Node Foundation and the merger, it would be good to put together a web based slide deck like we did for the roadmap.

I'm giving a talk at ONE-SHOT Oslo where we're getting people on twitter and from the conference to send in questions before the talk, picking 10, and then spending my time answering all of them. I could write this up as a generic deck if we find some HTML slide software that allows me to write up extensive notes for the whole answer.

It would be great if after that people translated it and did a few talks at local non-english meetups as well.

**Comment by bnb** [comment]
Will you be posting the questions and answers here? Also, would the same HTML slide software used in the Roadmap work?

**Comment by vjk2005** [comment]
[slides.com](http://slides.com) is great. I use it [at work](http://dffrnt.com/carton/final/).

**Comment by bnb** [comment]
@vjk2005 Looks pretty solid.

**Comment by bnb** [comment]
What is the status of this, @mikeal? Has anything new been created, or is there still a need for a new set?

**Comment by mikeal** [comment]
Things are changing and progressing so fast any slide deck we do now will be outdated too fast :)

In a month things should be more settled.

**Comment by bnb** [comment]
@mikeal Are things settled to the point where progress can be made?

**Comment by bnb** [comment]
Re-open if the stars align to make this happen.
