### ISSUE TITLE
Evangelism: Weekly Update for May 29

### ISSUE THREAD

**Issue by Gioyik** [nodejs/evangelism#82]
Deposit links and media from this week here.

**Comment by Gioyik** [comment]
Something to add for this WU?

**Comment by Gioyik** [comment]
Schism and Reconciliation in the Node Community by @rvagg
https://nodesource.com/blog/was-this-trip-really-necessary

**Comment by Gioyik** [comment]
First Node TSC Meeting 
https://soundcloud.com/node-foundation/tsc-meeting-2015-05-27

**Comment by Gioyik** [comment]
io.js have got a new Benchmarking Working Group
https://github.com/nodejs/benchmarking/issues/1

**Comment by Gioyik** [comment]
Blog post about iojs + node.js under Node Foundation
http://blog.nodejs.org/2015/05/15/the-nodejs-foundation-benefits-all/

**Comment by Gioyik** [comment]
New implements new `good first contribution` tag for new contributors
https://github.com/nodejs/io.js/labels/good%20first%20contribution

**Comment by Gioyik** [comment]
Blog post from TheNewStack about iojs and node.js new relation.
http://thenewstack.io/io-js-and-node-js-have-united-and-thats-a-good-thing/

**Comment by Gioyik** [comment]
@DJCordhose created a repo about ES6 and iojs implementation
https://github.com/DJCordhose/ecmascript-2015-iojs

---

If I am not wrong @yosuke-furukawa was working on something similar, isn't he?

**Comment by Gioyik** [comment]
No release for this week but there's a discussion issue about v3.0.
https://github.com/nodejs/io.js/issues/1807

**Comment by rvagg** [comment]
probably going to be a 2.2.0 today

**Comment by rvagg** [comment]
https://github.com/nodejs/io.js/issues/1808

**Comment by Gioyik** [comment]
Thank you @rvagg

**Comment by Gioyik** [comment]
I will wait until tomorrow to see if there's a release for this week to create a PR.

**Comment by yosuke-furukawa** [comment]
https://github.com/nodejs/io.js/blob/master/CHANGELOG.md v2.2.0 is released.

**Comment by yosuke-furukawa** [comment]
@yosuke-furukawa But we have to wait v2.2.1, v2.2.0 have a problem. https://github.com/nodejs/io.js/issues/1850

**Comment by Gioyik** [comment]
Well, this issue is locked now with PR #89. If you want to add something for a WU, let's comment it for next one at #88

**Comment by julianduque** [comment]
Published, thanks everybody, great work https://medium.com/node-js-javascript/io-js-week-of-may-29th-89bdeace6056
