### ISSUE TITLE
First meeting for benchmarking workgroup

### ISSUE THREAD

**Issue by mhdawson** [nodejs/evangelism#84]
https://github.com/nodejs/benchmarking/issues/1

Mikeal mentioned once I had the repo setup and the initial issue that I should ping the evangelism team to have it go out on twitter.

**Comment by mikeal** [comment]
I scheduled a tweet to go out at prime time ;)

**Comment by Gioyik** [comment]
This will be publish on #82 weekly update.

**Comment by bnb** [comment]
Thank you, @Gioyik. :+1:
