### ISSUE TITLE
Conference speaking opportunity (October 2015 US)

### ISSUE THREAD

**Issue by danielkhan** [nodejs/evangelism#86]
I am currently looking for a (keynote) speaker for a conference in October 2015 (US).
The talk should cover Node.js in general with some focus on enterprise use cases. The speaker should be member of one of the currently 'official' entities within Node.js/Io.js.

As there will be many representatives of high profile companies this is a great opportunity to establish Node.js in enterprise environments.

**Comment by bnb** [comment]
Hello Dan. Can you give us more details? Where is the location? There are many people who have volunteered to speak at meetups, and I'm sure there are several who would be happy to do so. Also, would travel/room and board/expenses be covered partially or wholly? @mikeal is probably a good person to talk with to find a specific person.

**Comment by rosskukulinski** [comment]
I'm not sure the evangelism repo is the right place for this: I think we'd like to focus this repo on keeping ourselves organized.  However, this does bring up a good point: How do we help people find speakers for events?  In the good 'ol days, we had https://github.com/knode/speakers, but that never took off.

**Comment by joemccann** [comment]
Hey @danielkhan, Joe McCann here, CEO and Cofounder of NodeSource, the Enterprise Node.js software company.  We have helped myriad enterprise companies transition and more effectively adopt and integrate Node.js into their IT.  We've worked with companies ranging from PayPal and Intuit to Uber and even NASA to name just a few.

I'd be happy to present a bit on what we're seeing at a macro level in the Enterprise with specifics where available.

Feel free to email me directly at

joe@nodesource.com

Cheers!

**Comment by danielkhan** [comment]
@rosskukulinski, @bnb - basically I was sent here by @mikeal.
Being evangelist myself I would also appreciate a single entry point for speaker requests though. 

I will collect all applications and discuss them internally.

**Comment by rosskukulinski** [comment]
Hi @danielkhan -- sorry, I think my last message came across, well, cross, and I didn't mean to.  I think right now, this repo is probably one of the best places TO ask your question - so sorry for jumping on you.  A +1 for talking with the NodeSource folks, btw.

My comment was more thinking that we, as the evangelism folks, might want to consider having a central place for speaker requests, thats not here.

**Comment by bnb** [comment]
@rosskukulinski This is what I was kind of hinting at in my previous comment: https://github.com/nodejs/website/issues/110

It is an issue on the Website WG repo asking for speakers to evangelize io.js. I'm going to write a spiritual successor could be made in the evangelism repo to get a fresh list of people.

**Comment by danielkhan** [comment]
@rosskukulinski - I didn't take it personally at all :)
Basically I am really interested in taking part in this currently fast shifting community.
The fact that I am currently also looking for a speaker myself is a coincidence.

**Comment by mikeal** [comment]
Yup, I sent @danielkhan here. This is as good a place as any to ask about finding speakers. If we don't know who to send directly we have the resources to point the community at a CFP, etc.

**Comment by danielkhan** [comment]
You've got mail, @joemccann.

**Comment by yosuke-furukawa** [comment]
Sounds interesting. If you have some webpages, please share us. I will add the conference on weekly updates :D

**Comment by danielkhan** [comment]
@yosuke-furukawa - thank you! I will share details as soon we have the Node.js parts of the agenda ready.

**Comment by bnb** [comment]
@danielkhan Is it okay to close this? I would hope you have your speaker by now.

**Comment by bnb** [comment]
Outdated.
