### ISSUE TITLE
Evangelism: Weekly Update for June 5

### ISSUE THREAD

**Issue by Gioyik** [nodejs/evangelism#88]
It&rsquo;s Friday, Friday... Gotta get down on Friday!

**Comment by bnb** [comment]
Marius.co switches to io.js from Node 0.10: RE https://twitter.com/edatrero/status/605040698992164864

**Comment by bnb** [comment]
Up and running with io.js and Docker - http://blog.codefresh.io/up-and-running-with-io-js-and-docker/?utm_content=buffer75f6e&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer

**Comment by bnb** [comment]
###### Previous Weekly Update - do not use

> Was this trip really necessary? - https://nodesource.com/blog/was-this-trip-really-necessary

**Comment by Gioyik** [comment]
> Was this trip really necessary? - https://nodesource.com/blog/was-this-trip-really-necessary

This was published on past WU. :)

**Comment by bnb** [comment]
Ah, okay! Adding a do not use to it.

**Comment by Gioyik** [comment]
Don't worry. Thanks a lot for the comments and inputs for WU. I really appreciate them

**Comment by bnb** [comment]
New PluralSight course: io.js (or is it?) http://www.marcusoft.net/2015/06/new-pluralsight-course-iojs-or-is-it.html

**Comment by Gioyik** [comment]
I was waiting for a release past week, but seems that not happened. I created the PR for past week, let me know if you want to add something else.

**Comment by julianduque** [comment]
Published! https://medium.com/node-js-javascript/io-js-week-of-june-5th-48af5e69f16e
