### ISSUE TITLE
Who's using io.js?

### ISSUE THREAD

**Issue by a0viedo** [nodejs/evangelism#9]
There's a list somewhere?

**Comment by bnb** [comment]
There's this: https://github.com/iojs/website/wiki/Projects--and-services-using-io.js#hosting

**Comment by a0viedo** [comment]
[This](https://news.floobits.com/2015/02/23/on-moving-to-io.js/) is also related. I heard that Uber might be using it on production, anyone have more info?

**Comment by bnb** [comment]
We keep all links to people using and adding support for io.js in the weekly update posts. Here's this week's: https://github.com/iojs/evangelism/issues/4 If you see anything that's not posted there, be sure to add it so we can include it in the official weekly update!

**Comment by bnb** [comment]
About Uber: No, I haven't heard anything about that. That'd be super cool and a big win for us if it were true.

**Comment by bnoordhuis** [comment]
@a0viedo @bnb https://twitter.com/mranney/status/540013975568535553

**Comment by dotproto** [comment]
Cross linking with the relevant website issue: iojs/website#241
