### ISSUE TITLE
Iterate on Weekly Update process

### ISSUE THREAD

**Issue by mikeal** [nodejs/evangelism#93]
I'd like to start a discussion about how we might improve the weekly update process.

Everyone has done a great job of keeping them consistent but it's still quite a lot of manual work taken on by a few people to get it out.

Can we think of any ideas that might:
- Make it easier for people to contribute in a way that doesn't require we duplicate their effort.
- Automate the publishing side (Medium)

I'm wondering if it might be better, but not too laborious, to have people send a PR for their additions to the update. If it's already a markdown file we might be able to more easily automate the publishing. Does Medium have an API or a library to do the publishing yet?

**Comment by diagramatics** [comment]
This might be complicated, but a template that we can pass JSON values to and get the results as a Markdown file would be nice. Helps reduce the grammatical errors to a certain extent.

As for the Medium API, I haven't found anything official.

**Comment by mikeal** [comment]
It's a bit difficult to encode the formatting in to the JSON strings, especially if we're asking new contributors to do so.

**Comment by yosuke-furukawa** [comment]
In iojs-ja, we automated the process using werker. We translate the weekly updates and merge it to [blog.iojs.jp repo](https://github.com/iojs-jp/blog), then publish the blog. that is so easy to publish.

However, Medium does not have an API. If we can change the blog platform to gh-pages, that is easy to publish.

BUT I would like to get the Medium ID/PASS and twitter ID/PASS first of all.
How do I get the permission?

**Comment by mikeal** [comment]
I can email you the twitter id/pass, and that's also how you login to Medium, what's your email?

**Comment by yosuke-furukawa** [comment]
my email is yosuke.furukawa@gmail.com Thank you!!

**Comment by bnb** [comment]
Here's an idea we can publicize, and is pretty easy for the user: Use some hashtag like #nodethisweek, #nodeweek, #nodenews, or some other one so people can easily tweet us with news they find, create, or distribute. 

Let enterprise Node users use it for announcements, jobs, code, etc. and let average users know to send us content like blog posts, modules, etc., and spin it as getting free publicity and recognition in a public way by the Foundation.

**Comment by Gioyik** [comment]
Complement that @yosuke-furukawa said. Medium has not API. If it had one we could automated the publishing process as I do with IFTTT and the weekly issue in the repo. The hashtag on twitter is useful if we want to filter the result for WU but not something to do this process more faster, I think (maybe I don't understand well the point).

I have a question about this:

> Make it easier for people to contribute in a way that doesn't require we duplicate their effort.

What does mean _duplicate their effort_ when people contribute?

I think the process to select what's going on in the next WU is good, everyone can add a link, video or discussion issue as suggestion for the WU; and the way (using the PR tools) to suggest changes on the markdown file (PR with collected info for WU) is correct, I receive a lot of feedback for changes on PR's I created. The unique (I think) situation to take care for me is search and automated process to publish the WU markdown file after is done on the repo on Medium and Social accounts. (Social accounts it's more easier to automate if situation with Medium is solved first)

**Comment by mikeal** [comment]
> What does mean duplicate their effort when people contribute?

What I mean is this:
- One person writes text in a comment.
- Another person writes that text again as markdown in this repo.
- Possibly another person still copies that to Medium and adjusts the formatting.

**Comment by diagramatics** [comment]
I had discussed the formatting adjustments in the Markdown files so manually publishing the thing on Medium takes as few steps as possible. It's better if we write the "io.js Week of ..." and the subtitle on the Markdown too so the one responsible of pasting it to Medium doesn't need to make one. Title should be in H3 too because Markdown's H3 and H4 is Medium's H2 and H3.
