### ISSUE TITLE
Social Media Campaign to Use/Test RC candidates

### ISSUE THREAD

**Issue by mikeal** [nodejs/evangelism#95]
Let's help these people out with a good campaign https://github.com/nodejs/website/issues/369

**Comment by bnb** [comment]
How about a scheduled series of weekly tweets (different text and multiple days) to alert people/remind them to try it out?

**Comment by bnb** [comment]
`Want to help Node (|| io.js)? Run the nightly builds to help test the next major version! <link>`

`Test the Node (|| io.js) nightly builds to find bugs and improve the next major release! <link>`

`Be on the bleeding edge and help node by running the nightly builds! <link>`

`We need YOU! Help Node (|| io.js) by running the nightly release candidate build! <link>`

`Like Node (|| io.js)? Like testing? Help Node (|| io.js) out by testing the nightly release candidates`

**Comment by mikeal** [comment]
Is there a single link to "latest nightly" we can use for all of these?

What is the idea schedule to reach all active timezones but not annoying people in the same timezone?

**Comment by bnb** [comment]
@mikeal A single, immutable link is definitely a possibility, and would make the messages useful no matter when they are viewed. @nodejs/build is probably the group to talk to, as it would be a forwarding thing on the domain.

As for schedule for maximum reach, here's a basic plan:
- Monday: Mid-day US
- Wednesday: Mid-day EU
- Friday: Mid-day Asia/Russia
