### ISSUE TITLE
Evangelism: Weekly Update for June 19

### ISSUE THREAD

**Issue by Gioyik** [nodejs/evangelism#97]
It&rsquo;s Friday, Friday... Gotta get down on Friday!

**Comment by yosuke-furukawa** [comment]
Linux foundation announces nodejs foundation community.
http://www.linuxfoundation.org/news-media/announcements/2015/06/nodejs-foundation-advances-community-collaboration-announces-new

**Comment by yosuke-furukawa** [comment]
ES2015 is approved, ES2015 is now an ecma standard. https://esdiscuss.org/topic/ecmascript-2015-is-now-an-ecma-standard
(This news is not related io.js directly, but every JavaScript developers should know the news :+1: )

**Comment by bnb** [comment]
So, @rvagg just posted here: https://github.com/nodejs/evangelism/issues/100#issuecomment-113336507

Basically, he said we're first-class citizens in the social marketing of Node now. What do you think about moving this content to the official Node.js Blog, under the Node name? I think it is an absolutely _perfect_ time to do so because of the Linux Foundation announcement this week. 

Additionally, we can also broaden our scope of content to include to anything Node related - if you guys don't feel up to it, I can collect and write about that content tomorrow. Letting me know by ~2PM EST (18:00GMT) would be best.

**Comment by yosuke-furukawa** [comment]
> What do you think about moving this content to the official Node.js Blog, under the Node name?

+1 I agree.

**Comment by Gioyik** [comment]
I agree :+1: 

What could be the procedure now to create WU with this migration?

**Comment by bnb** [comment]
@Gioyik So the repo [joyent/node-website](https://github.com/joyent/node-website) will be transferring to nodejs/nodejs.org. To post a blog post, you can follow the instructions here: [joyent/node-website/tree/master/doc/blog](https://github.com/joyent/node-website/tree/master/doc/blog). 

We can create a PR there that follows those guidelines. I've sent a warning over there (https://github.com/joyent/node-website/issues/141) to ask them if there's anything else that needs to be done to get this taken care of ASAP. This will be easier once it's in the nodejs organization. Let me know if there's anything else I can do, including content curation.

**Comment by bnb** [comment]
**Top billing:** IBM VP Angel Diaz talks about the new Node.js Foundation - https://www.youtube.com/watch?v=9iuqi8c91mg&feature=youtu.be

**Comment by bnb** [comment]
Blog Post: Using Cloud Code, Mobile Application Security, Node.js and Bluemix - http://www.raymondcamden.com/2015/06/09/using-cloud-code-mobile-application-security-node-js-and-bluemix

**Comment by bnb** [comment]
**Top Billing (popular article):** Should I use Node.js or io.js? And which version? - https://strongloop.com/strongblog/should-i-use-node-js-or-io-js-and-which-version/

**Comment by bnb** [comment]
Blog post: Deploying Multiple Node.js Apps with strong-pm.io - https://strongloop.com/strongblog/deploying-multiple-node-js-apps-with-strong-pm-io/

**Comment by bnb** [comment]
Blog post: The smartest way to program smart things: Node.js - http://radar.oreilly.com/2015/06/the-smartest-way-to-program-smart-things-node-js.html

**Comment by bnb** [comment]
Blog post: How to Implement Node + React Isomorphic JavaScript & Why it Matters  - https://strongloop.com/strongblog/node-js-react-isomorphic-javascript-why-it-matters/

**Comment by bnb** [comment]
Blog post: Node.js async in practice: When to use what? - http://www.sebastianseilund.com/nodejs-async-in-practice

**Comment by bnb** [comment]
Blog post: Not Really Single Page Apps - http://dailyjs.com/2015/06/19/not-really-single-page-apps/

**Comment by bnb** [comment]
Blog Post: Containerizing Node.js Apps with Docker and StrongLoop - https://strongloop.com/strongblog/containerizing-node-js-apps-with-docker-and-strongloop/

**Comment by bnb** [comment]
Interesting site: http://builtinnode.com/

**Comment by mikeal** [comment]
**Top billing:** Interview in Free Software Magazine about the merge and the foundation http://www.freesoftwaremagazine.com/articles/interview_mikeal_rogers_nodejs_fork_ended_giant_unifying_step_forward

**Comment by danielkhan** [comment]
I just joined lately but I have 2 recent blog posts that look at Node.js from a business and from a developer perspective. I don't know if this is the right place for it but you can use them if you wish. Especially the first one received great feedback.

http://apmblog.dynatrace.com/2015/04/09/node-js-is-hitting-the-big-time-in-enterprise-markets/
http://apmblog.dynatrace.com/2015/06/02/keeping-things-simple-with-node-js/

**Comment by bnb** [comment]
Blog post: Containerizing Node.js Apps with Docker and StrongLoop - https://strongloop.com/strongblog/containerizing-node-js-apps-with-docker-and-strongloop/

**Comment by bnb** [comment]
@danielkhan We still haven't come up with a policy for what content is and isn't to be included in the weekly update for nodejs.org yet. I've been posting blog posts on the chance that we want to include them (which I think is a good idea). 

Either way, we appreciate you dropping your posts here, and they'll be included if it is decided blog posts are to be included.

**Comment by bnb** [comment]
Blog post: Comparing NodeJS IDEs (now with ST3 and WebStorm!) - https://paulb.gd/comparing-nodejs-ides/

**Comment by bnb** [comment]
**Top Billing:** Understanding npm - https://unpm.nodesource.com/

**Comment by mikeal** [comment]
Let's cut out a section for pieces from members of the foundation talking about joining it.
- Modulus/Progress http://blog.modulus.io/modulus-and-progress-software-join-nodejs-foundation
- IBM https://developer.ibm.com/bluemix/2015/06/16/node-js-foundation-launched/
- Groupon https://engineering.groupon.com/2015/node-js/groupon-is-proud-to-be-a-part-of-the-new-node-js-foundation/
- NodeSource https://nodesource.com/blog/nodesource-to-join-the-nodejs-foundation
- Famous Industries https://blog.famous.org/famous-industries-joins-the-node-foundation/
- Nearform http://www.nearform.com/nodecrunch/thanks-everybody-making-node-foundation-happen/
- Strongloop https://strongloop.com/strongblog/announcing-the-node-js-foundation/
- GoDaddy https://garage.godaddy.com/godaddy/godaddy-supports-the-new-node-js-foundation/
- Microsoft http://blogs.microsoft.com/firehose/2015/02/11/microsoft-joins-industry-to-create-node-js-foundation/

**Comment by bnb** [comment]
@mikeal Absolutely! Thanks for making that list! Really great addition to the post.

**Comment by bnb** [comment]
Blog post: Node.js High Availability at Box - https://www.box.com/blog/node-js-high-availability-at-box/

**Comment by bnb** [comment]
Video tutorial: Deploying a Scalable Node.js Application with Docker - https://www.youtube.com/watch?v=uhNpSWI8MTM

**Comment by bnb** [comment]
Maybe separate tutorials from theory crafting with the blog posts, and the video tutorial can go in with the tutorials.

**Comment by bnb** [comment]
Blog post by Foundation member: Top 10 Reasons To Use Node.js - http://blog.modulus.io/top-10-reasons-to-use-node

**Comment by bnb** [comment]
~~Next week we should have a section for foundation-member content.~~

**Comment by mikeal** [comment]
We shouldn't split the content between "members" and "non-members." The weekly update should be about the whole community. The only reason we would have a section this week about members is to group all the posts about joining the foundation.

**Comment by bnb** [comment]
Blog Post: Why Node.js is Ideal for the Internet of Things - http://www.programmableweb.com/news/why-node.js-ideal-internet-things/analysis/2014/07/31

**Comment by bnb** [comment]
@mikeal Okay, that sounds good to me.

**Comment by bnb** [comment]
Blog post: Painless Microsoft SQL Server with Node.js and seriate - http://developer.leankit.com/painless-sql-server-with-nodejs-and-seriate/

**Comment by bnb** [comment]
Just FYI, I was previously searching via all tweets with the hashtag #nodejs. I have refined my search to more popular posts with filters, as there was a lot of spam-y, automated content that was just noise preventing me from finding content that the community valued. I'll share the filters, if anyone wants them.

**Comment by bnb** [comment]
Community Event: Nodeday (UK) - http://nodeday.com/

**Comment by bnb** [comment]
Community Slidedeck: http://www.afronski.pl/presentations/june-2015-zeromq-in-nodejs@berlinjs/presentation.html#1

**Comment by bnb** [comment]
No idea what EE is, but, if it's relevant: 

Blog Post: Golden rules for JS introduction to your EE project - http://blog.upwardsmotion.com/golden-rules-for-js-introduction-to-your-ee-project/

**Comment by Gioyik** [comment]
Wow, so much entries for this WU. o/

Well, until we have access to the new Nodejs site, we will continue publishing on Medium. I am going to create the weekly update file.

**Comment by Gioyik** [comment]
Ok I am getting confused with a lot of issues related to what's next for evangelism group and upcoming WU. I am going to ask to get clear the situation:
- Should we publish this WU on Medium?
- Should we create a PR on joynet/node-website and wait to be published there?

**Comment by mikeal** [comment]
Publish on Medium from the iojs twitter as usual. We won't get access to either the domain name or the nodejs twitter account by the end of the day.

**Comment by Gioyik** [comment]
Got it!

**Comment by bnb** [comment]
Interesting site: https://nodesecurity.io/

**Comment by Gioyik** [comment]
I created a PR for this WU. Please review it and tell me if there's something to change or correct.

**Comment by yosuke-furukawa** [comment]
Merged !!! I would like to publish new io.js weekly updates.

**Comment by yosuke-furukawa** [comment]
published https://medium.com/node-js-javascript/io-js-week-of-june-19th-3f18a68dbe21
