### ISSUE TITLE
Request from the Website WG: Blog post prompting the community for a design for the new nodejs.org

### ISSUE THREAD

**Issue by bnb** [nodejs/evangelism#99]
I was in the Website WG meeting that happened today, and a few decisions have been made. Both the current io.js site and the current node.js site are being scrapped, put and put into deep sleep. 

A new site is going to be created - while it's in development, it will be located at @nodje/new.nodejs.org. Before going to the Node Foundation's Marketing team, the Website WG would like to try to get the community to design a site that they can build.

So, the Website WG is asking for the @nodejs/evangelism WG to write a blog post as a prompt to the community asking for a design they can use.

The specifics haven't been ironed out yet, so I'll probably bring this up again as soon as the website repositories are in their final resting places. However, if you guys would like to start outlining a blog post for it, that'd be great. Something to consider is that we now have the Node.js official blog to post to, which is where I think would get the most traction. 

Since we're past the point of the merger, I think it makes sense to use the Node.js blog, as I imagine it has a deeper impact on the relevance and seriousness of writings this group comes up with.

**Comment by mikeal** [comment]
We need to figure out how we're going to structure this. We certainly don't want a "design by committee" situation. We also need full, real, designs and not just a smattering of logos like we asked for in the logo thread.

Is the tooling in place for building out the right pages? Can we task someone with writing a document up about "how to submit a site design" calling out the assets to modify, etc.

Also, if we are going to modify the branding in any way we need to do that first so that each designer can use it, and that's one thing that we are a little blocked on until the marketing team meets.

**Comment by bnb** [comment]
When you're asking about the tooling being in place for the right pages to be built, are you talking about what @new.nodejs.org (why can't I mention that repo? Same thing happened to @rebelrobot mentioning nodejs/docs) will need to put in place? As in what pages will need to be initially designed for consideration in the submissions?

In terms of branding, I don't think changing Node's branding is a good idea - the branding is well-recognized and beloved by the community. There's not a reason to change it, and I think we may even get lash back if we _do_ change it. We're putting forward the future of Node - maintaining that we're still Node is important.

**Comment by mikeal** [comment]
@bnb you can't mention repos you can only mention users and teams. we have several teams that are identical to repos so this is a little confusing.

**Comment by mikeal** [comment]
> In terms of branding, I don't think changing Node's branding is a good idea

Nobody is talking about or considering a re-brand. The hexagons are so widely understood and accepted that it would be insane to throw them out. What is being discussed is an "update" to the branding, something a little easier to use when square logos are required and something that speaks a little more to the _many_ uses of node. Example:

![changesstarbucks](https://cloud.githubusercontent.com/assets/579/8259524/f30dd592-1671-11e5-8202-a5805189bc85.jpg)

**Comment by bnb** [comment]
@mikeal 1: Thanks for the info, I had no idea.

2: Okay, I thought you meant something along the lines of a completely new logo. Iteration isn't a problem, but how will we handle that process? It's probably going to be lengthy if it's design-by-committee, so what's the alternative?

**Comment by vjk2005** [comment]
Would you guys like me to give it a shot?

**Comment by bnb** [comment]
@vjk2005  We'd be happy if you were to give it a shot, but as I said there needs to be foundation laid by the Website WG before we start taking submissions. We've loved your work in the past, and would appreciate a submission from you once we are taking submissions.

**Comment by tetsuo** [comment]
What @mikeal said reminded me of this nice read from alistapart: [Good Designers Redesign, Great Designers Realign](http://alistapart.com/article/redesignrealign)

**Comment by bnb** [comment]
Closing, it's already been publicized as much as it could be.
